muSE: muse_builtin_networking.c File Reference
muse_builtin_networking.c File Reference
#include "muse_opcodes.h"
#include "muse_port.h"
#include "muse_utils.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>
Macros
#define MUSE_SO_REUSE SO_REUSEADDR
On *BSD (including MacosX), it looks like we have to use SO_REUSEPORT instead of SO_REUSEADDR to achieve the same effect.
Functions
muse_boolean muse_network_startup (muse_env *env)
In the POSIX version, we initially setup to block the SIGPIPE signal.
muse_cell fn_wait_for_input (muse_env *env, void *context, muse_cell args)
muse_cell fn_fetch_uri (muse_env *env, void *context, muse_cell args)
Usage: (fetch-uri uri ['refresh] [headers])
muse_cell fn_symbol (muse_env *env, void *context, muse_cell args)
muse_cell fn_http_parse (muse_env *env, void *context, muse_cell args)
muse_cell fn_http_respond (muse_env *env, void *context, muse_cell args)
Misc
muse_cell fn_format (muse_env *env, void *context, muse_cell args)
Point to point communication
Made possible through the functions
with-incoming-connections-to-port and
open
typedef struct muse_server_stream_socket__ muse_server_stream_socket_t
muse_cell fn_open_connection (muse_env *env, void *context, muse_cell args)
muse_cell fn_with_incoming_connections_to_port (muse_env *env, void *context, muse_cell args)
Multicast messaging
A simple multicast mechanism is implemented using UDP datagrams.
You join a multicast group by creating a muSE port using the function multicast-group. Once the join succeeds, you can broadcast a message to the group and can receive broadcast messages from any member of the group using the standard read and write functions.
Immediately after a read, information about the sender is stored internally and you can reply to the sender alone by using the reply function. reply works only with multicast group ports. It is a programming error to use it with other ports.
You can use the wait-for-input function to wait for a message from a multicast group as well.
muse_cell fn_multicast_group (muse_env *env, void *context, muse_cell args)
muse_cell fn_reply (muse_env *env, void *context, muse_cell args)
muse_cell fn_multicast_group_p (muse_env *env, void *context, muse_cell args)
Detailed Description
Author
Srikumar K. S. (kumar.nosp@m.@muv.nosp@m.ee.co.nosp@m.m)
Copyright (c) 2006 Jointly owned by Srikumar K. S. and muvee Technologies Pte. Ltd.
All rights reserved. See LICENSE.txt distributed with this source code or http://muvee-symbolic-expressions.googlecode.com/svn/trunk/LICENSE.txt for terms and conditions under which this software is provided to you.
Function Documentation
muse_cell fn_fetch_uri (muse_env * env, void * context, muse_cell args)
Usage: (fetch-uri uri ['refresh] [headers])
Evaluates to the cached local file path for the uri. If 'refresh is passed, then it downloads the uri again if it is out of date, even if it is already in the cache. headers is a list of strings, each expected to contain one line of the extra HTTP header to be passed to the request. The header strings should not end with CRLF.
muSE exceptions:
'fetch-uri:network-error uri Indicates a fundamental problem with connecting to the net. Allows you to replace the uri with a default file path.
'fetch-uri:bad-resource uri Indicates that the uri is either badly formatted or is referring to an invalid resource. In this case, you can continue by replacing the uri with either a file or a default uri that's known to work.
'fetch-uri:unsupported uri Indicates that the uri is not a http uri or of a type that can't be supported. In this case, you are allowed to replace the uri with a file.
'fetch-uri:cache-failure uri Indicates a problem downloading the uri and storing it in the system cache. In this case, you're allowed to replace it with a file.
Note
Supports the
References buffer_alloc(), buffer_char(), buffer_free(), buffer_length(), buffer_putc(), buffer_substring(), buffer_to_string(), buffer_to_symbol(), _muse_port_base_t::env, fn_symbol(), muse_add_recent_item(), muse_cell_type(), muse_cons(), MUSE_CONS_CELL, muse_csymbol(), muse_evalnext(), muse_list(), MUSE_NIL, muse_raise_error(), muse_text_contents(), muse_trace_pop(), muse_trace_push(), muse_try(), port_eof(), port_getc(), and port_ungetc().
Referenced by fn_http_respond().
muse_cell fn_symbol (muse_env * env, void * context, muse_cell args)
 (symbol "symbol-name")
Interns the symbol of the given textual name and returns a unique symbol cell.
Referenced by fn_fetch_uri().
muse_cell fn_http_parse (muse_env * env, void * context, muse_cell args)
 (http-parse port) -> (('GET url "HTTP/1.1") ('Header1 "value1") ('Header2 "value2") ...)
 (http-parse port) -> (('POST url "HTTP/1.1") ('Header1 "value1") ('Header2 "value2") ...)
Parses the series of http headers from the given port (can be any port) and returns an association list as shown above.
Supports the.
References fn_format(), muse_add_recent_item(), and port_putc().
Referenced by fn_http_respond().
muse_cell fn_format (muse_env * env, void * context, muse_cell args)
 (format ...args...)
Converts each arg to a string, concatenates all the strings and returns the result as a single string. Things that support the 'frmt' view such as bytes? and object? convert themselves to strings.
Objects, in particular, get their "as-string" methods invoked to get a string representation. The "as-string" can also be a field. If it isn't a method, its value is used as the string representation of the object. In particular, the "as-string" implementation can return or be any object which can be converted to a string, such as int, float or even another object.
For example -
 > (define ex
     (object ()
       'name     "telepathic-robot"
       'id       3
       'as-string (fn (self) (format self.name "-" self.id))))
 > (format "object=" ex)
 object=telepathic-robot-3
Referenced by fn_alert(), fn_http_parse(), fn_http_respond(), and fn_vector().
muse_cell fn_http_respond (muse_env * env, void * context, muse_cell args)
 (http-respond port code headers-alist crlf?)
Parameters
port The port to which to write out the headers.
code A numeric response code such as 200. Pass 0 to skip the response line.
headers-alist An a-list such as
 '((Content-Type . "text/html"))
crlf? Pass T if you want a blank line to terminate the list of headers. If you pass (), you can make another call to http-respond to write out some more headers.
Supports the
References fn_fetch_uri(), fn_format(), fn_http_parse(), fn_multicast_group(), fn_multicast_group_p(), fn_open_connection(), fn_reply(), fn_wait_for_input(), fn_with_incoming_connections_to_port(), muse_int_value(), muse_network_startup(), MUSE_NIL, muse_port(), MUSE_SYMBOL_CELL, muse_symbol_name(), MUSE_TEXT_CELL, muse_text_contents(), port_putc(), and port_write().