muSE: Modules
Modules
Functional objects
A module is a value that contains a set of variable bindings you can refer to.
Functions
muse_cell fn_module (muse_env *env, void *context, muse_cell args)
muse_cell module_find_symbol_with_value (muse_env *env, void *obj, muse_cell value)
Searches this module's symbols for a symbol defined to the given value.
muse_cell module_syntax (muse_env *env, module_t *m, muse_cell args)
muse_cell fn_require (muse_env *env, void *context, muse_cell args)
(require ModuleSymbol ...)
muse_cell fn_import (muse_env *env, void *context, muse_cell args)
Detailed Description
A module is a value that contains a set of variable bindings you can refer to.
You define a module using the module syntax which creates a module value. Symbols exported from a module are accessed using the long form notation
ModuleName.exportSymbol
. If you want to use a module's exports just by their short names, you can import its definitions using import.
Function Documentation
muse_cell fn_module (muse_env * env, void * context, muse_cell args)
 (module MyMod (exportA exportB ...) ...body... )
Such a module expression introduces global symbols MyMod.exportA, MyMod.exportB, etc. with the appropriate bindings.
Within a module, you use the usual define function to introduce definitions for whatever ie exported from the module. If you introduce definitions of other symbols, they will be visible only to the module block and will disappear from all scope when the module completes loading. Such local symbols' values can be usefully captured in closures however.
The module expression defines the value of the MyMod symbol to be a function of one argument. This function takes a symbol and evaluates to its value in the context of the module.
Another way to define a module is to place
 (module MyMod (exportA exportB ...))
at the start of a module file. In this case, the rest of the file will be considered to be the module definition and will be read in. The advantage of this approach over the top approach is that using the top approach you cannot define macros for local use within the module. Whereas in the above approach you have all the facilities normally available via load.
Modules are values. Therefore you are free to define functions that return modules, etc. Modules may export other modules as well, which can be accessed using the dot notation - for example: m1.m2.m3.val
Module exports are mutable. You can use the generic get and put functions to fetch and modify the exports of a module. You cannot, however, add new exports or remove exports from a module using "put". To add new exports or to change existing definitions (for example, to reload a module), you can evaluate
 (module M (newexport1 oldexport1 ...) ...)
If your module is defined in a file and you've edited it, you can use this property to redefine the module by simply callind
 (load "mymodule.scm")
to have your module's definition changes take effect. Note that this refresh mechanism cannot be used to remove module exports.
Right before the body of a module is evaluated, the new module object itself is made available in the "recent computations" list so that you can get at the "current module" object by evaluating the expression
 (the module)
. This holds even for anonymous modules.
Exceptions
error:key-not-found Handler format:
 (fn (resume 'error:key-not-found obj key) ...)
Raised when the given key cannot be found in the given module during a lookup. You can resume by resolving the intended value.
error:immutable-key Handler format:
 (fn (resume 'error:immutable-key module key) ...)
Raised if the module doesn't export the given key. Only exported keys can be modified using put. You can resume with the intended result of the put operation.
error:invalid-module-name Handler format:
 (fn (resume 'error:invalid-module-name name) ...)
Raised if this module definition is trying to augment an existing module, but the value of the given module name doesn't refer to a module and neither is it an undefined symbol.
References fn_require(), muse_bind_copy_expr(), MUSE_CONS_CELL, muse_functional_object_data(), muse_mk_functional_object(), MUSE_NIL, muse_raise_error(), MUSE_SYMBOL_CELL, and muse_symbol_value().
Referenced by module_find_symbol_with_value().
muse_cell module_find_symbol_with_value (muse_env * env, void * obj, muse_cell value)
Searches this module's symbols for a symbol defined to the given value.
If any of the module's symbols is itself is a module, then it recursively searches the sub modules. The returned value is a list that gives the path through the module hierarchy to the value.
References fn_module(), module_find_symbol_with_value(), muse_add_recent_item(), muse_bind_copy_expr(), MUSE_CONS_CELL, muse_current_port(), muse_do(), muse_expect(), muse_functional_object_data(), muse_get(), muse_list_length(), muse_mark(), MUSE_NIL, muse_pop_recent_scope(), muse_pread(), muse_push_recent_scope(), muse_put(), muse_pwrite(), muse_raise_error(), MUSE_SYMBOL_CELL, port_eof(), port_putc(), port_write(), and syntax_do().
Referenced by fn_symbol_whose_value_is(), fn_system(), and module_find_symbol_with_value().
muse_cell module_syntax (muse_env * env, module_t * m, muse_cell args)
 (MyMod ...body...)
Behaves exactly like do under all circumstances, except that the symbols in the body part are interpreted in the context of the module.
When you use such an expression within a closure creating expression, the head is replaced with "do" since the body is already automatically bind-copied in the context of the module and there is no longer any necessity for the module object sitting at the head. So this function is called only when the module object is used outside of a closure capturing expression - i.e. either at the top level or inside any immediately evaluated expression at the top level.
References muse_apply().
muse_cell fn_require (muse_env * env, void * context, muse_cell args)
(require ModuleSymbol ...)
Will first search the current directory for file named "ModuleSymbol.scm" and load that if found. The module is not "import"ed. If such a file doesn't exist, it will fetch and load "http://muvee-symbolic-expressions.googlecode.com/svn/trunk/lib/ModuleSymbol.scm"
Can raise fetch-uri and load related exceptions.
Exceptions
error:invalid-module-reference Handler format:
 (fn ('error:invalid-module-reference given-ref) ...)
Raised when the module (if not loaded yet) could neither be resolved as a local file nor as a file on the library site.
References fn_import(), muse_generate_list(), and MUSE_NIL.
Referenced by fn_import(), and fn_module().
muse_cell fn_import (muse_env * env, void * context, muse_cell args)
 (import ModA ModB ...)
Introduces symbols in all the named modules into the current context, in their short forms. Useful in two places -
Inside a module definition to make the short form of symbols from aother module available for the scope of the module being defined.
To globally introduce short form names of the symbols in the given modules, when used at the REPL or file level.
References fn_require(), muse_eval(), muse_eval_list(), muse_list(), MUSE_NIL, muse_raise_error(), and MUSE_SYMBOL_CELL.
Referenced by fn_require().