muSE: Generic functions
Generic functions
A generic function is one whose definition can be augmented even after it is first created.
Functions
muse_cell fn_define_extension (muse_env *env, void *context, muse_cell args)
muse_cell fn_define_override (muse_env *env, void *context, muse_cell args)
muse_cell syntax_local (muse_env *env, void *context, muse_cell args)
muse_cell syntax_generic_lambda (muse_env *env, void *context, muse_cell args)
(gfn formal-args body)
muse_cell syntax_generic_block (muse_env *env, void *context, muse_cell args)
(gfn: formal-args body)
Detailed Description
A generic function is one whose definition can be augmented even after it is first created.
Every function presents a "case" to the evaluator - its supplied argument may or may not match the declared argument pattern of the function. The generic function mechanism allows you to define a function in terms of a number of such cases that are incrementally specified - potentially in different source files.
For example, the humble factorial can be defined in two phases -
(define fact (gfn (1) 1))
(define fact (fn (n) (* n (fact (- n 1)))))
The second function's definition is added to the existing generic function so that you can do the following -
> (fact 3)
6
> (fact 5)
120
You can use define-extension or define-override to augment a generic function. When supplied with a generic function, define itself behaves like define-extension which is the most common use case for generic functions.
It is important to note that if a partially specified generic function is captured in a closure and then augmented with a new case, the new case will influence the closure.
Since macros are just functions, you can create "generic macros" the same way you create generic functions. The constraint here is that a function used to extend a generic macro must itself be a macro.
There is some overhead to using generic functions versus normal functions - the overhead of dispatching a given set of arguments to the appropriate case.
Function Documentation
muse_cell fn_define_extension (muse_env * env, void * context, muse_cell args)
(define-extension generic-fn-symbol fn-extension)
Obeys the same syntax as define, except that the symbol for extension is expected to be bound to a generic function. Only generic functions can be extended.
"Extension" means that the case presented by the given function is examined after all the preceding cases. So if the extension function has the same argument pattern as any of the preceding cases, will not have any effect on the behaviour of the generic function.
You can also use define instead of define-extension.
See Also
gfn, gfn:, define-override
References fn_define().
muse_cell fn_define_override (muse_env * env, void * context, muse_cell args)
(define-override generic-fn-symbol fn-override)
Obeys the same syntax as define, except that the symbol for extension is expected to be bound to a generic function. Only generic functions can be overridden.
"Override" means that the case presented by the given function is examined before all the preceding cases of the generic function. This means that if an overriding function has the same argument pattern as any preceding case, it'll completely take over and not give the preceding case a chance.
See Also
gfn, gfn:, define-extension
References fn_define().
muse_cell syntax_local (muse_env * env, void * context, muse_cell args)
(local symbol1 symbol2 ...)
The local declaration is used to introduce symbols that are, well, local to a particular context. What it says is that "from this point onwards and till the end of the surrounding scope, you have to discard any previous definitions of these symbols". This is useful mostly in module definitions to prevent the definitions of some symbols from influencing the definition of the module. For example -
; A function to determine if the sequence [a,b,c] progresses evenly.
(define (even? a b c) (= (- b a) (- c b)))
(module Num (classify)
  (local even? odd?)  ; Ignore previous definitions/declarations of even? and odd?.
                      ; Without this, the following declaration will give a
                      ; redeclaration error.
  (define (even? n))  ; Forward declare even? so that odd? can use it.
  (define (odd? n) (case n (0 ()) (_ (even? (- n 1)))))
  (define (even? n) (case n (0 T) (_ (odd? (- n 1))))))
  (define (classify n) (cond ((even? n) 'even) ((odd? n) 'odd)))
)
; At this point, the original 3-argument definition of even? is available.
References muse_message(), MUSE_NIL, and MUSE_SYMBOL_CELL.
muse_cell syntax_generic_lambda (muse_env * env, void * context, muse_cell args)
(gfn formal-args body)
gfn creates a generic function that can be extended or overridden using define-extension and define-override. You can define generic functions as well as macros.
See Also
gfn:
References syntax_lambda().
Referenced by muse_bind_copy_expr().
muse_cell syntax_generic_block (muse_env * env, void * context, muse_cell args)
(gfn: formal-args body)
gfn: creates a generic function that can be extended or overridden using define-extension and define-override. This version is similar to gfn, but uses dynamic scoping in its body.
See Also
gfn
References syntax_block().
Referenced by muse_bind_copy_expr().