muSE: Embedding API for the Muse language.
Embedding API for the Muse language.
The muSE embedding API is a C wrapper around the core muSE runtime with additional support functions.
Data Structures
struct muse_functional_object_type_t
Type information for a functional object.
struct muse_functional_object_t
Any muSE functional object must always begin with this structure.
Typedefs
typedef struct _muse_env muse_env
Identifies a particular muse instance.
typedef wchar_t muse_char
Unicode character type used throughout muse.
typedef longlong_t muse_int
64-bit signed integer type.
typedef double muse_float
64-bit double precision floating point type.
typedef long int muse_cell
A cell is referred using a single 32-bit signed integer.
typedef muse_cell(* muse_nativefn_t)(muse_env *env, void *context, muse_cell args)
You can include native C-function calls within Muse procedure execution.
Enumerations
enum muse_cell_t {
MUSE_CONS_CELL,
MUSE_LAMBDA_CELL,
MUSE_SYMBOL_CELL,
MUSE_NATIVEFN_CELL,
MUSE_INT_CELL,
MUSE_FLOAT_CELL,
MUSE_TEXT_CELL,
MUSE_LAZY_CELL
}
Type codes for the various cell types.
enum muse_builtin_symbol_t {
MUSE_NIL,
MUSE_T,
MUSE_QUOTE,
MUSE_CLASS,
MUSE_SELF,
MUSE_SUPER,
MUSE_DOC,
MUSE_CODE,
MUSE_SIGNATURE,
MUSE_USAGE,
MUSE_BRIEF,
MUSE_DESCR,
MUSE_TIMEOUT,
MUSE_DEFINE,
MUSE_TRAP_POINT,
MUSE_DEFAULT_EXCEPTION_HANDLER,
MUSE_CLOSURE,
MUSE_NAME,
MUSE_IT,
MUSE_THE,
MUSE_TIMEOUTVAR,
MUSE_XMLSPLICE,
MUSE_GENERIC_INVOKE,
MUSE_GET,
MUSE_PUT,
MUSE_NUM_BUILTIN_SYMBOLS
}
Some builtin-symbols are provided for general use.
Managing the muse environment.
enum muse_env_parameter_name_t {
MUSE_END_OF_LIST,
MUSE_HEAP_SIZE,
MUSE_GROW_HEAP_THRESHOLD,
MUSE_STACK_SIZE,
MUSE_MAX_SYMBOLS,
MUSE_DISCARD_DOC,
MUSE_PRETTY_PRINT,
MUSE_TAB_SIZE,
MUSE_DEFAULT_ATTENTION,
MUSE_ENABLE_OBJC,
MUSE_OWN_OBJC_AUTORELEASE_POOL,
MUSE_ENABLE_TRACE,
MUSE_NUM_PARAMETER_NAMES
}
When creating a new muse environment, you can configure it using a set of parameters.
MUSEAPI muse_env * muse_init_env (const int *parameters)
Creates a new muse environment.
MUSEAPI void muse_destroy_env (muse_env *env)
Destroys the given environment.
Basic memory management
typedef void(* muse_slot_cleanup_proc_t)(muse_env *env, muse_int *slot)
MUSEAPI muse_cell muse_cons (muse_env *env, muse_cell head, muse_cell tail)
Allocates a new cons cell with the given head and tail cells.
MUSEAPI muse_cell muse_mk_int (muse_env *env, muse_int i)
Allocates a new integer cell to hold the given integer.
MUSEAPI muse_cell muse_mk_float (muse_env *env, muse_float f)
Allocates a new float cell to hold the given integer.
MUSEAPI muse_cell muse_mk_text (muse_env *env, const muse_char *start, const muse_char *end)
Copies the given text and creates a new text cell to store it.
MUSEAPI muse_cell muse_mk_text_utf8 (muse_env *env, const char *start, const char *end)
Same as muse_mk_text() except that it takes a UTF8 string and converts it into a unicode string and stores it.
MUSEAPI muse_cell muse_mk_ctext (muse_env *env, const muse_char *start)
Same as muse_mk_text() except that it assumes a null terminated string.
MUSEAPI muse_cell muse_mk_ctext_utf8 (muse_env *env, const char *start)
Same as muse_mk_text_utf8() except that it assumes a null terminated string as input.
MUSEAPI muse_cell muse_mk_nativefn (muse_env *env, muse_nativefn_t fn, void *context)
Creates a new cell that stores a C function.
MUSEAPI muse_cell muse_mk_destructor (muse_env *env, muse_nativefn_t fn, void *context)
A destructor is a native function that also gets called with no arguments when the function is garbage collected.
MUSEAPI muse_cell muse_mk_anon_symbol (muse_env *env)
An anonymous symbol is similar to a named symbol, except that it is not stored permanently on the symbol stack.
MUSEAPI muse_cell muse_list (muse_env *env, const char *format,...)
Returns a list of the given items.
MUSEAPI muse_cell muse_symbol (muse_env *env, const muse_char *start, const muse_char *end)
Returns a reference to a named symbol with the given name.
MUSEAPI muse_cell muse_csymbol (muse_env *env, const muse_char *sym)
Same as muse_symbol(), but takes a c-style null terminated unicode character string.
MUSEAPI muse_cell muse_symbol_utf8 (muse_env *env, const char *start, const char *end)
Same as muse_symbol() except that it takes a UTF8 string.
MUSEAPI muse_cell muse_csymbol_utf8 (muse_env *env, const char *sym)
Same as muse_symbol_utf8() except that it takes a c-style null terminated utf8 string.
MUSEAPI muse_cell muse_builtin_symbol (muse_env *env, muse_builtin_symbol_t s)
Returns a symbol reference corresponding to the given symbol index.
MUSEAPI int muse_stack_pos (muse_env *env)
Returns the current stack position.
MUSEAPI void muse_stack_unwind (muse_env *env, int stack_pos)
Unwinds the stack to the given position.
MUSEAPI muse_cell muse_stack_push (muse_env *env, muse_cell obj)
Saves the given object on the stack so that it will not be garbage collected when gc is next invoked.
MUSEAPI void muse_trace_push (muse_env *env, const muse_char *label, muse_cell fn, muse_cell arglist)
A mechanism for gathering call trace information.
MUSEAPI void muse_trace_pop (muse_env *env)
MUSEAPI size_t muse_trace_report (muse_env *env, size_t numchars, muse_char *buffer)
Generates a report of the stuff on the trace stack at the point of call.
MUSEAPI void muse_gc (muse_env *env, int free_cells_needed)
Collects all the garbage cells - i.e.
MUSEAPI void muse_mark (muse_env *env, muse_cell cell)
Prior to garbage collection, muse_mark is called on all cells which are referenced somewhere and should not be garbage collected.
MUSEAPI muse_boolean muse_doing_gc (muse_env *env)
You can call this to know whether the garbage collection is in progress.
MUSEAPI muse_int * muse_slot (muse_env *env, int slotid)
The environment maintains a fixed number of "slots" which are memory locations of size muse_int that are addressed using a four-character int id.
MUSEAPI void muse_set_slot_cleanup_proc (muse_env *env, int slotid, muse_slot_cleanup_proc_t proc)
Associates a callback function with a slot that will be called when the muSE environment is destroyed.
Cell access
typedef muse_cell(* muse_list_generator_t)(muse_env *env, void *context, int i, muse_boolean *eol)
A function that is called to generate elements which are collected into a list by muse_generate_list().
MUSEAPI muse_cell_t muse_cell_type (muse_cell cell)
Returns the type of the cell data referenced by the given cell reference.
MUSEAPI muse_boolean muse_isfn (muse_cell cell)
Returns MUSE_TRUE if the given cell is a function.
MUSEAPI muse_cell muse_head (muse_env *env, muse_cell cell)
Returns the head of the cons cell referred to by the given cell reference.
MUSEAPI muse_cell muse_tail (muse_env *env, muse_cell cell)
Returns the tail of the cons cell referred to by the given cell reference.
MUSEAPI muse_cell muse_tail_n (muse_env *env, muse_cell cell, int n)
Returns the n-th tail of the given list.
MUSEAPI muse_int muse_int_value (muse_env *env, muse_cell cell)
Given an integer or float cell, it returns the value cast to a 64-bit integer.
MUSEAPI muse_float muse_float_value (muse_env *env, muse_cell cell)
Given an integer or float cell, it returns the value cast to a 64-bit float.
MUSEAPI const muse_char * muse_text_contents (muse_env *env, muse_cell cell, int *length)
Returns a pointer to the characters of the string referenced by the given cell.
MUSEAPI void * muse_nativefn_context (muse_env *env, muse_cell cell, muse_nativefn_t *fn)
Returns the context pointer of a nativefn cell.
MUSEAPI const muse_char * muse_symbol_name (muse_env *env, muse_cell sym)
Returns the string name of the given symbol.
MUSEAPI muse_cell muse_symbol_value (muse_env *env, muse_cell sym)
Returns the top-most value of the symbol that's on the symbol's value stack.
MUSEAPI int muse_list_length (muse_env *env, muse_cell list)
Returns the number of elements in the list.
MUSEAPI muse_cell muse_list_last (muse_env *env, muse_cell list)
Returns the last cell of a list or () if the list is itself ().
MUSEAPI muse_cell muse_list_append (muse_env *env, muse_cell head, muse_cell tail)
Appends the tail list to the end of the head list and returns the head list.
MUSEAPI muse_cell muse_array_to_list (muse_env *env, int count, const muse_cell *array, int astep)
Constructs a new list whose contents are that of the given array in the given order.
MUSEAPI muse_cell * muse_list_to_array (muse_env *env, muse_cell list, int *lengthptr)
Constructs a new array with the contents of the list in the given order.
MUSEAPI void muse_list_extract (muse_env *env, int count, muse_cell list, int lstep, muse_cell *array, int astep)
Extracts count elements from the list starting with the first element, into the given array.
MUSEAPI muse_cell muse_generate_list (muse_env *env, muse_list_generator_t generator, void *context)
Creates a list whose contents are generated by the given generator function.
Cell editing
MUSEAPI muse_cell muse_set_cell (muse_env *env, muse_cell cell, muse_cell head, muse_cell tail)
Sets the given cell's head and tail to the given cell references.
MUSEAPI muse_cell muse_set_head (muse_env *env, muse_cell cell, muse_cell head)
Sets the head of the given cell.
MUSEAPI muse_cell muse_set_tail (muse_env *env, muse_cell cell, muse_cell tail)
Sets the tail of the given cell.
MUSEAPI muse_cell muse_set_int (muse_env *env, muse_cell int_cell, muse_int value)
Sets the integer value of an int cell.
MUSEAPI muse_cell muse_set_float (muse_env *env, muse_cell float_cell, muse_float value)
Sets the float value of a float cell.
MUSEAPI muse_cell muse_set_text (muse_env *env, muse_cell text, const muse_char *start, const muse_char *end)
Copies the given string to the given text cell, modifying the cell's contents.
MUSEAPI muse_cell muse_set_ctext (muse_env *env, muse_cell text, const muse_char *start)
Same as muse_set_text, except that it takes a null terminated c-style string instead.
MUSEAPI muse_cell muse_define (muse_env *env, muse_cell symbol, muse_cell value)
Sets the value of the symbol.
MUSEAPI muse_cell muse_pushdef (muse_env *env, muse_cell symbol, muse_cell value)
Makes the given value the current value of the symbol, without losing the previously assigned set of values.
MUSEAPI muse_cell muse_popdef (muse_env *env, muse_cell symbol)
Removes the current value on the symbol's value stack and returns it.
MUSEAPI int muse_bindings_stack_pos (muse_env *env)
Gets the current depth of the bindings stack.
MUSEAPI void muse_bindings_stack_unwind (muse_env *env, int pos)
MUSEAPI muse_cell muse_dup (muse_env *env, muse_cell obj)
Deep copies the given object.
MUSEAPI muse_cell * muse_find_list_element (muse_env *env, muse_cell *listptr, muse_cell element)
Searches for the given element in the given list and returns a reference to it.
Property lists
MUSEAPI int muse_eq (muse_env *env, muse_cell a, muse_cell b)
Shallow compares two cells.
MUSEAPI int muse_equal (muse_env *env, muse_cell a, muse_cell b)
Deep compares two cells.
MUSEAPI int muse_compare (muse_env *env, muse_cell a, muse_cell b)
Deep compares two cells for ordering.
MUSEAPI muse_cell muse_symbol_plist (muse_env *env, muse_cell sym)
Returns the property list of the given symbol.
MUSEAPI muse_cell muse_assoc (muse_env *env, muse_cell alist, muse_cell prop)
Looks up a particular association by key in an association list.
MUSEAPI muse_cell * muse_assoc_iter (muse_env *env, muse_cell *alist, muse_cell prop)
Similar to muse_assoc, except that the return value is not the kvpair, but the list position of the kvpair.
MUSEAPI muse_cell muse_get_prop (muse_env *env, muse_cell sym, muse_cell prop)
Looks up the given property in the given symbol's property list.
MUSEAPI muse_cell muse_get (muse_env *env, muse_cell obj, muse_cell key, muse_cell argv)
Recursive property getter.
MUSEAPI muse_cell muse_put_prop (muse_env *env, muse_cell sym, muse_cell prop, muse_cell value)
Sets or adds the given property-value association to the symbol's property list.
MUSEAPI muse_cell muse_put (muse_env *env, muse_cell obj, muse_cell prop, muse_cell argv)
Deeply nested value setting support.
MUSEAPI muse_cell muse_put_many (muse_env *env, muse_cell obj, muse_cell argv)
MUSEAPI muse_cell muse_get_meta (muse_env *env, muse_cell fn)
I/O
MUSEAPI muse_cell muse_load (muse_env *env, FILE *f)
Reads all symbolic expressions in the stream and evaluates them one by one, until end of stream.
Evaluation
MUSEAPI muse_cell muse_eval (muse_env *env, muse_cell sexpr, muse_boolean lazy)
Evaluates the given symbolic expression.
MUSEAPI muse_cell muse_evalnext (muse_env *env, muse_cell *sexpr)
Evaluates the head of the list referred to by the given sexpr pointer and steps the pointer to the tail of the list, getting ready for the next call.
MUSEAPI muse_cell muse_eval_list (muse_env *env, muse_cell list)
Evaluates each element of the given list, builds a new list out of the results of the evaluations and returns the list.
MUSEAPI muse_cell muse_apply (muse_env *env, muse_cell fn, muse_cell args, muse_boolean args_already_evaluated, muse_boolean lazy)
Applies the given native function or lambda to the given list of arguments and returns the result.
MUSEAPI muse_cell muse_do (muse_env *env, muse_cell block)
A block of code is a list of expressions to evaluate in sequence.
MUSEAPI muse_cell muse_quote (muse_env *env, muse_cell args)
Returns the given arguments quoted.
MUSEAPI muse_boolean muse_bind_formals (muse_env *env, muse_cell formals, muse_cell values)
Binds the symbols in the given formals list to the corresponding values in the args list.
MUSEAPI muse_cell muse_callcc (muse_env *env, muse_cell proc)
MUSEAPI muse_cell muse_force (muse_env *env, muse_cell cell)
Forces evaluation of a lazy cell.
MUSEAPI muse_cell muse_raise_error (muse_env *env, muse_cell error, muse_cell info)
Raises an error which can be resumed just like an exception raised using the raise operator.
MUSEAPI muse_cell muse_bind_copy_expr (muse_env *env, muse_cell body, muse_boolean list_start)
A key function for implementing portions of closure creation.
MUSEAPI muse_cell muse_try (muse_env *env, muse_cell handlers, muse_nativefn_t fn, void *context, muse_cell arg)
Calls the given function fn within the context of a try block, protected by the given handlers list (which can be nil).
MUSEAPI muse_cell muse_apply_top_level (muse_env *env, muse_cell fn, muse_cell args)
Wraps an apply in a try block with the default top-level handler.
MUSEAPI void muse_add_finalizer (muse_env *env, muse_cell finalizer)
Adds a call to the given function to be triggered upon exiting the current try block.
MUSEAPI void muse_add_finalizer_call (muse_env *env, muse_nativefn_t fn, void *context)
A special variant of muse_add_finalizer to call the given native fn.
Misc
MUSEAPI muse_int muse_hash (muse_env *env, muse_cell obj)
Hashes a given cell reference.
MUSEAPI muse_int muse_hash_text (const muse_char *start, const muse_char *end, muse_int initial)
A hash similar to muse_hash_data, but tailored for text.
MUSEAPI muse_int muse_hash_data (const unsigned char *start, const unsigned char *end, muse_int initial)
Creates a simple hash of the given data.
MUSEAPI void * muse_tick ()
Used for performance timing.
MUSEAPI muse_int muse_elapsed_us (void *timer)
Returns the time elapsed since the start of the given timer.
MUSEAPI muse_int muse_tock (void *timer)
When passed the timing handle returned by muse_tick(), it returns the time elapsed between the muse_tick() call and this muse_tock() call in microseconds.
MUSEAPI void muse_sleep (muse_int time_us)
Sleeps the muse process for the given time in microseconds.
MUSEAPI FILE * muse_fopen (const muse_char *filename, const muse_char *options)
A wrapper to the common fopen function so that we can call _wfopen if available, or the narrow version if the wide version isn't available.
MUSEAPI int muse_fsize (FILE *f)
Computes the size of the given file using fseek.
Diagnostics
MUSEAPI const muse_char * muse_typename (muse_cell thing)
Returns a non-mutable string describing the type of the thing passed as the parameter.
MUSEAPI size_t muse_sprintf (muse_env *env, muse_char *buffer, size_t maxlen, const muse_char *format,...)
Formats a string consisting of the given format string with the other argument objects inserted at specified positions.
MUSEAPI void muse_message (muse_env *env, const muse_char *context, const muse_char *format,...)
Displays a message string formatted according to the given message string with format codes.
MUSEAPI muse_boolean muse_expect (muse_env *env, const muse_char *context, const muse_char *spec,...)
Checks whether a set of expectations are satisfied by some values.
MUSEAPI muse_cell muse_similar_symbol (muse_env *env, muse_cell symbol, int *outDistance, muse_nativefn_t predicate, void *context)
Sometimes, it is useful to know whether another symbol that's very similar in textual representation from a known symbol.
MUSEAPI muse_cell muse_symbol_with_value (muse_env *env, muse_cell value)
Searches the symbol table to find a symbol whose current value is the given cell.
MUSEAPI muse_cell muse_symbol_is_defined (muse_env *env, void *context, muse_cell symbol)
Returns T if the given symbol is defined and () if it isn't.
Multilingual stuff
MUSEAPI size_t muse_unicode_to_utf8 (char *out, size_t out_maxlen, const muse_char *win, size_t win_len)
Converts the given double-byte unicode string to multibyte UTF8 string.
MUSEAPI size_t muse_utf8_to_unicode (muse_char *wout, size_t wout_maxlen, const char *in, size_t in_len)
Converts the given UTF8 string to double-byte unicode string.
MUSEAPI size_t muse_utf8_size (const muse_char *wstr, size_t length)
Returns an estimate of the number of bytes (conservative upper bound) that might be needed to represent the given number of unicode characters using UTF8 encoding.
MUSEAPI size_t muse_unicode_size (const char *utf8, size_t nbytes)
Returns an estimate (conservative upper bound) of the number of bytes that will be required to store the converted unicode version of the given utf8 string.
Attached code
muSE code can be attached to the ends of some kinds of binary files such as executables, JPEG and PNG files.
These functions are to handle such files.
MUSEAPI int muSEexec_check (FILE *e, int *source_pos, int *source_size, int *footer_size)
A muSE executable is a binary file to the end of which souce code is appended.
MUSEAPI int muSEexec_finish (FILE *e, int source_size)
Seeks to the end of the file and writes out the footer containing the number of bytes of source appended to the end of the given file.
Dynamically loading plugins
typedef muse_cell(* muse_plugin_entry_t)(void *module, muse_env *env, muse_cell arglist)
A muSE plugin is expected to export only one function - the entry point - of this type.
MUSEAPI muse_cell muse_link_plugin (muse_env *env, const muse_char *path, muse_cell arglist)
Loads a muse plugin DLL and calls its entry point function which is to have the name "muse_plugin_entry" and be of the type muse_plugin_entry_t.
REPL - Read Eval Print Loop
MUSEAPI void muse_repl (muse_env *env)
The muSE REPL - Read-Eval-Print-Loop.
Extending muSE with functional objects
MUSEAPI muse_functional_object_t * muse_create_and_init_object (muse_env *env, muse_functional_object_type_t *type_info, muse_cell init_args)
Just creates an object without allocating a cell for it.
MUSEAPI void muse_destroy_object (muse_env *env, muse_functional_object_t *obj)
Counterpart of muse_create_and_init_object.
MUSEAPI muse_cell muse_mk_functional_object (muse_env *env, muse_functional_object_type_t *type_info, muse_cell init_args)
Creates a new functional object instance based on the given type information.
MUSEAPI muse_functional_object_t * muse_functional_object_data (muse_env *env, muse_cell fobj, int type_word)
Returns the data pointer of the functional object, or NULL if the object is not a functional object.
Ports API
A port is an I/O abstraction that you can use to work with objects like files and network connections.
Anything that satisfies a simple protocol can be used as a port. All standard muSE functions such as muse_pwrite and muse_pread will work with any port that satisfies such the protocol.
See Also
Ports
enum muse_stdport_t
enum muse_port_mode_bits_t {
MUSE_PORT_READ = 1,
MUSE_PORT_WRITE = 2,
MUSE_PORT_READ_WRITE = MUSE_PORT_READ | MUSE_PORT_WRITE,
MUSE_PORT_EZSCHEME = 4,
MUSE_PORT_READ_EXPAND_BRACES = 0x10,
MUSE_PORT_READ_DETECT_MACROS = 0x20,
MUSE_PORT_TRUSTED_INPUT = MUSE_PORT_READ | MUSE_PORT_READ_EXPAND_BRACES | MUSE_PORT_READ_DETECT_MACROS
}
These bits are used to identify various port features, whether it is for reading, writing, etc.
typedef struct _muse_port_base_t * muse_port_t
MUSEAPI muse_port_t muse_port (muse_env *env, muse_cell p)
Takes a muSE port represented as a cell and returns the internal port object that it uses.
MUSEAPI muse_port_t muse_stdport (muse_env *env, muse_stdport_t descriptor)
MUSEAPI muse_port_t muse_assign_port (muse_env *env, FILE *f, int mode)
Creates a port definition that you can use to read/write stuff from a given file pointer.
MUSEAPI void muse_unassign_port (muse_port_t p)
Unassigns a file port which was earlier assigned using muse_assign_port.
MUSEAPI muse_cell muse_pread (muse_port_t port)
Reads the next symbolic expression at the current stream position, ignoring white space and comment lines.
MUSEAPI void muse_pwrite (muse_port_t port, muse_cell sexpr)
Writes the given s-expression to the given stream.
MUSEAPI void muse_pprint (muse_port_t port, muse_cell sexpr)
MUSEAPI void muse_mickey (muse_port_t in, muse_port_t out)
Processes mickey streams from input port to output port.
MUSEAPI muse_port_t muse_create_memport (muse_env *env)
MUSEAPI muse_cell muse_read_xml_node (muse_port_t in)
MUSEAPI muse_port_t muse_current_port (muse_env *env, muse_stdport_t which, muse_port_t port)
If port is NULL, retrieves the current input port for the current process.
MUSEAPI muse_cell muse_pload (muse_port_t port)
Similar to muse_load but works on the given port.
Vectors
MUSEAPI muse_cell muse_mk_vector (muse_env *env, int length)
Creates a new vector object that has enough slots allocated to hold the given number of objects.
MUSEAPI int muse_vector_length (muse_env *env, muse_cell vec)
Returns the number of slots the vector has.
MUSEAPI muse_cell muse_vector_get (muse_env *env, muse_cell vec, int index)
Returns the value occupying the slot at the given 0-based index.
MUSEAPI muse_cell muse_vector_put (muse_env *env, muse_cell vec, int index, muse_cell value)
Replaces the value in the slot at the given index with the new value.
Hashtables
MUSEAPI muse_cell muse_mk_hashtable (muse_env *env, int length)
Creates a hashtable with a bucket count setup according to the given desired length.
MUSEAPI int muse_hashtable_length (muse_env *env, muse_cell ht)
Returns the number of key-value pairs put into the hash table.
MUSEAPI muse_cell muse_hashtable_get (muse_env *env, muse_cell ht, muse_cell key)
Returns the key-value pair with the given key as the head if the key is present in the hash table, otherwise it returns MUSE_NIL.
MUSEAPI muse_cell muse_hashtable_put (muse_env *env, muse_cell ht, muse_cell key, muse_cell value)
Associates the given value with the given key in the hash table.
Boxes
MUSEAPI muse_cell muse_mk_box (muse_env *env, muse_cell contents)
Creates a new box with the given contents.
MUSEAPI muse_cell muse_box_get (muse_env *env, muse_cell box)
Returns the contents of the given box.
MUSEAPI muse_cell muse_box_set (muse_env *env, muse_cell box, muse_cell contents)
Changes the contents of the given box to the new value.
ByteArrays
MUSEAPI muse_cell muse_mk_bytes (muse_env *env, size_t s)
MUSEAPI void * muse_bytes_data (muse_env *env, muse_cell b, size_t offset)
MUSEAPI size_t muse_bytes_size (muse_env *env, muse_cell b)
Detailed Description
The muSE embedding API is a C wrapper around the core muSE runtime with additional support functions.
muSE - which stands for "muvee Symbolic Expressions" - is an environment for manipulating list-based data structures. It consists of functions to create and parse such data structures as well as functions to read and write them from/to files.
The muSE environment
The muSE environment holds all the data constructed using the muSE API calls and keeps track of object references. There is a single global muse environment muse_env* active at any given time. One creates this global muse environment using muse_init_env and destroys it using muse_destroy_env.
The basic data types in muSE
64-bit integers - see MUSE_INT_CELL, muse_mk_int
64-bit floats - see MUSE_FLOAT_CELL, muse_mk_float
and unicode strings - see MUSE_TEXT_CELL, muse_mk_text and family
symbols - see MUSE_SYMBOL_CELL, muse_symbol and family
The cons cell
The object that glues the above fundamental types into complex structures is the "cons cell", aka a "pair" (MUSE_CONS_CELL, _cons). A cons (short for "constructor") cell is a pair of cells which are referred to as the head and tail of the cons cell. A cons cell may have another cons cell as its head or tail.
If one uses the notation
(cons h t)
to denote a cons cell whose head is h and tail is t, then we can encode a list of items
(h1 h2 h3 ... hN)
using cons cells like this -
(cons h1 (cons h2 (cons h3 ... (cons hN ()) ...)))
where () is another name for the empty list and is used to mark the end of a list.
Symbols
Symbols are objects that are uniquely identified by giving their names (see muse_symbol, muse_csymbol, and family). A symbol may have a value (see muse_symbol_value and muse_define) and a list of properties (see muse_symbol_plist, muse_get_prop and muse_put_prop).
The property list of a symbol is in the form of what's called an "association list" - a list of property-value pairs. Each property-value pair is stored in a cons cell with the property in the head and the value in the tail. (see muse_assoc)
It is also possible to have anonymous symbols which differ from named symbols in only one aspect - they have no name and are not preserved eternally. Anonymous symbols form the foundation of muSE's simple, yet powerful object system.
S-Expressions
Compound structures built out of cons cells, and values such as ints, floats, symbols, strings, are called s-expressions - short for "symbolic expressions". This term includes functions as well.
Reading and writing s-expressions
The functions muse_pread and muse_pwrite read and write complete s-expressions from a given IO stream. You can use this feature to load and save data to files, or to build a simple interpreter using a read-eval-print-loop (REPL for short). For a brief description of the syntax of the data structure representation, see mainpage.
Typedef Documentation
typedef struct _muse_env muse_env
Identifies a particular muse instance.
typedef wchar_t muse_char
Unicode character type used throughout muse.
typedef longlong_t muse_int
64-bit signed integer type.
typedef double muse_float
64-bit double precision floating point type.
typedef long int muse_cell
A cell is referred using a single 32-bit signed integer.
typedef muse_cell(* muse_nativefn_t)(muse_env *env, void *context, muse_cell args)
You can include native C-function calls within Muse procedure execution.
This is how built-in functionality is provided. A Muse nativefn can be passed a single pointer to arbitrary data that is not managed by the muse environment. This is called its "context" and serves to supply any data and state the function may need to maintain. For example, context can be the pointer to a C++ object instance and the nativefn can in turn call some specific method of that object.
Parameters
env The muse environment that's calling the native function.
context The function's closure argument.
args A list of arguments that was passed to the function when it was called within the muse environment.
typedef muse_cell(* muse_list_generator_t)(muse_env *env, void *context, int i, muse_boolean *eol)
A function that is called to generate elements which are collected into a list by muse_generate_list().
Parameters
context Arbitrary data that is passed by muse_generate_list to the generator function, without being touched.
i An integer indicating the zero-based index of the list element that the generator function is being asked to generate.
eol If the generator function wants to end the list at the given index i, then it can simply set (*eol) to MUSE_TRUE and return. If (*eol) is found to be MUSE_FALSE, then the element returned by the generator function is appended to the list.
typedef muse_cell(* muse_plugin_entry_t)(void *module, muse_env *env, muse_cell arglist)
A muSE plugin is expected to export only one function - the entry point - of this type.
When linking the plugin using muse_link_plugin, this entry point function is invoked and the result returned by this function is returned by muse_link_plugin.
Parameters
module The system specific handle of the loaded dynamically linked module. In Windows, this is the HMODULE returned by the LoadLibrary call. In Unix, its the handle returned by dlopen.
env The muse environment which is linking the plugin. The plugin entry function is expected to set its current environment to this environment pointer before calling any muSE API functions.
arglist An arbitrary list of arguments for use by the plugin entry point function.
Returns
Any s-expression. This return value will be returned by muse_link_plugin.
Enumeration Type Documentation
enum muse_cell_t
Type codes for the various cell types.
Enumerator
MUSE_CONS_CELL
A CONS cell contains a pair of cells - the "head" and "tail".
MUSE_LAMBDA_CELL
A LAMBDA cell contains a definition of a function.
MUSE_SYMBOL_CELL
Holds a SYMBOL that may have been given a value or have properties.
MUSE_NATIVEFN_CELL
A NATIVEFN holds the address of C-function to execute with an arbitrary argument.
MUSE_INT_CELL
Holds a single 64-bit signed integer.
MUSE_FLOAT_CELL
Holds a single 64-bit floating point number - i.e.
a "double".
MUSE_TEXT_CELL
Holds an immutable copy of a wide character string - as ptrs to beginning and end.
MUSE_LAZY_CELL
A cell whose head is a function and whose tail is its argument list.
enum muse_builtin_symbol_t
Some builtin-symbols are provided for general use.
See Also
muse_builtin_symbol()
Enumerator
MUSE_NIL
()
MUSE_T
T.
MUSE_QUOTE
quote
MUSE_CLASS
class
MUSE_SELF
self
MUSE_SUPER
super
MUSE_DOC
doc
MUSE_CODE
code
MUSE_SIGNATURE
signature
MUSE_USAGE
usage
MUSE_BRIEF
brief
MUSE_DESCR
descr
MUSE_TIMEOUT
timeout
MUSE_DEFINE
define
MUSE_TRAP_POINT
[internal]
MUSE_DEFAULT_EXCEPTION_HANDLER
[internal]
MUSE_CLOSURE
closure
MUSE_NAME
name
MUSE_IT
it
MUSE_THE
the
MUSE_TIMEOUTVAR
[internal]
MUSE_XMLSPLICE
++
MUSE_GENERIC_INVOKE
invoke
MUSE_GET
get
MUSE_PUT
put
MUSE_NUM_BUILTIN_SYMBOLS
Not a symbol.
enum muse_env_parameter_name_t
When creating a new muse environment, you can configure it using a set of parameters.
Parameters are passed as an array of 32-bit integers where indices 0, 2, 4, etc. hold parameter names and indices 1, 3, 5, etc. hold parameter values. This enumeration defines the set of configurable parameters.
Enumerator
MUSE_END_OF_LIST
Used to signal the end of the parameter list.
No value needed.
MUSE_HEAP_SIZE
Integer parameter giving required heap size.
MUSE_GROW_HEAP_THRESHOLD
Percentage of heap size usage above which to grow the heap.
Default = 80.
MUSE_STACK_SIZE
Integer parameter giving required stack size.
MUSE_MAX_SYMBOLS
Integer parameter giving max symbols used.
MUSE_DISCARD_DOC
Boolean parameter indicating that documentation should not be kept.
Default = MUSE_FALSE.
MUSE_PRETTY_PRINT
Boolean parameter indicating whether write and print should indent their output.
Default = MUSE_TRUE
MUSE_TAB_SIZE
Defaults to 4.
Controls pretty printed output.
MUSE_DEFAULT_ATTENTION
The default attention with which a process is spawned.
Defaults to 1.
MUSE_ENABLE_OBJC
Sets up objective C support in muSE using [] expressions.
Also allocates its own auto-release pool. Default is MUSE_FALSE.
MUSE_OWN_OBJC_AUTORELEASE_POOL
Creates a keeps a reference to an independent auto-release pool, which is released when the muSE environment is destroyed.
Default is MUSE_TRUE.
MUSE_ENABLE_TRACE
Default = MUSE_TRUE.
Enables the collection of stack traces during execution for error detection.
MUSE_NUM_PARAMETER_NAMES
Not a parameter.
enum muse_port_mode_bits_t
These bits are used to identify various port features, whether it is for reading, writing, etc.
Enumerator
MUSE_PORT_READ
Indicates that the port is to be used for input.
MUSE_PORT_WRITE
Indicates that the port is to be used for output.
MUSE_PORT_READ_WRITE
Convenient definition for bi-directional ports.
MUSE_PORT_EZSCHEME
Says that the input from the given port is uses the EZSCHEME syntax.
MUSE_PORT_READ_EXPAND_BRACES
Allows muse_pread() function to expand s-expressions that use braces instead of parentheses.
This is enabled by default for standard input and for files from which code is loaded using muse_load().
MUSE_PORT_READ_DETECT_MACROS
Allows muse_pread() function to detect and expand macro expressions.
Macro expressions are those parentheses delimited list expressions with a macro symbol as the first list element. A macro symbol is a symbol that is defined to a macro function at the point at which the macro expression is encountered.
Macro expression detection is always disabled when reading quoted expressions, though brace expansion may be active.
MUSE_PORT_TRUSTED_INPUT
Convenience definition indicating that input from the given port can be trusted, therefore enabling macro expansion.
Standard input and file ports using by muse_load() are considered to be trusted input sources.
Function Documentation
MUSEAPI muse_env* muse_init_env (const int * parameters)
Creates a new muse environment.
Parameters
parameters is an int array of param-value pairs. The last entry should be MUSE_END_OF_LIST which need not be given a value.
See Also
muse_env_parameter_name_t
References muse_stack::bottom, create_process(), init_process_mailbox(), MUSE_DEFAULT_ATTENTION, MUSE_ENABLE_OBJC, MUSE_HEAP_SIZE, MUSE_MAX_SYMBOLS, MUSE_NIL, MUSE_NUM_BUILTIN_SYMBOLS, muse_tick(), prime_process(), muse_stack::size, and muse_stack::top.
MUSEAPI void muse_destroy_env (muse_env * env)
Destroys the given environment.
If the given environment is the current environment, then the current environment is set to NULL and no muse calls can subsequently be made.
References free_process(), muse_gc(), and muse_tock().
MUSEAPI muse_cell muse_cons (muse_env * env, muse_cell head, muse_cell tail)
Allocates a new cons cell with the given head and tail cells.
This is the primary constructor in the whole of muse out of which all muse objects are built. A new cell for the cons operation is taken from the heap's free list. If no cell is available the garbage collector is invoked to collect the unreferenced cells into the free list. If absolutely no cells are available, then the heap is grown in order to get a free cell to allocate to the cons. The newly allocated cell is placed on the stack so that it won't be inadvertently garbage collected. This way, you can safely write expressions of the form
_cons(_cons(a,b), _cons(c,d))
The cons operation does not fail unless there is absolutely no system memory available for the new cell.
References muse_heap::free_cells, muse_gc(), MUSE_NIL, and muse_heap::size_cells.
MUSEAPI muse_cell muse_mk_int (muse_env * env, muse_int i)
Allocates a new integer cell to hold the given integer.
The newly allocated cell is placed on the stack.
References MUSE_INT_CELL.
Referenced by fn_system(), and fn_windows_registry_entry().
MUSEAPI muse_cell muse_mk_float (muse_env * env, muse_float f)
Allocates a new float cell to hold the given integer.
The newly allocated cell is placed on the stack.
References MUSE_FLOAT_CELL.
MUSEAPI muse_cell muse_mk_text (muse_env * env, const muse_char * start, const muse_char * end)
Copies the given text and creates a new text cell to store it.
The newly allocated cell is placed on the stack. If you pass NULL for start, then this creates a new text cell of the needed length (= end-start), but stores null characters in it. You can subsequently change the contents of the text cell.
References MUSE_TEXT_CELL.
Referenced by buffer_substring(), buffer_to_string(), fn_format(), fn_string_with_char_codes(), fn_substring(), fn_temp_folder(), fn_to_lower(), fn_to_upper(), fn_urldecode(), fn_urlencode(), muse_mk_ctext(), and muse_symbol().
MUSEAPI muse_cell muse_mk_nativefn (muse_env * env, muse_nativefn_t fn, void * context)
Creates a new cell that stores a C function.
The C function can be passed its own context data that is not managed by muSE. The function pointer is given in fn and the context data is given in context. Using the context pointer, it is possible to encode a call to a C++ member function, by writing a static wrapper function.
References MUSE_NATIVEFN_CELL.
Referenced by fn_system(), and fn_with_bytes_as_port().
MUSEAPI muse_cell muse_mk_anon_symbol (muse_env * env)
An anonymous symbol is similar to a named symbol, except that it is not stored permanently on the symbol stack.
It has a property list as well and a value stack, but the symbol name cell is nil. The hash code of an anonymous symbol is the integer value of cell reference itself, so comparing using the hash is the same as comparing the cell reference itself.
Anonymous symbols are used to represent objects in muSE's object system. An object's properties are stored in the plist of an anonymous symbol.
References MUSE_NIL, and MUSE_SYMBOL_CELL.
MUSEAPI muse_cell muse_list (muse_env * env, const char * format, ...)
Returns a list of the given items.
The format string is a string of single character codes indicating the type of argument to convert to a muse object.
Single character codes -
c -> cell
i -> 32-bit integer
I -> 64-bit integer
f -> 64-bit float
T -> unicode text string
t -> utf8 text string
S -> unicode symbol string
s -> utf8 symbol string
Multiple character codes -
=<format-code> -> An '=' character followed by a format code will cause the expression passed in that field to be stored into the list after evaluation.
'<format-code> -> A quote character followed by a format code will place a value according to the format code in quoted form into the list. 2 characters consumed, 1 item generated.
(<format-codes>) -> nestable list of items. All characters from the '(' to the matching ')' are consumed and 1 item is generated. The generator works as though there is an implicit '(' at the beginning of the format list and a matching ')' at the end of the format list.
References muse_generate_list(), and MUSE_NIL.
Referenced by check_timeout(), fn_launch(), fn_stats(), fn_with_incoming_connections_to_port(), and muse_apply_top_level().
MUSEAPI muse_cell muse_symbol (muse_env * env, const muse_char * start, const muse_char * end)
Returns a reference to a named symbol with the given name.
All symbols with the same name have identical symbol references. Therefore you can compare whether two symbols are the same by comparing their cell references.
References _newlocal, muse_intern_symbol(), muse_mk_text(), MUSE_NIL, and MUSE_SYMBOL_CELL.
Referenced by buffer_to_symbol(), fn_symbol(), muse_csymbol(), and muse_symbol_utf8().
MUSEAPI muse_cell muse_builtin_symbol (muse_env * env, muse_builtin_symbol_t s)
Returns a symbol reference corresponding to the given symbol index.
This a convenience function.
See Also
muse_builtin_symbol_t
References MUSE_NUM_BUILTIN_SYMBOLS.
MUSEAPI int muse_stack_pos (muse_env * env)
Returns the current stack position.
You can subsequently unwind to the position by calling muse_stack_unwind(), passing the position as its argument.
A muse enviroment maintains a stack of cell references which will not be garbage collected the next time the gc is invoked. Every API function that uses _cons takes at least one new cell from the free list and places it on the stack. Such functions include _mk_int, _mk_float and family, the muse_list and related functions and so on - anything that will need to allocate a new cell.
Once a reference to a cell is placed into another cell, either by using _define on a named symbol, or by placing it in the property list of a named symbol or by adding it to a list that is itself protected by being on the stack, the stack space occupied by the cell can be released. This is done using muse_stack_unwind.
If a function does not allocate an unreferenced cell, but creates temporary cells, it should reset the stack position before it returns. This is typically done as follows -
void my_func()
{
    int sp = muse_stack_pos();
    / * ... code that allocates new cells ... * /
    muse_stack_unwind(sp);
}
If a function returns as its result a newly constructed compound data structure referenced by a single muse_cell reference, it is advisable for it to place it on the stack, but release all other stack references to the constituent elements. For example -
muse_cell my_make_blooper(int arg)
{
    int sp = muse_stack_pos();
    muse_cell result = MUSE_NIL;
    / * .. compute the data structure and store the reference in "result". * /
    muse_unwind_stack(sp);
    muse_stack_push(result);
    return result;
}
See Also
muse_stack_unwind, muse_stack_push
MUSEAPI void muse_stack_unwind (muse_env * env, int stack_pos)
Unwinds the stack to the given position.
This discards all references to cells that have been kept on the stack. Temporary objects which were placed on the stack that aren't referred to elsewhere will be available for garbage collection.
See Also
muse_stack_pos
MUSEAPI muse_cell muse_stack_push (muse_env * env, muse_cell obj)
Saves the given object on the stack so that it will not be garbage collected when gc is next invoked.
See Also
muse_stack_pos
MUSEAPI void muse_trace_push (muse_env * env, const muse_char * label, muse_cell fn, muse_cell arglist)
A mechanism for gathering call trace information.
"Push" the trace information at the start of your call context pop it at the end.
References _muse_process_frame_t::traceinfo.
Referenced by fn_fetch_uri().
MUSEAPI void muse_trace_pop (muse_env * env)
See Also
muse_trace_push().
References _muse_process_frame_t::traceinfo.
Referenced by fn_fetch_uri().
MUSEAPI void muse_gc (muse_env * env, int free_cells_needed)
Collects all the garbage cells - i.e.
unreferenced cells. Cells referenced on the various stacks including the symbol stack are not collected. _cons() automaticallly invokes this function when it cannot take a cell from the free list.
Parameters
free_cells_needed Tells the garbage collector to ensure that these many free cells are available after collection. If simply collecting unreferenced cells is insufficient, the collector will grow the heap by a sufficient amount. If this parameter is <= 0, it means muse environment is being destroyed and the gc call simply destroys all the specials.
References enter_atomic(), leave_atomic(), muse_tick(), and muse_tock().
Referenced by muse_cons(), and muse_destroy_env().
MUSEAPI void muse_mark (muse_env * env, muse_cell c)
Prior to garbage collection, muse_mark is called on all cells which are referenced somewhere and should not be garbage collected.
The unmarked cells are then swept into the free list.
References muse_functional_object_type_t::mark, muse_mark(), and muse_functional_object_t::type_info.
Referenced by mark_process(), muse_mark(), muse_mark_recent(), and muse_mark_recent_context().
MUSEAPI muse_boolean muse_doing_gc (muse_env * env)
You can call this to know whether the garbage collection is in progress.
This is useful inside destructor functions to decide whether to do destruction or some other operation.
Referenced by fn_pid().
MUSEAPI muse_int* muse_slot (muse_env * env, int slotid)
The environment maintains a fixed number of "slots" which are memory locations of size muse_int that are addressed using a four-character int id.
The int in the location can be used for any purpose and is intended for use by plugins to store and manage sub-system state. The returned pointer to muse_int is valid for the lifetime of the environment and can always be retrieved given the slotid.
References MUSE_NIL, and muse_raise_error().
MUSEAPI void muse_set_slot_cleanup_proc (muse_env * env, int slotid, muse_slot_cleanup_proc_t proc)
Associates a callback function with a slot that will be called when the muSE environment is destroyed.
The callback is expected to perform any cleanup that might be necessary for the slot.
The order in which slots get cleaned up is not guaranteed.
The slot with the given id must already exist.
MUSEAPI muse_boolean muse_isfn (muse_cell cell)
Returns MUSE_TRUE if the given cell is a function.
either native or lambda.
MUSEAPI muse_cell muse_head (muse_env * env, muse_cell cell)
Returns the head of the cons cell referred to by the given cell reference.
Symbols, lambdas are also defined using cons cells, so this applies to those kinds of cells as well.
Applicable to cons cells, symbols, lambdas.
See Also
muse_tail
References MUSE_LAZY_CELL.
Referenced by fn_first(), fn_list_to_vector(), fn_nth(), and muse_bind_formals().
MUSEAPI muse_cell muse_tail (muse_env * env, muse_cell cell)
Returns the tail of the cons cell referred to by the given cell reference.
Applies to symbols and lambdas in addition to cons cells because they are defined in terms of cons cells.
See Also
muse_head
References MUSE_LAZY_CELL.
Referenced by fn_drop(), fn_list_to_vector(), fn_nth(), fn_rest(), fn_reverse_inplace(), muse_bind_formals(), muse_list_length(), and muse_tail_n().
MUSEAPI muse_cell muse_tail_n (muse_env * env, muse_cell cell, int n)
Returns the n-th tail of the given list.
muse_tail_n(env, list, 0)
is equivalent to
list
The n-th element of an N-element list (n = 1, 2, 3, ..., N) can be obtained using
muse_head(env, muse_tail_n(env, list, n-1))
References muse_tail().
MUSEAPI const muse_char* muse_text_contents (muse_env * env, muse_cell cell, int * length)
Returns a pointer to the characters of the string referenced by the given cell.
If the length parameter is non-NULL, the length of the string is stored in that location.
Referenced by buffer_substring(), buffer_to_string(), buffer_to_symbol(), fn_char_code(), fn_file_has_attached_code_p(), fn_http_respond(), fn_launch(), fn_md5_hash(), fn_sha1_hash(), fn_string(), fn_string_to_bytes(), fn_string_with_char_codes(), fn_substring(), fn_system(), fn_temp_file(), fn_to_lower(), fn_to_upper(), fn_urldecode(), fn_urlencode(), and fn_windows_registry_entry().
MUSEAPI const muse_char* muse_symbol_name (muse_env * env, muse_cell sym)
Returns the string name of the given symbol.
Can be used only with a named symbol. Invalid with an anonymous symbolm you'll get NULL.
Referenced by ez_parse(), fn_bytes_fn(), fn_http_respond(), muse_apply(), muse_compare(), and muse_similar_symbol().
MUSEAPI int muse_list_length (muse_env * env, muse_cell list)
Returns the number of elements in the list.
The list must be a proper list - i.e. all tails must be cons cells and the tail of the last cell in the list must be MUSE_NIL.
References muse_tail().
Referenced by fn_string_with_char_codes(), and fn_system().
MUSEAPI muse_cell muse_list_last (muse_env * env, muse_cell list)
Returns the last cell of a list or () if the list is itself ().
For example if you have the list '(1 2 3 4), it'll return the cell which will print as (4).
Referenced by muse_list_append().
MUSEAPI muse_cell muse_list_append (muse_env * env, muse_cell head, muse_cell tail)
Appends the tail list to the end of the head list and returns the head list.
The head list is thus destructively modified. If the head list is (), then the head list cannot be modified, so the tail list is returned as is.
References muse_list_last().
Referenced by fn_append_M().
MUSEAPI muse_cell muse_array_to_list (muse_env * env, int count, const muse_cell * array, int astep)
Constructs a new list whose contents are that of the given array in the given order.
Parameters
count The number of elements to extract from the array.
astep The step interval to reach the elements to extract. Typically, astep is 1.
References MUSE_NIL.
Referenced by fn_vector_to_list().
MUSEAPI muse_cell* muse_list_to_array (muse_env * env, muse_cell list, int * lengthptr)
Constructs a new array with the contents of the list in the given order.
If you give a non-NULL lengthptr, the length of the array will be stored in it. You should free() the result array when you're done with it.
MUSEAPI void muse_list_extract (muse_env * env, int count, muse_cell list, int lstep, muse_cell * array, int astep)
Extracts count elements from the list starting with the first element, into the given array.
List elements are extracted by stepping by lstep each time and array locations into which the extracted elements will be placed are obtained by stepping the array pointer by astep items for each element.
MUSEAPI muse_cell muse_generate_list (muse_env * env, muse_list_generator_t generator, void * context)
Creates a list whose contents are generated by the given generator function.
The generator function is called until it return "eol" or end-of-list. context is an arbitrary data pointer that's passed to the generator.
References MUSE_NIL.
Referenced by fn_hashtable_to_alist(), fn_list_files(), fn_list_folders(), fn_require(), fn_split(), fn_transpose(), fn_windows_registry_entry(), and muse_list().
MUSEAPI muse_cell muse_set_cell (muse_env * env, muse_cell cell, muse_cell head, muse_cell tail)
Sets the given cell's head and tail to the given cell references.
Works with symbols, lambdas, cons cells.
See Also
muse_set_head
muse_set_tail
MUSEAPI muse_cell muse_set_head (muse_env * env, muse_cell cell, muse_cell head)
Sets the head of the given cell.
See Also
muse_set_cell
muse_set_tail
MUSEAPI muse_cell muse_set_tail (muse_env * env, muse_cell cell, muse_cell tail)
Sets the tail of the given cell.
See Also
muse_set_cell
muse_set_tail
MUSEAPI muse_cell muse_set_text (muse_env * env, muse_cell text, const muse_char * start, const muse_char * end)
Copies the given string to the given text cell, modifying the cell's contents.
The previous contents of the cell are freed.
Referenced by muse_set_ctext().
MUSEAPI muse_cell muse_define (muse_env * env, muse_cell symbol, muse_cell value)
Sets the value of the symbol.
The current top-most value of the symbol on the symbol's value stack is replaced.
See Also
muse_pushdef
muse_popdef
MUSEAPI muse_cell muse_pushdef (muse_env * env, muse_cell symbol, muse_cell value)
Makes the given value the current value of the symbol, without losing the previously assigned set of values.
i.e. It pushes the value on the symbol's value stack.
MUSEAPI muse_cell muse_popdef (muse_env * env, muse_cell symbol)
Removes the current value on the symbol's value stack and returns it.
The cell used to hold a reference to the value is released immediately to the free list because it is not available to the language environment in normal circumstances, unless the program delves into the internal representation of symbols.
References _muse_process_frame_t::bindings_stack, and muse_stack::top.
MUSEAPI int muse_bindings_stack_pos (muse_env * env)
Gets the current depth of the bindings stack.
You can use this to locally introduce new bindings using muse_pushdef() and when you're done with the local definitions, use muse_bindings_stack_unwind() to return the state of the bindings to where they were when you got the bindings stack position.
See Also
muse_bindings_stack_unwind()
MUSEAPI void muse_bindings_stack_unwind (muse_env * env, int pos)
See Also
muse_bindings_stack_pos()
MUSEAPI muse_cell muse_dup (muse_env * env, muse_cell obj)
Deep copies the given object.
Leaves the duplicate object on the muSE stack upon return.
References MUSE_CONS_CELL, MUSE_FLOAT_CELL, MUSE_INT_CELL, and MUSE_NIL.
Referenced by fn_dup().
MUSEAPI muse_cell* muse_find_list_element (muse_env * env, muse_cell * list, muse_cell element)
Searches for the given element in the given list and returns a reference to it.
Parameters
list The list in which to search for the element. The first cell of the list is *list.
element The element to find. The list item found is first one that satisfies muse_equal().
Returns
If the element was found at the head of the list, it will return the value of list. If it was found elsewhere, then it will return a ptr such that muse_head(env,*ptr) is the element you searched for and you can remove the element with code like the following -
muse_cell list, element;
muse_cell *ptr = muse_find_list_element(env, &list, element);
if (ptr)
   *ptr = muse_tail(env,*ptr);
If the element could not be found, the return value is NULL.
References MUSE_CONS_CELL, and muse_equal().
Referenced by fn_write_xml(), and print_handler_choices().
MUSEAPI int muse_eq (muse_env * env, muse_cell a, muse_cell b)
Shallow compares two cells.
Two cells are "eq" if either they refer to the same cell, or they are equal intgers.
References MUSE_INT_CELL.
Referenced by fn_eq().
MUSEAPI int muse_equal (muse_env * env, muse_cell a, muse_cell b)
Deep compares two cells.
Returns
1 if the two cells are equal, 0 otherwise.
References MUSE_CONS_CELL, muse_equal(), MUSE_FLOAT_CELL, MUSE_INT_CELL, and MUSE_TEXT_CELL.
Referenced by muse_assoc(), muse_assoc_iter(), muse_bind_formals(), muse_equal(), and muse_find_list_element().
MUSEAPI int muse_compare (muse_env * env, muse_cell a, muse_cell b)
Deep compares two cells for ordering.
Returns
0 if the cells are eq, 1 if b < a and -1 if a < b.
References MUSE_CONS_CELL, MUSE_FLOAT_CELL, MUSE_INT_CELL, MUSE_NIL, MUSE_SYMBOL_CELL, muse_symbol_name(), and MUSE_TEXT_CELL.
MUSEAPI muse_cell muse_symbol_plist (muse_env * env, muse_cell sym)
Returns the property list of the given symbol.
The symbol can be either a named symbol such as that created by the muse_symbol() class of functions, or an anonymous symbol created by muse_mk_anon_symbol().
Referenced by fn_plist(), and muse_get_prop().
MUSEAPI muse_cell muse_assoc (muse_env * env, muse_cell alist, muse_cell prop)
Looks up a particular association by key in an association list.
An association list has the form
((key1 . value1) (key2 . value2) ... (keyN . valueN))
When given a key keyK, it returns the pair
(keyK . valueLK)
if the key can be found in the association list, or () if it doesn't exist in the list.
Note
I'm considering changing this function to return the list whose head is the found key-value pair instead. This will let us search through an assoc list for all instances of a given key.
References muse_assoc(), muse_equal(), and MUSE_NIL.
Referenced by muse_assoc(), and muse_get_prop().
MUSEAPI muse_cell* muse_assoc_iter (muse_env * env, muse_cell * alist, muse_cell prop)
Similar to muse_assoc, except that the return value is not the kvpair, but the list position of the kvpair.
Since the return value is also an assoc list, you can iterate through the list using this function.
The reason the return value is given as a muse_cell* instead of simply a muse_cell is so that you can remove the found cell using a simple pointer setting operation, from the assoc list.
muse_cell alist, prop;
muse_cell *pos = muse_assoc_iter(&alist, prop);
(*pos) = muse_tail(*pos);
If the property is not found in the alist, the return value is a pointer to the tail cell of the end of the alist. This way, you can add the item to the end if the property is not found.
muse_cell alist, prop, defval;
muse_cell *pos = muse_assoc_iter(&alist, prop);
if (!*pos)
   (*pos) = muse_cons( muse_cons( prop, defval ), MUSE_NIL );
References muse_assoc_iter(), and muse_equal().
Referenced by muse_assoc_iter().
MUSEAPI muse_cell muse_get_prop (muse_env * env, muse_cell sym, muse_cell prop)
Looks up the given property in the given symbol's property list.
The return value is the pair whose head is the property key and the tail is the property value.
References muse_assoc(), and muse_symbol_plist().
MUSEAPI muse_cell muse_get (muse_env * env, muse_cell obj, muse_cell key, muse_cell argv)
Recursive property getter.
First gets the property key of the object obj. If argv is MUSE_NIL, that becomes the result. Otherwise, that result is used as the target for yet more property keys extracted from argv.
See Also
muse_put()
References muse_prop_view_t::get_prop, muse_get(), MUSE_NIL, and MUSE_SYMBOL_CELL.
Referenced by fn_get(), muse_get(), and muse_put().
MUSEAPI muse_cell muse_put_prop (muse_env * env, muse_cell sym, muse_cell prop, muse_cell value)
Sets or adds the given property-value association to the symbol's property list.
If the property already exists in the symbol's plist, the value of the property is changed to the new one. If it doesn't exist, a new cell with the new association is created and added to the symbol's property list.
Returns
The cell in the symbol's plist that contains the association.
MUSEAPI muse_cell muse_put (muse_env * env, muse_cell obj, muse_cell prop, muse_cell argv)
Deeply nested value setting support.
If the argv has a single element, then that becomes the value of the prop key of the obj.
If the argv has more than one element, then the call recurses into the object that is the prop of obj.
Exceptions
error:readonly-object
Handler
(fn (resume 'error:readonly-object obj prop . argv) ...)
When You tried to set a property of a read-only object.
Resume By performing the expected operation and passing the expected result of the put operation that failed.
See Also
muse_get()
References muse_get(), MUSE_NIL, muse_put(), muse_raise_error(), MUSE_SYMBOL_CELL, and muse_prop_view_t::put_prop.
Referenced by fn_put(), fn_put_many(), muse_put(), muse_put_many(), and syntax_lambda().
MUSEAPI muse_cell muse_put_many (muse_env * env, muse_cell obj, muse_cell argv)
(put* thing key1 value1 key2 value2 ... keyN valueN)
Multiple property setting.
See Also
put*
References MUSE_NIL, and muse_put().
Referenced by fn_stats().
MUSEAPI muse_cell muse_load (muse_env * env, FILE * f)
Reads all symbolic expressions in the stream and evaluates them one by one, until end of stream.
Returns the result of evaluating the last s-expression in the stream.
Use this to load definitions from files.
References muse_assign_port(), muse_pload(), MUSE_PORT_TRUSTED_INPUT, and muse_unassign_port().
Referenced by fn_load().
MUSEAPI muse_cell muse_eval (muse_env * env, muse_cell sexpr, muse_boolean lazy)
Evaluates the given symbolic expression.
- Numbers, strings, native functions and lambda
    functions evaluate to themselves.
- Quoted expressions evaluate to their unquoted forms.
- A list is evaluated by evaluating the first
    element, interpreting it as a function to be
    supplied the rest of the list as arguments. If
    the first element is not a function, then the
    list evaluates to itself.
The result of the evaluation is usually protected by the stack if it is a newly allocated cell.
References muse_apply(), MUSE_CONS_CELL, and MUSE_SYMBOL_CELL.
Referenced by fn_eval(), muse_do(), muse_force(), and syntax_if().
MUSEAPI muse_cell muse_evalnext (muse_env * env, muse_cell * sexpr)
Evaluates the head of the list referred to by the given sexpr pointer and steps the pointer to the tail of the list, getting ready for the next call.
This is useful to evaluate arguments inside native functions.
Referenced by fn_fetch_uri().
MUSEAPI muse_cell muse_apply (muse_env * env, muse_cell fn, muse_cell args, muse_boolean args_already_evaluated, muse_boolean lazy)
Applies the given native function or lambda to the given list of arguments and returns the result.
The arguments are not evaluated when passing them to a native function but are evaluated when passing to a lambda. Not evaluating the arguments for a native function lets us define syntaxes in native code. If you're passing already evaluated arguments in the args list, set the args_already_evaluated parameter to MUSE_TRUE.
See Also
muse_apply_lambda
References muse_eval_list(), MUSE_FLOAT_CELL, MUSE_INT_CELL, MUSE_LAMBDA_CELL, MUSE_LAZY_CELL, muse_message(), MUSE_NATIVEFN_CELL, muse_similar_symbol(), MUSE_SYMBOL_CELL, muse_symbol_name(), and yield_process().
Referenced by fn_system(), fn_with_incoming_connections_to_port(), module_syntax(), muse_eval(), and muse_force().
MUSEAPI muse_cell muse_do (muse_env * env, muse_cell block)
A block of code is a list of expressions to evaluate in sequence.
The result of evaluating a block is the result of evaluating the last expression in the block.
References muse_eval(), and MUSE_NIL.
Referenced by fn_with_recent(), and fn_with_timeout_us().
MUSEAPI muse_cell muse_quote (muse_env * env, muse_cell args)
Returns the given arguments quoted.
The behaviour of quote is that
s = _eval(muse_quote(s))
References MUSE_QUOTE.
Referenced by ez_parse(), muse_bind_copy_expr(), and muse_pread().
MUSEAPI muse_boolean muse_bind_formals (muse_env * env, muse_cell formals, muse_cell args)
Binds the symbols in the given formals list to the corresponding values in the args list.
This recursive definition of muse_(un)bind_formals can perform arbitrary structure pattern matching between the formals specification and the given arguments.
For ex: A formals specification of
((a b) (c . d))
and an argument list with the structure
((1 2) (3 4 5 6))
will cause the bindings -
a = 1
b = 2
c = 3
d = (4 5 6)
You're allowed to use function values in patterns, which you can create using the braces notation to evaluate code at read-time. When such a function value is encountered, its arguments are first pattern tested against the value at the position of the function. If the pattern testing succeeds and the body of the function evalutes to a non-NIL value, then the bindings are left as is for the remainder of the evaluation context. If either the argument pattern didn't match or the function body evaluated to nil, then the bindings are reversed and the pattern match is taken to have failed. These functions in patterns therefore serve as guards.
For example, here is a contrived function of two arguments "a" and "b" which returns "b-a" if b > a and fails otherwise -
(fn {fn (a b) (< a b)} (- b a))
Returns
MUSE_TRUE if the match succeeded and MUSE_FALSE if some element failed. In case of failure, no variables are bound.
See Also
syntax_lambda
syntax_case
syntax_let
References muse_bind_formals(), MUSE_CONS_CELL, muse_equal(), muse_head(), MUSE_LAMBDA_CELL, MUSE_LAZY_CELL, MUSE_NIL, MUSE_SYMBOL_CELL, and muse_tail().
Referenced by muse_bind_formals(), and syntax_case().
MUSEAPI muse_cell muse_raise_error (muse_env * env, muse_cell error, muse_cell info)
Raises an error which can be resumed just like an exception raised using the raise operator.
The handler pattern that will match the raised error is given by -
(ex error . info)
ex - The resume continuation.
error - A symbol identifying the error.
info - Arbitrary info to be passed on to handlers.
Referenced by check_timeout(), fn_char_code(), fn_fetch_uri(), fn_image_properties(), fn_load(), fn_md5_hash(), fn_module(), fn_open_connection(), fn_sha1_hash(), fn_slice(), fn_string_to_bytes(), fn_substring(), fn_super_invoke(), fn_super_invoke_explicit(), fn_supers(), fn_urldecode(), fn_urlencode(), fn_windows_registry_entry(), fn_with_incoming_connections_to_port(), muse_intern_symbol(), muse_message(), muse_put(), and muse_slot().
MUSEAPI muse_cell muse_bind_copy_expr (muse_env * env, muse_cell body, muse_boolean list_start)
A key function for implementing portions of closure creation.
What it does is top create a copy of the given "body" expression binding all defined symbols to their values along the way.
Parameters
body The expression whose copy needs to be created.
list_start If the body expression is the head part of a list expression, pass MUSE_TRUE, otherwise pass MUSE_FALSE. In general, you should pass MUSE_FALSE.
References muse_scope_view_t::begin, muse_scope_view_t::end, fn_define(), fn_quote(), muse_bind_copy_expr(), MUSE_CONS_CELL, MUSE_NATIVEFN_CELL, MUSE_NIL, MUSE_QUOTE, muse_quote(), MUSE_SYMBOL_CELL, syntax_block(), syntax_case(), syntax_generic_block(), syntax_generic_lambda(), syntax_lambda(), and syntax_let().
Referenced by muse_bind_copy_expr(), and syntax_lambda().
MUSEAPI muse_int muse_hash (muse_env * env, muse_cell obj)
Hashes a given cell reference.
The hash has the property that if two cells have different hashes, they are not eq.
References MUSE_FLOAT_CELL, muse_hash_data(), muse_hash_text(), MUSE_INT_CELL, MUSE_SYMBOL_CELL, and MUSE_TEXT_CELL.
MUSEAPI muse_int muse_hash_data (const unsigned char * start, const unsigned char * end, muse_int initial)
Creates a simple hash of the given data.
This hash is sufficient for strings, but not robust enough for arbitrary data. Use some other hash scheme if you want greater strength.
Referenced by muse_hash().
MUSEAPI void* muse_tick ()
Used for performance timing.
muse_tick() captures the current time and returns a handle containing the time information. Use it with muse_tock() to get the time elapsed between the two calls in microseconds.
Referenced by fn_time_taken_us(), muse_gc(), muse_init_env(), and push_timeout().
MUSEAPI muse_int muse_elapsed_us (void * arg)
Returns the time elapsed since the start of the given timer.
The timer is the object returned by muse_tick().
Referenced by check_timeout(), fn_receive(), fn_run(), muse_tock(), and switch_to_process().
MUSEAPI muse_int muse_tock (void * arg)
When passed the timing handle returned by muse_tick(), it returns the time elapsed between the muse_tick() call and this muse_tock() call in microseconds.
The handle becomes unusable after it is passed to muse_tock().
References muse_elapsed_us().
Referenced by fn_time_taken_us(), muse_destroy_env(), and muse_gc().
MUSEAPI size_t muse_sprintf (muse_env * env, muse_char * buffer, size_t maxlen, const muse_char * format, ...)
Formats a string consisting of the given format string with the other argument objects inserted at specified positions.
%m prints the next argument given as a muse_cell.
%t prints the type of the argument given as a muse_cell.
%i prints the cell index of the argument. This is like a pointer to the cell.
%s means the next argument is a unicode string and has to be included literally in the message.
%f means the next argument is a muse_float.
%d means the next argument is a muse_int.
%@ prints the data and time in a standard format.
%% prints the % character itself.
Returns
The number of characters used in the buffer.
Todo:
The maxlen is not strictly adhered to and its good to give an extra 20 characters more than what you actually need. Needs to be fixed to be strict.
See Also
muse_vsprintf
Referenced by muse_trace_report().
MUSEAPI void muse_message (muse_env * env, const muse_char * context, const muse_char * message, ...)
Displays a message string formatted according to the given message string with format codes.
The format codes are the same as for muse_sprintf().
Parameters
message A format string possibly containing codes indicating where and how to insert a string representation of further arguments.
See Also
muse_sprintf
muse_vsprintf
References MUSE_NIL, muse_raise_error(), and muse_trace_report().
Referenced by fn_add(), fn_alert(), fn_apply_w_keywords(), fn_call_w_keywords(), fn_datafn(), fn_define(), fn_div(), fn_load(), fn_mul(), fn_post(), fn_retry(), fn_sub(), fn_substring(), fn_the(), muse_add_finalizer(), muse_apply(), muse_box_get(), muse_box_set(), muse_pread(), syntax_case(), syntax_finally(), syntax_for(), syntax_if(), syntax_local(), and syntax_while().
MUSEAPI muse_boolean muse_expect (muse_env * env, const muse_char * context, const muse_char * spec, ...)
Checks whether a set of expectations are satisfied by some values.
The spec parameter is a string of condition characters that consume arguments and perform the appropriate tests. This function, which is itself a sort of mini language, is motivated by the fact that I've often coded ASSERT statements encoding multiple conditions that must be jointly satisfied in some way, having the assert fail, and not immediately knowing which of those conditions was responsible for the failure and the vales involved. If the entire set of expectations fails in some way, the generated error report (message box or stderr print out) is rather informative about which exact expectation was violated.
's' -> The next argument is a symbol (given as muse_cell) which will be used as the subject of subsequent tests. Its value will be used in any tests that may require it.
'v' -> The next argument is a value (given as a muse_cell) which will be used as the subject of subsequent tests. You can use this if you want to check some properties of a value which is not the value of any symbol you know. If you know the symbol, then use 's' in order to get better diagnostic messages.
':' -> The symbol must be defined to some value. The argument is expected to be a unicode string that describes what the symbol must be defined as. Ex: "a function", "a number", etc. This label is used in the message text.
'?' -> Next argument is int and the value of the symbol must be of that type - given by enum muse_cell_t.
'=' -> The symbol's value must be "eq" to the next argument, which is given as muse_cell.
'[' -> The next argument must be a muse_float and the symbol's value will be checked for >= the given limit.
']' -> The next argument must be a muse_float and the symbol's value will be checked for <= the given limit.
'(' -> The next argument must be a muse_float and the symbol's value will be checked for > the given limit.
')' -> The next argument must be a muse_float and the symbol's value will be checked for < the given limit.
"|blah|" -> The symbol must satisfy at least one of the conditions within the || pair. i.e. the conditions are "or"ed.
'!' -> Placing this character causes the result of the following test to be inverted. For example, a "not-defined" check can be encoded as "!:". The following test can be an or-block too.
Referenced by fn_add(), fn_div(), fn_mul(), fn_set_M(), fn_sub(), and syntax_case().
MUSEAPI muse_cell muse_similar_symbol (muse_env * env, muse_cell symbol, int * outDistance, muse_nativefn_t predicate, void * context)
Sometimes, it is useful to know whether another symbol that's very similar in textual representation from a known symbol.
For example, the user may make a spelling mistake in keying in a symbol and it'll be useful to know the alternative. You can use this function in such circumstances to determine the symbol that is very similar to the known symbol, yet different, so that you can warn the user about the closeness.
You can obtain the levenshtein distance measure between the two symbols if you supply an int pointer in outDistance. You can then use the distance measure to decide whether the similar symbol is worth bothering about.
If you only want to consider certain types of symbols, you can give a predicate and an arbitrary context pointer that will be given to it. muse_symbol_is_defined can be used as a predicate, with a context pointer of NULL to consider only defined symbols.
References muse_stack::bottom, MUSE_NIL, muse_symbol_name(), and muse_stack::size.
Referenced by muse_apply().
MUSEAPI muse_cell muse_symbol_with_value (muse_env * env, muse_cell value)
Searches the symbol table to find a symbol whose current value is the given cell.
The value's contents are not used in the comparison, but the symbol must actually contain this particular cell as its value. This function is useful to lookup a function name given a native function object. If a symbol exists with the given value, it is returned. Otherwise it returns MUSE_NIL.
Beware that the complexity of this operation is linear w.r.t. the number of symbols in the environment - defined or undefined.
References muse_stack::bottom, MUSE_NIL, and muse_stack::size.
MUSEAPI muse_cell muse_symbol_is_defined (muse_env * env, void * context, muse_cell symbol)
Returns T if the given symbol is defined and () if it isn't.
The design of this function might look too bloated for just checking whether a symbol is defined or not. The signature is like this just so you can use it as an argument to muse_similar_symbol() to consider only defined symbols.
References MUSE_NIL, and MUSE_T.
MUSEAPI size_t muse_unicode_to_utf8 (char * out, size_t out_maxlen, const muse_char * win, size_t win_len)
Converts the given double-byte unicode string to multibyte UTF8 string.
Note that it'll place the terminating null character only if the output buffer can hold it as well.
Parameters
out The output buffer to store the UTF8 string.
out_maxlen The maximum number of characters (bytes) that the output buffer can hold.
win The input wide character string.
win_len The number of input wide characters to convert.
Returns
The number of bytes written to the output UTF8 buffer, excluding any terminating null character that we written.
References uc16_to_utf8().
Referenced by fn_md5_hash(), fn_open_connection(), fn_sha1_hash(), fn_string_to_bytes(), fn_with_incoming_connections_to_port(), muse_fopen(), and muse_link_plugin().
MUSEAPI size_t muse_utf8_to_unicode (muse_char * wout, size_t wout_maxlen, const char * in, size_t in_len)
Converts the given UTF8 string to double-byte unicode string.
Note that it'll place the terminating null character only if the output buffer can hold it as well.
Parameters
in The input UTF8 encoded string.
in_len The number of bytes in the UTF8 string.
wout The output buffer to store the double byte unicode string.
wout_maxlen The maximum number of double-byte characters that can be written to the output buffer.
Returns
The number of output characters written the buffer, excluding any terminating null character that might have been written.
References utf8_to_uc16().
Referenced by muse_mk_text_utf8(), and muse_symbol_utf8().
MUSEAPI int muSEexec_check (FILE * e, int * source_pos, int * source_size, int * footer_size)
A muSE executable is a binary file to the end of which souce code is appended.
This source code is expected to be loaded before any other operation is done. The way we determine whether such attached source code is available or not is to check the last 20 bytes which must have the following format - ;<10-digit-decimal-number> muSEexec The decimal number gives the size in bytes of the source code stream that precedes this end code. The rationale for the above format for the ending code is that when the source code is loaded, this sequence will be ignored because it looks like a scheme comment.
muSEexec_check checks whether such an end code is present in the given executable file and if so, returns the source start position and source size in the locations supplied as arguments.
The return value is 1 if the file has such attached code and 0 if the file doesn't have attached code. In either case, the file's seek pointer is not modified.
References muse_fsize().
Referenced by fn_file_has_attached_code_p(), and fn_load().
MUSEAPI int muSEexec_finish (FILE * e, int source_size)
Seeks to the end of the file and writes out the footer containing the number of bytes of source appended to the end of the given file.
After writing out the footer, the file is closed.
MUSEAPI muse_cell muse_link_plugin (muse_env * env, const muse_char * path, muse_cell arglist)
Loads a muse plugin DLL and calls its entry point function which is to have the name "muse_plugin_entry" and be of the type muse_plugin_entry_t.
The function must be declared extern "C" if defined in a CPP file and must be exported from the DLL.
The entry point function receives 3 arguments -
The first argument is the HMODULE of the loaded library.
The second argument is the muse environment pointer.
The third argument is an arbitrary argument list that can used for whatever purpose the plugin sees fit. The entry point function must call muse_set_current_env() with the given env pointer before calling any other muse functions.
Parameters
path Path to the DLL file.
arglist Arg list passed to the entry point function.
See Also
muse_plugin_entry_t
References MUSE_NIL, and muse_unicode_to_utf8().
Referenced by fn_load_plugin().
MUSEAPI void muse_repl (muse_env * env)
The muSE REPL - Read-Eval-Print-Loop.
It reads symbolic expressions from standard input, evaluates them and writes the result of the evaluation to the standard output.
The only way to return from the function is to exit the program by typing
(exit)
into the command line.
References MUSE_CONS_CELL, MUSE_ENABLE_OBJC, MUSE_FLOAT_CELL, MUSE_INT_CELL, MUSE_NATIVEFN_CELL, muse_pread(), MUSE_SYMBOL_CELL, MUSE_TEXT_CELL, port_flush(), and port_getc().
MUSEAPI muse_functional_object_t* muse_create_and_init_object (muse_env * env, muse_functional_object_type_t * type_info, muse_cell init_args)
Just creates an object without allocating a cell for it.
It is the caller's responsibility to call muse_destroy_object() once she's done with it.
MUSEAPI muse_cell muse_mk_functional_object (muse_env * env, muse_functional_object_type_t * type_info, muse_cell init_args)
Creates a new functional object instance based on the given type information.
The type of the returned cell is a native function, so that the object can be used in the function position.
References muse_functional_object_type_t::fn, and muse_functional_object_t::type_info.
Referenced by fn_image_properties(), fn_module(), and fn_with_recent().
MUSEAPI muse_port_t muse_port (muse_env * env, muse_cell p)
Takes a muSE port represented as a cell and returns the internal port object that it uses.
If the given thing is not a port, then it returns NULL.
Referenced by fn_http_respond(), fn_load(), fn_md5_hash(), fn_read_json(), fn_sha1_hash(), and fn_write_json().
MUSEAPI muse_port_t muse_assign_port (muse_env * env, FILE * f, int mode)
Creates a port definition that you can use to read/write stuff from a given file pointer.
The returned port is only for use by the API when it has a file pointer and must use the port calls such as muse_pread() several times on the same port.
Ports assigned using muse_assign_port must be released using muse_unassign_port.
Parameters
f The file that the new port should read from.
mode A combination of muse_port_mode_bits_t indicating properties of the file port.
References MUSE_PORT_READ, MUSE_PORT_READ_DETECT_MACROS, MUSE_PORT_WRITE, and port_init().
Referenced by fn_generate_documentation(), and muse_load().
MUSEAPI void muse_unassign_port (muse_port_t p)
Unassigns a file port which was earlier assigned using muse_assign_port.
Should not be used with other ports.
References MUSE_PORT_WRITE, port_destroy(), and port_flush().
Referenced by fn_generate_documentation(), and muse_load().
MUSEAPI muse_cell muse_pread (muse_port_t f)
Reads the next symbolic expression at the current stream position, ignoring white space and comment lines.
Parameters
f The port from which the expression is to be read.
References _muse_port_base_t::env, ez_skip_whitespace(), MUSE_ENABLE_OBJC, muse_message(), MUSE_NIL, MUSE_PORT_EZSCHEME, MUSE_PORT_READ_EXPAND_BRACES, muse_pread(), muse_quote(), port_eof(), port_getc(), and port_ungetc().
Referenced by fn_read(), fn_top_level_handler(), muse_pload(), muse_pread(), and muse_repl().
MUSEAPI void muse_pwrite (muse_port_t f, muse_cell sexpr)
Writes the given s-expression to the given stream.
If the expression contains only basic objects such as numbers, lists and symbols, then output of write is suitable to read back by muse_pread(). Otherwise, the only difference between write and print is that write encloses strings in quotes and print doesn't.
Referenced by fn_reply(), fn_top_level_handler(), fn_write(), and print_handler_choices().
MUSEAPI void muse_mickey (muse_port_t in, muse_port_t out)
Processes mickey streams from input port to output port.
Mickey streams let you use muSE as a powerful yet simple macro expander. You may find this useful in scripting, dynamic documents in web applications, etc.
A mickey stream is a stream of text with embedded "mickey" codes - of the form ..expr...@ where the portion between the "@" signs (which look like Mickey's ears and hence the name) is interpreted as a muSE expression. The result of evaluating the expression is used in place of the @ expression itself (without the mickey ears).
If you put a sequence of expressions within .expr..@, the mickey block will evaluate to the value of the last expression - behaving like a (do ..) block.
Note that scheme symbols and atoms are themselves allowed to use the @ character within a mickey expression. So, for example, if you simply want a symbol Hello to expand to its value "World", you should write it like this - ;@ The ; character will terminate the symbol name and ignore all characters up to the next new line or @ whichever comes first. In general, it is a good idea to end a mickey expression with ;@ instead of just Stuff like @(+ 1 2)@ will work correctly however.
If you have a symbol starting with an @ character (say), you can place its value in the output using @(eval ')
If you want to place a literal @ character in the output stream, simply use @ in the input stream wherever you need the literal For example, an email address would look like somebody@somewhere.com in the input stream.
References port_eof(), port_getc(), and port_putc().
Referenced by fn_mickey().
MUSEAPI muse_port_t muse_current_port (muse_env * env, muse_stdport_t which, muse_port_t port)
If port is NULL, retrieves the current input port for the current process.
If port is not NULL, changes the current input port to the given one and returns the previously current input port.
References _muse_process_frame_t::current_port.
Referenced by fn_json(), fn_read_json(), fn_scheme_syntax(), fn_tab_syntax(), fn_write_json(), fn_xml(), muse_define_builtin_fileport(), and muse_pload().
MUSEAPI muse_cell muse_mk_vector (muse_env * env, int length)
Creates a new vector object that has enough slots allocated to hold the given number of objects.
All slots are initialized to MUSE_NIL.
References fn_mk_vector(), and MUSE_NIL.
MUSEAPI muse_cell muse_mk_hashtable (muse_env * env, int length)
Creates a hashtable with a bucket count setup according to the given desired length.
Note that calling muse_hashtable_length() without first putting anything into the hashtable will always get you 0. The "length" of the hashtable is the number of key-value pairs put into it.
References fn_mk_hashtable(), and MUSE_NIL.
MUSEAPI muse_cell muse_hashtable_get (muse_env * env, muse_cell ht, muse_cell key)
Returns the key-value pair with the given key as the head if the key is present in the hash table, otherwise it returns MUSE_NIL.
The value associated with the key will be in the tail of the returned pair.
References MUSE_NIL.
MUSEAPI muse_cell muse_hashtable_put (muse_env * env, muse_cell ht, muse_cell key, muse_cell value)
Associates the given value with the given key in the hash table.
The given value replaces any previous value that might have been associated with the key.
References MUSE_NIL.
MUSEAPI muse_cell muse_mk_box (muse_env * env, muse_cell contents)
Creates a new box with the given contents.
If you pass MUSE_NIL for the contents, it is equivalent to creating an empty box.
References muse_box_set(), and MUSE_NIL.
MUSEAPI muse_cell muse_box_set (muse_env * env, muse_cell box, muse_cell contents)
Changes the contents of the given box to the new value.
Returns the new value.
References muse_message(), and MUSE_NIL.
Referenced by muse_mk_box().