muSE: Type casting
Type casting
Functions
muse_cell fn_int (muse_env *env, void *context, muse_cell args)
muse_cell fn_float (muse_env *env, void *context, muse_cell args)
muse_cell fn_number (muse_env *env, void *context, muse_cell args)
muse_cell fn_string (muse_env *env, void *context, muse_cell args)
muse_cell fn_format (muse_env *env, void *context, muse_cell args)
muse_cell fn_char_code (muse_env *env, void *context, muse_cell args)
muse_cell fn_string_with_char_codes (muse_env *env, void *context, muse_cell args)
Detailed Description
Function Documentation
muse_cell fn_int (muse_env * env, void * context, muse_cell args)
(int thing)
Converts the given thing to an integer or returns () if it cannot. Integers, floats and strings containing integers can be converted to integers using this function.
References MUSE_FLOAT_CELL, MUSE_INT_CELL, MUSE_NIL, and MUSE_TEXT_CELL.
muse_cell fn_float (muse_env * env, void * context, muse_cell args)
(float thing)
Converts the given thing to a floating point number or returns () if it cannot. Integers, floats and strings containing floats can be converted to floats using this function.
References MUSE_FLOAT_CELL, MUSE_INT_CELL, MUSE_NIL, and MUSE_TEXT_CELL.
muse_cell fn_number (muse_env * env, void * context, muse_cell args)
(number thing)
Returns a number - either int or float. If thing is a string, it is parsed to determine whether it is an int or float. Returns () if thing cannot be converted to a number.
References MUSE_FLOAT_CELL, MUSE_INT_CELL, MUSE_NIL, and MUSE_TEXT_CELL.
muse_cell fn_string (muse_env * env, void * context, muse_cell args)
(string thing)
Behaves almost the same as format when applied to thing. The difference is that format accepts any number of arguments whose strings forms are concatenated into one big string. string only accepts one argument.
So why have a separate function?
When thing is a number, string takes an optional second argument that gives a printf style format specification string for converting the number to a string. For everything else, the second argument, if supplied, is ignored. The formatting should not result in generating a string that is longer than 128 characters, including the terminating null character.
References fn_format(), MUSE_FLOAT_CELL, muse_float_value(), MUSE_INT_CELL, muse_int_value(), muse_mk_ctext(), MUSE_NIL, MUSE_TEXT_CELL, and muse_text_contents().
muse_cell fn_format (muse_env * env, void * context, muse_cell args)
(format ...args...)
Converts each arg to a string, concatenates all the strings and returns the result as a single string. Things that support the 'frmt' view such as bytes? and object? convert themselves to strings.
Objects, in particular, get their "as-string" methods invoked to get a string representation. The "as-string" can also be a field. If it isn't a method, its value is used as the string representation of the object. In particular, the "as-string" implementation can return or be any object which can be converted to a string, such as int, float or even another object.
For example -
> (define ex
    (object ()
      'name     "telepathic-robot"
      'id       3
      'as-string (fn (self) (format self.name "-" self.id))))
> (format "object=" ex)
object=telepathic-robot-3
References fn_format(), muse_add_recent_item(), muse_eval_list(), muse_mk_text(), and MUSE_NIL.
muse_cell fn_char_code (muse_env * env, void * context, muse_cell args)
(char-code string [n])
Gives the numeric code of a character in the given string. The second optional integer argument gives the index of the character whose code is requested. The index defaults to 0.
References MUSE_INT_CELL, MUSE_NIL, muse_raise_error(), and muse_text_contents().
muse_cell fn_string_with_char_codes (muse_env * env, void * context, muse_cell args)
(string-with-char-codes code0 code1 code2 ...)
Builds a string whose characters are given by the integer codes in the argument list. If you give N arguments, the resultant string will be of length N.
References muse_eval_list(), muse_list_length(), muse_mk_text(), and muse_text_contents().