muSE: Hashtables
Hashtables
Functional objects
A functional hash table is a function from symbols or integers to arbitrary values.
Functions
muse_cell fn_mk_hashtable (muse_env *env, void *context, muse_cell args)
(mk-hashtable [datafn] [size]).
muse_cell fn_hashtable_p (muse_env *env, void *context, muse_cell args)
(hashtable? ht).
muse_cell fn_hashtable_size (muse_env *env, void *context, muse_cell args)
(hashtable-size ht).
muse_cell fn_alist_to_hashtable (muse_env *env, void *context, muse_cell args)
(hashtable alist).
muse_cell fn_hashtable_to_alist (muse_env *env, void *context, muse_cell args)
(hashtable->alist ht).
MUSEAPI muse_cell muse_mk_hashtable (muse_env *env, int length)
Creates a hashtable with a bucket count setup according to the given desired length.
MUSEAPI int muse_hashtable_length (muse_env *env, muse_cell ht)
Returns the number of key-value pairs put into the hash table.
MUSEAPI muse_cell muse_hashtable_get (muse_env *env, muse_cell ht, muse_cell key)
Returns the key-value pair with the given key as the head if the key is present in the hash table, otherwise it returns MUSE_NIL.
MUSEAPI muse_cell muse_hashtable_put (muse_env *env, muse_cell ht, muse_cell key, muse_cell value)
Associates the given value with the given key in the hash table.
Detailed Description
A functional hash table is a function from symbols or integers to arbitrary values.
When given only a single key argument, it returns the value associated with the key. If no value is associated with the key, it returns (). Note that this means you can't distinguish between a key being associated with a () value and the key not being present in the hash table.
When given two arguments key and value, adds the association to the hash table and returns the value. If you want to remove a key's association from the hash table, pass a second argument of ().
Examples -
(define ht (mk-hashtable))
(ht 'ceo 'pete)
(ht 'coo 'terence)
(ht 'company 'muvee)
(print (ht 'ceo))
     > pete
(print (hashtable-size ht))
     > 3
(print (hashtable->alist ht))
     > ((coo . terence) (ceo . pete) (company . muvee))
(ht 'company ())
(print (hashtable-size ht))
     > 2
(print (hashtable->alist ht))
     > ((coo . terence) (ceo . pete))
Function Documentation
muse_cell fn_mk_hashtable (muse_env * env, void * context, muse_cell args)
(mk-hashtable [datafn] [size]).
Creates a new hash table. No arguments are required, but you can give the expected size of the hash table as an argument and/or the datafn to use to map keys to values. You may give the size and the datafn in any order.
Referenced by fn_alist_to_hashtable(), and muse_mk_hashtable().
muse_cell fn_hashtable_p (muse_env * env, void * context, muse_cell args)
(hashtable? ht).
Returns ht if it is a functional hashtable, or () if it isn't.
References MUSE_NIL.
muse_cell fn_hashtable_size (muse_env * env, void * context, muse_cell args)
(hashtable-size ht).
Returns the number of key-value pairs stored in the hash table.
muse_cell fn_alist_to_hashtable (muse_env * env, void * context, muse_cell args)
(hashtable alist).
Returns a hash table with the same contents as the given alist.
Supports the.
References fn_alist_to_hashtable(), fn_mk_hashtable(), muse_add_recent_item(), and MUSE_NIL.
Referenced by fn_alist_to_hashtable().
muse_cell fn_hashtable_to_alist (muse_env * env, void * context, muse_cell args)
(hashtable->alist ht).
Returns an alist version of the contents of the given hash table. The order of the elements is unpredictable.
References fn_hashtable_to_alist(), muse_add_recent_item(), and muse_generate_list().
Referenced by fn_hashtable_to_alist().
MUSEAPI muse_cell muse_mk_hashtable (muse_env * env, int length)
Creates a hashtable with a bucket count setup according to the given desired length.
Note that calling muse_hashtable_length() without first putting anything into the hashtable will always get you 0. The "length" of the hashtable is the number of key-value pairs put into it.
References fn_mk_hashtable(), and MUSE_NIL.
MUSEAPI muse_cell muse_hashtable_get (muse_env * env, muse_cell ht, muse_cell key)
Returns the key-value pair with the given key as the head if the key is present in the hash table, otherwise it returns MUSE_NIL.
The value associated with the key will be in the tail of the returned pair.
References MUSE_NIL.
MUSEAPI muse_cell muse_hashtable_put (muse_env * env, muse_cell ht, muse_cell key, muse_cell value)
Associates the given value with the given key in the hash table.
The given value replaces any previous value that might have been associated with the key.
References MUSE_NIL.