muSE: Basic cell, list and symbol manipulation
Basic cell, list and symbol manipulation
Functions
muse_cell fn_define (muse_env *env, void *context, muse_cell args)
muse_cell fn_define_extension (muse_env *env, void *context, muse_cell args)
muse_cell fn_define_override (muse_env *env, void *context, muse_cell args)
muse_cell fn_set_M (muse_env *env, void *context, muse_cell args)
muse_cell fn_setf_M (muse_env *env, void *context, muse_cell args)
muse_cell fn_setr_M (muse_env *env, void *context, muse_cell args)
muse_cell fn_first (muse_env *env, void *context, muse_cell args)
muse_cell fn_rest (muse_env *env, void *context, muse_cell args)
muse_cell fn_nth (muse_env *env, void *context, muse_cell args)
muse_cell fn_take (muse_env *env, void *context, muse_cell args)
muse_cell fn_drop (muse_env *env, void *context, muse_cell args)
muse_cell fn_dup (muse_env *env, void *context, muse_cell args)
muse_cell fn_list (muse_env *env, void *context, muse_cell args)
muse_cell fn_append_M (muse_env *env, void *context, muse_cell args)
Detailed Description
Function Documentation
muse_cell fn_define (muse_env * env, void * context, muse_cell args)
 (define symbol value)
Sets the current value of the symbol. symbol is not evaluated, value is evaluated.
Examples -
This example simply evaluates value and assigns it as the value of the given symbol.
 (define symbol value)
The second example provides additional documentation about the symbol being defined, using an arbitrary property structure identified by the keyword doc at the head of the documentation block, followed by an association list of the documentation writer's own choosing. Typical documentation property words include usage for a brief description of the usage syntax, descr for a more elaborate description of the object being created, and brief for a brief textual description of the purpose of the object.
 (define symbol
   (doc (usage "(symbol param1 param2)")
        (descr "Computes symbol")
        (param1 "The first value")
        (param2 "The second value"))
   (fn (p1 p2) (+ p1 p2)))
The defined function takes two arguments and returns their sum. Pretty lame function, but serves to illustrate.
If you want the documentation block to be ignored by the reader, then you should call muse_init_env with the MUSE_DISCARD_DOC parameter set to MUSE_TRUE.
Generic functions
If the given symbol is already bound to a generic function, define behaves like define-extension - i.e. it extends the definition of the generic function with the new function's case.
Declarations
If you're defining a function and you leave its body empty - for example -
 (define (f x y))
or
 (define f (fn (x y)))
, it is taken to mean a declaration of the function's argument pattern. The purpose of a declaration facility is to permit mutually recursive functions in local scopes. The body of the declared function may be provided later on by redefinition using a similar argument pattern. For example, after the declaration shown in example above, you can provide a definition like -
 (define (f x y) (+ (* x x) (* y y)))
or
 (define f (fn (x y) (+ (* x x) (* y y))))
At the definition point, you can use any argument pattern that will match against the declared pattern. So you could have done -
 (define (f a b) (+ (* a a) (* b b)))
which will be accepted. However, if you provide an incompatible argument pattern such as
 (define (f x) (* x x))
, an error message will be shown. If you ignore the error message, the new argument pattern is the one that will take effect. Pattern matching is therefore useful to declare that something is a function without dscribing any of its arguments like this -
 (define f (fn _))
. All argument patterns will match against the _ pattern (or any symbol in its place).
References _muse_process_frame_t::bindings_stack, muse_stack::bottom, fn_define(), MUSE_CODE, MUSE_CONS_CELL, MUSE_DISCARD_DOC, MUSE_DOC, muse_message(), MUSE_NIL, muse_sprintf(), and muse_stack::top.
Referenced by fn_define(), fn_define_extension(), fn_define_override(), and muse_bind_copy_expr().
muse_cell fn_define_extension (muse_env * env, void * context, muse_cell args)
 (define-extension generic-fn-symbol fn-extension)
Obeys the same syntax as define, except that the symbol for extension is expected to be bound to a generic function. Only generic functions can be extended.
"Extension" means that the case presented by the given function is examined after all the preceding cases. So if the extension function has the same argument pattern as any of the preceding cases, will not have any effect on the behaviour of the generic function.
You can also use define instead of define-extension.
See also
gfn, gfn:, define-override
References fn_define().
muse_cell fn_define_override (muse_env * env, void * context, muse_cell args)
 (define-override generic-fn-symbol fn-override)
Obeys the same syntax as define, except that the symbol for extension is expected to be bound to a generic function. Only generic functions can be overridden.
"Override" means that the case presented by the given function is examined before all the preceding cases of the generic function. This means that if an overriding function has the same argument pattern as any preceding case, it'll completely take over and not give the preceding case a chance.
See also
gfn, gfn:, define-extension
References fn_define().
muse_cell fn_set_M (muse_env * env, void * context, muse_cell args)
 (set! symbol value)
Inside a function body or let or case block, it changes the value of the given locally declared symbol. Cannot in general be used to set the value of a global symbol, unless that symbol is, up to this point, undefined.
References muse_expect().
muse_cell fn_setf_M (muse_env * env, void * context, muse_cell args)
 (setf! cell value)
Sets the head of the given cons cell to the given value.
muse_cell fn_setr_M (muse_env * env, void * context, muse_cell args)
 (setr! cell value)
Sets the tail of the given cons cell to the given value.
muse_cell fn_first (muse_env * env, void * context, muse_cell args)
 (first list)
Gets the head of the list, which is the first element.
References muse_head().
muse_cell fn_rest (muse_env * env, void * context, muse_cell args)
 (rest list)
Gets the tail of the list. This is intended to be read as "rest of the list".
References muse_tail().
muse_cell fn_nth (muse_env * env, void * context, muse_cell args)
 (nth n list)
Gets the n-th element of a list.
n is zero based. Returns item at index n in the list. Could be thought of as "skip n, then return head".
References muse_head(), and muse_tail().
muse_cell fn_take (muse_env * env, void * context, muse_cell args)
 (take N ls)
Returns a new list consisting of a maximum of N items of the given list "ls".
References MUSE_NIL.
muse_cell fn_drop (muse_env * env, void * context, muse_cell args)
 (drop N list)
Literally does that - drops N items from the given list and returns a list of the remaining items. Examples -
(drop 0 ls) = ls
(drop 2 ls) = (rest (rest ls))
etc.
Does not create a new list like take does.
References muse_tail().
muse_cell fn_dup (muse_env * env, void * context, muse_cell args)
 (dup arg)
Creates a structural duplicate of the given argument.
References muse_dup().
muse_cell fn_list (muse_env * env, void * context, muse_cell args)
 (list a1 a2 ...)
Returns a list of the given items - the list of items is a copy, though the items refer to the same objects.
Supports the
References fn_list(), muse_add_recent_item(), and muse_eval_list().
Referenced by fn_list(), and fn_read_json().
muse_cell fn_append_M (muse_env * env, void * context, muse_cell args)
 (append! list1 list2 ... listN)
Modifies the tail of list1 to point to list2, tail of list2 to list3 etc. All except listN are modified.
For example -
 (define a (list 1 2 3 4 5))
 (define b (list 10 20 30 40 50))
 (append! a b)
 (print a)
will print
 (1 2 3 4 5 10 20 30 40 50)
References muse_list_append(), and MUSE_NIL.