muSE: Higher order functions
Higher order functions
Functions
muse_cell fn_length (muse_env *env, void *context, muse_cell args)
muse_cell fn_map (muse_env *env, void *context, muse_cell args)
muse_cell fn_join (muse_env *env, void *context, muse_cell args)
muse_cell fn_collect (muse_env *env, void *context, muse_cell args)
muse_cell fn_reduce (muse_env *env, void *context, muse_cell args)
muse_cell fn_slice (muse_env *env, void *context, muse_cell args)
muse_cell fn_find (muse_env *env, void *context, muse_cell args)
muse_cell fn_andmap (muse_env *env, void *context, muse_cell args)
muse_cell fn_ormap (muse_env *env, void *context, muse_cell args)
muse_cell fn_for_each (muse_env *env, void *context, muse_cell args)
muse_cell fn_transpose (muse_env *env, void *context, muse_cell args)
muse_cell fn_datafn (muse_env *env, void *context, muse_cell args)
Detailed Description
Function Documentation
muse_cell fn_length (muse_env * env, void * context, muse_cell args)
(size obj) or (length obj)
Returns the size of the given list (i.e. its length) or vector (same as vector-length) or hashtable (same as hashtable-size).
Supports the.
References fn_length(), muse_add_recent_item(), MUSE_CONS_CELL, MUSE_NIL, and muse_monad_view_t::size.
Referenced by fn_length().
muse_cell fn_map (muse_env * env, void * context, muse_cell args)
(map fn obj)
The object can be a list, vector or hashtable and the return value will be of the corresponding type. When the object is a list, the function is expected to take a single argument and provide a mapped value that is collected into Creates a new list whose elements are determined by applying the given function to each argument of the list. For example -
(define squares (map (fn (x) (* x x)) (list 1 2 3 4 5)))
(print squares)
will print
(1 4 9 16 25)
map also works with vectors and hashtables. In those cases, it transforms the "values" of those data structures and creates an isomorphic structure with the transformed values.
Supports the.
References fn_map(), muse_monad_view_t::map, MUSE_CONS_CELL, MUSE_NIL, muse_pop_recent_scope(), and muse_push_recent_scope().
Referenced by fn_map().
muse_cell fn_join (muse_env * env, void * context, muse_cell args)
(join [reduction-fn] obj1 obj2 ...)
Joins the given objects, all of which must be of the same type. Objects can be lists, vectors or hashtables.
In the case of lists, the lists are all appended in the given order and a new list that is a concatenation of the given lists results.
In the case of vectors, they are all joined end to end to create a new vector whose length is the sum of the lengths of the individual vectors.
In the case of hashtables, a new hashtable with all the key-value pairs in all the given hashtables is created. If two hashtables contain the same key, the value stored in the later specified hashtable takes precedence over the value stored in an earlier one. The join function optionally accepts a reduction function as its first argument. When such a function is given, it is used to combined the values associated with the same key in multiple hashtables. If for a given key K the hashtables has values V1, V2, ... VN, then the result hashtable will have the value R(..R(R(V1, V2), V3)...,VN) where R is the reduction function.
Supports the.
References fn_join(), muse_monad_view_t::join, muse_add_recent_item(), MUSE_CONS_CELL, muse_eval_list(), and MUSE_NIL.
Referenced by fn_join().
muse_cell fn_collect (muse_env * env, void * context, muse_cell args)
(collect obj predicate mapper [reduction-fn])
EXPERIMENTAL Intended for more general iteration over the collection objects. The obj is either a list or a vector or a hashtable.
The predicate is a function that selects items from the object. For lists, the predicate is a f(x) where x is a list item. For vectors, the predicate is a f(i . x) where i is the index and x is the value of the vector at the index. For hashtables, the predicate is a f(k . v) where k is a key and v its corresponding value in the hashtable.
The mapper is a function that transforms items into other items. For lists, the mapper is a f(x) where x is a list item. For vectors, the mapper is a f(i . x) where i is the index and x is the value at the index. The result is expected to be a similar (j . y) pair. The result vector is automatically resized to fit the result indices. For hashtables, the mapper is a f(k . v) where k is a key and v is its corresponding value in the hashtable. Similar to vectors, the mapper has to evaluate to a (k' . v') pair that will be placed into the result hashtable.
The optional reduction-fn is a f(v1 v2) that is used to combined multiple values that may be assigned to the same index or key in the cases of vectors and hashtable respectively. If the reduction function is not specified, f(v1 v2) = v2 is used as the function - i.e. replacement.
Supports the.
References muse_monad_view_t::collect, fn_collect(), MUSE_CONS_CELL, MUSE_NIL, muse_pop_recent_scope(), and muse_push_recent_scope().
Referenced by fn_collect().
muse_cell fn_reduce (muse_env * env, void * context, muse_cell args)
(reduce fn initial obj)
Reduces the values of the given collection obj using the given reduction function and the initial value. You can use it with lists, vectors and hashtables. The reduction occurs only over the values of the collection. Indices (in the case of vectors) and keys (in the case of hashtables) are not touched at all.
For convenience, the reduction function is expected to be associative and commutative. If the function isn't so, then know that the first argument of the function is the accumulator. i.e.
(reduce f init (list 1 2 3 4 5))
will give you -
(f (f (f (f (f init 1) 2) 3) 4) 5)
Supports the.
References fn_reduce(), MUSE_CONS_CELL, MUSE_NIL, muse_pop_recent_scope(), muse_push_recent_scope(), and muse_monad_view_t::reduce.
Referenced by fn_reduce().
muse_cell fn_slice (muse_env * env, void * context, muse_cell args)
(slice collection [from count step])
Copies a portion of the collection into a new collection of the same type. The starting zero-based index is given by from, the number of items to copy is given by count (must be > 0 for non-empty collection) and the iteration step is given by step which can be +ve or -ve.
The range specified by from/count/step can be outside the range of available indices in the collection, in which case the range is shortened to whatever index range is possible.
Currently slicing is supported for lists and vectors.
Note that this is an "eager evaluation" optimization. You can also achieve slicing for vectors and hashtables by creating a new collection and setting a datafn on it, which will do the same thing lazily.
References fn_slice(), MUSE_CONS_CELL, muse_eval_list(), MUSE_NIL, muse_pop_recent_scope(), muse_push_recent_scope(), muse_raise_error(), and muse_monad_view_t::slice.
Referenced by fn_slice().
muse_cell fn_find (muse_env * env, void * context, muse_cell args)
(find item collection) -> reference
find can be used to locate an object in a list, vector or hashtable. It uses muse_equal() to determine whether an object is present in the collection.
When used with a list as the collection, it evaluates to the sublist with the given object at the head - or () if the object is not present in the list.
When used with a vector, it evaluates to the index of the object in the vector if it is present in the vector, or to () if it isn't.
When used with a hashtable, it evaluates to the key for which the object is the value in the hashtable. If the object isn't there, it evaluates to ()/
List example -
(print "Sub list = " (find 5 (list 1 2 3 4 5 6 7 8)))
(print "Vector pos = " (find 5 (vector 1 2 3 4 5 6 7 8)))
will print
Sub list = (5 6 7 8)
Vector pos = 4
Supports the.
References fn_find(), MUSE_NIL, muse_pop_recent_scope(), and muse_push_recent_scope().
Referenced by fn_find().
muse_cell fn_andmap (muse_env * env, void * context, muse_cell args)
(andmap predicate collection)
Evaluates the predicate on each element of the collection. The collection can be a list, vector or a hashtable. Returns T if everything satisfied the predicate and () if even one element didn't satisfy the predicate. If an element didn't satisfy the predicate, andmap does not evaluate the predicate on subsequent elements.
The predicate is a fn(x) and is given the value objects in lists, vectors or hashtables.
Supports the.
References _t, fn_andmap(), muse_add_recent_item(), MUSE_NIL, muse_pop_recent_scope(), and muse_push_recent_scope().
Referenced by fn_andmap().
muse_cell fn_ormap (muse_env * env, void * context, muse_cell args)
(ormap predicate collection)
Evaluates the predicate on each element of the collection. The collection can be a list, vector or a hashtable. Returns T if anything satisfied the predicate and () if nothing did. If any one element satisfied the predicate, then ormap does not evaluate the predicate on the other elements of the list.
The predicate is a fn(x) and is given the value objects in lists, vectors or hashtables.
Supports the.
References fn_ormap(), muse_add_recent_item(), MUSE_NIL, muse_pop_recent_scope(), and muse_push_recent_scope().
Referenced by fn_ormap().
muse_cell fn_for_each (muse_env * env, void * context, muse_cell args)
(for-each collection fn [result])
Same as fn_map(), but doesn't collect results. The collection can be a list, vector or a hashtable. You can optionally give a result expression which will be used as the result of the for-each expression.
The operation is a fn(x) and is given the value objects of lists, vectors or hashtables.
References fn_for_each(), MUSE_NIL, and muse_pop_recent_scope().
Referenced by fn_for_each().
muse_cell fn_transpose (muse_env * env, void * context, muse_cell args)
(transpose ...lists...)
Treats the given lists like the rows of a matrix, transposes the lists and returns a list of the rows of the transposed matrix.
For example -
(transpose '(1 2 3) '(4 5 6)) => '((1 4) (2 5) (3 6))
(transpose '(1 4) '(2 5) '(3 6)) => '((1 2 3) (4 5 6))
Not exactly a HOF, but it can be put to good use to implement arbitrary argument mapping like this -
(define map* (fn (f . args) (map (fn (x) (apply f x)) (apply transpose args)))
You can use map* as follows -
(print (map* + (list 1 2 3 4) (list 10 20 30 40)))
which is equivalent to
(print (list (+ 1 10) (+ 2 20) (+ 3 30) (+ 4 40)))
i.e. the result will be -
(11 22 33 44)
Supports the.
References fn_transpose(), muse_add_recent_item(), muse_eval_list(), muse_generate_list(), and MUSE_NIL.
Referenced by fn_transpose().
muse_cell fn_datafn (muse_env * env, void * context, muse_cell args)
(datafn [vector|hashtable] (fn ([key|index]) ...body...))
Establishes that the entries in the vector or the hashtable should be determined by the given function. The function is only computed on demand.
Example:
> (define fibs (vector 0 1))
> (datafn fibs (fn (i) (+ (fibs (- i 1)) (fibs (- i 2)))))
> (fibs 20)
6765
> fibs
{vector 0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765}
Or with a hashtable -
> (define fibs (mk-hashtable))
> (datafn fibs (fn (i) (+ (fibs (- i 1)) (fibs (- i 2)))))
> (fibs 0 0)
0
> (fibs 1 1)
1
> (fibs 10)
55
> fibs
{hashtable '((7 . 13) (6 . 8) (5 . 5) (4 . 3) (2 . 1) (3 . 2) (1 . 1) (9 . 34) (0 . 0) (10 . 55) (8 . 21))}
References muse_message(), and MUSE_NIL.