muSE: Core language
Core language
Functions
muse_cell fn_quote (muse_env *env, void *context, muse_cell args)
Quotes the given arguments without evaluating them.
muse_cell fn_lazy (muse_env *env, void *context, muse_cell args)
muse_cell fn_cons (muse_env *env, void *context, muse_cell args)
(cons head tail).
muse_cell fn_lcons (muse_env *env, void *context, muse_cell args)
(lcons a b)
muse_cell syntax_lambda (muse_env *env, void *context, muse_cell args)
muse_cell syntax_block (muse_env *env, void *context, muse_cell args)
muse_cell syntax_generic_lambda (muse_env *env, void *context, muse_cell args)
(gfn formal-args body)
muse_cell syntax_generic_block (muse_env *env, void *context, muse_cell args)
(gfn: formal-args body)
muse_cell syntax_let (muse_env *env, void *context, muse_cell args)
(let <variable-bindings> <body>).
muse_cell syntax_case (muse_env *env, void *context, muse_cell args)
(case object <match-cases>).
muse_cell fn_apply (muse_env *env, void *context, muse_cell args)
(apply fn arglist).
muse_cell fn_apply_w_keywords (muse_env *env, void *context, muse_cell args)
The counterpart of call/keywords that applies a function to an a-list of key-value pairs.
muse_cell fn_eval (muse_env *env, void *context, muse_cell args)
muse_cell fn_call_w_keywords (muse_env *env, void *context, muse_cell args)
muse_cell fn_callcc (muse_env *env, void *context, muse_cell args)
muse_cell fn_the (muse_env *env, void *context, muse_cell args)
muse_cell fn_meta (muse_env *env, void *context, muse_cell args)
Returns an object containing meta information about the given function.
muse_cell fn_trace (muse_env *env, void *context, muse_cell args)
muse_cell fn_with_recent (muse_env *env, void *context, muse_cell args)
muse_cell fn_symbol_whose_value_is (muse_env *env, void *context, muse_cell args)
Detailed Description
Function Documentation
muse_cell fn_quote (muse_env * env, void * context, muse_cell args)
Quotes the given arguments without evaluating them.
For example,
(quote . hello)
is identical to
'hello
Referenced by muse_bind_copy_expr().
muse_cell fn_lazy (muse_env * env, void * context, muse_cell args)
(lazy fn arg1 arg2 ...)
Delays the application of the given function to the given arguments. Each argument is itself evaluated right away before encapsulating the function call as a lazy application.
Since native function calls are not tail call optimized, you can use lazy to make a delayed tail call to the function.
For reading such an expression, think of the "lazy" as a tag that marks the remainder of the expression as lazy, rather than an operator applied to its arguments. The meaning of a (lazy f a1 a2 ..) expression is exactly the same as (f a1 a2 ...) except that the application is not performed immediately. Note that (lazy f) is the same as (f).
See Also
lcons
References muse_eval_list(), and MUSE_LAZY_CELL.
muse_cell fn_cons (muse_env * env, void * context, muse_cell args)
(cons head tail).
Creates a new cons cell with the given head and tail. If no free cells are available, invokes the garbage collector and grows the heap if necessary.
See Also
_cons()
muse_cell fn_lcons (muse_env * env, void * context, muse_cell args)
(lcons a b)
A "lazy" version of (cons a b) where the a and b are expressions that are not immediately evaluated. They'll be evaluated when their values are required - i.e. when you do a (first ...) or (rest ...) invocation on the resultant cons cell.
Any operation that accesses the head or tail of a lazy cons cell will force the evaluation. Such operations include printing out the list, calling nth, take, drop, etc.
For example -
> (define (numsfrom N) (lcons N (numsfrom (+ N 1))))
> (take 10 (numsfrom 100))
(100 101 102 103 104 105 106 107 108 109)
See Also
lazy
cons
muse_cell syntax_lambda (muse_env * env, void * context, muse_cell args)
(fn formal-args ...body...)
Common syntax -
(fn (x1 x2 ... xN)
  expr1
  expr2
  ...
  result-expr)
fn creates a closure when it is executed. A closure is a copy of the body of the lambda with all non-parameter variables bound to their current values. If an undefined symbol (free variable) is used in the body, it will simply evaluate to itself. Once the symbol is defined after the creation of the closure, the defined value will take the place of the symbol in the closure.
For example -
(define norm3 (fn (x y z) (sqrt (+ (* x x) (* y y) (* z z)))))
defines the symbol norm3 to be a function that computes the norm (i.e. vector-length) of a 3-vector. You use the function in expressions like the following -
(norm3 3 4 0)
(norm3 10 20 30)
Binding formals -
Argments to a function are given as a list. Therefore a function may accept a variable number of arguments, computing different (but hopefully related) values in the different cases. The mechanism using which a function accesses its entire argument list is more general than purely for that case, though.
The arguments to the norm3 function in the above examples may be considered to be lists like
(10 20 30)
. In order to obtain the argument list, simply drop the function position. It is now easy to see that the formal argument pattern
(x y z)
is similar to the given argument list and a one-to-one mapping can be established between the symbols x, y and z in the formals list and the values in the arguments list. This is how the matching and binding is done.
In order to illustrate the matching method, let us write the norm3 argument list in its canonical form - as
(10 . (20 . (30 . ())))
. The formals pattern can also be written in such a canonical form - as
(x . (y . (z . ())))
.
Note
The binder lets a symbol to be bound to either the head or the tail of any cons cell in the argument list. Anything other than a symbol in the formals pattern must match the argument position exactly.
Therefore if you simply use one symbol as the formals specification (ex: args), it will be bound to the entire argument list. If you use a pattern like
(x . xs)
, x will be bound to the first argument 10 and xs will be bound to the first cons cell's tail, i.e. the list
(20 30)
. It is valid for a symbol to be bound to (), but it is not valid to deconstruct a () value and assign its components to symbols. i.e. () will not match against (x . xs) but will match against xs.
See Also
muse_bind_formals()
syntax_let
syntax_case
muse_cell syntax_block (muse_env * env, void * context, muse_cell args)
(fn: (arg1 arg2 ...) ...body...)
Very similar to syntax_lambda, except that it doesn't create a closure. All the free variables in the block (i.e. those except the given arguments) are expected to be bound by the environment in which the block is invoked. Otherwise a block is identical to syntax_lambda and can be used in all places a closure can be used.
In particular, a block is effective with call/cc to specify jump out points such as exceptions and loop breaks. A normal closure can be used as well, but the closure will be repeatedly created every time the call/cc expression is evaluated.
Creating a block is extremely cheap compared to creating a closure using syntax_lambda. As a thumb rule, blocks are equivalent to closures when they are consumed within the scope of their declaration - as in the following example -
(map (fn: (x) (* x 2)) '(1 2 3 4 5))
The above code evaluates to the list
(2 4 6 8 10)
and fn: in this case is equivalent to using fn.
If you define a symbol to a block, then you need to be careful, because the value of any free variables (non-local) used within the block can be redefined outside the block. For example -
(define y 2)
(define double (fn: (x) (* x y)))
(double 3)
    -> 6
(double 5)
    -> 10
(define y 3)
(double 3)
    -> 9
(define y 100)
(double 3)
    -> 300
whereas the same sequence with "fn" instead will be -
(define y 2)
(define double (fn (x) (* x y)))
(double 3)
    -> 6
(double 5)
    -> 10
(define y 3)
(double 3)
    -> 6
(define y 100)
(double 3)
    -> 6
because fn "captures" the value of y at the time it is invoked to create a closure. It is the closure thus created which is bound to the symbol "double".
References MUSE_LAMBDA_CELL.
Referenced by muse_bind_copy_expr(), and syntax_generic_block().
muse_cell syntax_generic_lambda (muse_env * env, void * context, muse_cell args)
(gfn formal-args body)
gfn creates a generic function that can be extended or overridden using define-extension and define-override. You can define generic functions as well as macros.
See Also
gfn:
References syntax_lambda().
Referenced by muse_bind_copy_expr().
muse_cell syntax_generic_block (muse_env * env, void * context, muse_cell args)
(gfn: formal-args body)
gfn: creates a generic function that can be extended or overridden using define-extension and define-override. This version is similar to gfn, but uses dynamic scoping in its body.
See Also
gfn
References syntax_block().
Referenced by muse_bind_copy_expr().
muse_cell syntax_let (muse_env * env, void * context, muse_cell args)
(let <variable-bindings> <body>).
Syntax -
(let ((pattern1 value1)
      (pattern2 value2)
      ...
      (patternN valueN))
  expr1
  expr2
  ...
  result-expr)
let introduces local variables bound to the results of given expressions in the context of a block of code. For example, an expression to compute the distance between two points (x1,y1) and (x2,y2) can be written as -
(let ((dx (- x2 x1))
      (dy (- y2 y1)))
  (print "Computing distance between two points ...")
  (sqrt (* dx dx) (* dy dy)))
The above code introduces the symbols dx and dy bound to x2-x1 and y2-y1 respectively, in the expression (sqrt (* dx dx) (* dy dy)).
The result of the let expression is the result of the last expression in the body. In the above example, the last statement computes the sqrt.
The variable binding scheme in let is exactly the same as the argument binding scheme for lambdas. This means, you can decompose lists using let expressions as follows -
(let (((x y . xs) things))
   (print "x = " x ", y = " y ", and the rest are " xs))
If things is the list (1 2 3 4), the above expression will print
x = 1, y = 2, and the rest are (3 4)
If any of the binding operations failed, the let block is not evaluated and the result is ().
See Also
muse_bind_formals()
syntax_lambda
syntax_case
References MUSE_NIL.
Referenced by muse_bind_copy_expr().
muse_cell syntax_case (muse_env * env, void * context, muse_cell args)
(case object <match-cases>).
Syntax -
(case object
      (match-expr1 result1)
      (match-expr2 result2)
      ...
      (T else-result))
Like switch in C, but way more expressive. The result of a case expression is the result corresponding to the match-expr that succeeded in a match-bind operation against the given object.
In the simplest case, when object is a symbol, you can use case like switch as follows -
(case object
      ('one "One a penny")
      ('two "Two a penny")
      ('what "Hot cross buns"))
The match expressions are not limited to constants and are basically the same as the binding expressions for let or lambda. For example, here is a case expression to print the head of a list -
(case list-object
      ((x . xs) (print "Head of " list-object " is " x "."))
      (() (print "Cannot take head of the empty list!")))
In the above code, the first match expression (x . xs) is bound against the given list-object. If list-object is a non-empty list, this bind operation will succeed and x will be bound to the head of the list and xs will be bound to the tail of the list. The second match expression is the empty list which will succeed in matching against another empty list only. So if list-object is the empty list, then the second print statement will be evaluated.
See Also
muse_bind_formals()
syntax_lambda
syntax_let
References muse_add_recent_item(), muse_bind_formals(), MUSE_CONS_CELL, muse_expect(), muse_message(), MUSE_NIL, and syntax_case().
Referenced by muse_bind_copy_expr(), and syntax_case().
muse_cell fn_apply (muse_env * env, void * context, muse_cell args)
(apply fn arglist).
Equivalent to
(eval (cons fn arglist))
. The apply function lets you apply the given function to the given argument list, both of which may be values of other expressions.
For example -
(define one-to-ten '(1 2 3 4 5 6 7 8 9 10))
(print (apply + one-to-ten))
The above code will print the sum of numbers from 1 to 10, and is equivalent to
(print (+ 1 2 3 4 5 6 7 8 9 10))
.
muse_cell fn_apply_w_keywords (muse_env * env, void * context, muse_cell args)
The counterpart of call/keywords that applies a function to an a-list of key-value pairs.
(define f (fn (x y) (if (< x y) x y)))
(define args '((x . 15) (y . 30)))
(apply/keywords f args)
will evaluate to 15.
References MUSE_LAMBDA_CELL, muse_message(), MUSE_NATIVEFN_CELL, MUSE_NIL, and yield_process().
muse_cell fn_eval (muse_env * env, void * context, muse_cell args)
(eval s-expr)
Evaluates the given single s-expression and returns the result. For example,
(eval '(+ 2 3))
will result in 5. In this sense, eval is the counter part of quote.
References muse_eval().
muse_cell fn_call_w_keywords (muse_env * env, void * context, muse_cell args)
(call/keywords f 'key1 val1 'key2 val2 ...)
f is a user defined function (non-native) that has a bunch of named arguments. You can supply values to those named arguments in another order compared to what it was declared with. For example -
(define f (fn (x y) (if (< x y) x y)))
defines the minimum function. You can call this function as follows -
(call/keywords f 'y 15 'x 3)
to get 3 as the answer. Note that all arguments must be specified for the result to make sense. That condition is not checked for. Note that the symbol positions are
Note that although it makes sense to specify all arguments without exception, the behaviour is such that arguments which are unspecified take on the value of the symbol at invocation time. This means you can introduce "default" values using let blocks. For example -
(let ((x 15)) (call/keywords f 'y 30))
will produce 15 as the answer. In this sense,
(call/keywords f 'x 15 'y 30)
is equivalent to
(let ((x 15) (y 30)) (call/keywords f))
. This gives you yet another kind of dynamic scoping behaviour.
If you want to know the function's formal argument list at any time, you can evaluate
(first f)
.
If f is a macro function - i.e. it requires its arguments in an unevaluated form - the expressions in place of values are used without being first evaulated. Note that the symbol positions are always evaluated.
References MUSE_LAMBDA_CELL, muse_message(), MUSE_NATIVEFN_CELL, MUSE_NIL, and yield_process().
muse_cell fn_callcc (muse_env * env, void * context, muse_cell args)
(call/cc (fn (k) ... (k result) ...))
Abbreviation for "call with current continuation", call/cc is an implementation of the scheme recommendation for continuation support. The first and only argument to call/cc is expected to be a function that takes a single argument called the continuation. call/cc will then call this function, supplying the current continuation as the argument.
A brief intro to continuations follows. When evaluating a sub-expression of any expression, the remainder of the computation may be thought of as a function that expects the result of the sub-expression evaluation. This "remainder of the computation" function w.r.t. the specific sub-expression is called the "continuation" at that point in the evaluation process.
The whole expression may be rewritten as a call to this continuation function with the argument as the result of the sub-expression under consideration. Note that the continuation function does not return a value to the context in which it is called. Instead, it "breaks out" of the context and pretends as though the result of the sub-expression is the argument supplied to the continuation function at invocation time.
Its time for an example - what'll the following code print? .. and then, what'll it print when bomb is defined to T instead?
(define bomb ())
(print (+ 1 2 (call/cc (fn (k)
                         (print "before\n")
                         (if bomb (k 0))
                         (print "after\n")
                         3))
         4 5))
When bomb is (), the
(k 0)
part is not evaluated due to the if condition failing. Therefore the output will be -
before
after
15
When bomb is changed to T, the if block will kick in and
(k 3)
will be evaluated. But since continuation functions do not return to te point of invocation, but to the point of the call/cc which captured them, the
(print "after\n")
expression never gets evaluated and the result of the call/cc block is not 3 as one would expect, but 0, because that's the argument given to the continuation function when it is invoked! So you'll get
before
12
as the result printed to the screen. Note that we know that the continuation invocation did not return to its invocation point because the expression
(print "after\n")
did not get evaluated.
Continuations are rather powerful. The can be used to implement language constructs such as -
try-catch style exception handling,
breaking out of loops.
suspend and resume mechanism.
In general, it should be possible to store away the continuation function for future invocation. Early on in muSE's development, only a limited implementation of call/cc was put in in order to support breaking out of loops. Later on a full implementation of continuations was added. Now, you can store away the continuation function in a variable and invoke it as many times as you need to, because the continuation captures a complete snapshot of the execution environment at the time it is created.
Todo:
The current implementation of call/cc seems to be working properly on Windows + Intel, but doesn't work correctly on PowerPC. Needs investigation.
References MUSE_NIL.
muse_cell fn_the (muse_env * env, void * context, muse_cell args)
(the recent-key)
Looks up the given recent-key to access the result of a recently done computation. Some builtin functions add their results to the recent list as do all user-defined functions. The recent list length is 8. This roughly matches the level at which readability begin to suffer instead of improving.
Here is a trivial example for illustration - a function that computes (a+b)/(a-b).
> (define (add a b) (+ a b))
> (define (sub a b) (- a b))
> (define (h a b)
   (add a b)
   (sub a b)
   (/ (the add) (the sub)))
> (h 5 2)
2.333333
> (the h)
2.333333
Note
The add and sub recent results are not accessible to the caller of h. Evaluating
(the add)
after evaluating
(h 5 2)
will result in a "recent item not found" message box. This is a very important property of the - its ability to restrict the scope of the recent computations to the scope of user defined functions so that callers can access the results of their function evaluations rather than those made by the functions they evaluate.
Here is another contrived one -
(if (find x some-list)
   (length (the find))
   (raise 'FindFailed x))
The above example is clearer using the and without it, you might have to write -
(let ((result (find x some-list)))
   (if result
      (length result)
      (raise 'FindFailed x)))
which introduces a new name result into the code, besides adding a level of nesting for the purpose. The the primitive therefore reduces the need to introduce new temporary names into the code by allowing you to refer to recent computation results using the function that computed it as the key. As in the trivial
(h a b)
example above, it allows you to reduce the level of nesting as well.
the and it
Within a given scope, the reserved symbol "it" can be used to refer to the most recently evaluated "the" expression. "it" will refer to the most recent "the" expression even if that result has been forgotten in the recent list and can no longer be obtained by re-evaluating the "the" expression. Here's an example -
(if (find x some-list)
   (if (>= (length (the find)) 3)
      (print it)
      (print (the length) "is too short because" it "is less than 3."))
   (raise 'FindFailed x))
Builtins that support the -
length, map, join, collect, reduce,
find, andmap, ormap
transpose
vector, hashtable, list
read, read-bytes, read-xml
open-file
References muse_find_recent_item(), MUSE_IT, muse_message(), MUSE_NATIVEFN_CELL, and MUSE_NIL.
muse_cell fn_meta (muse_env * env, void * context, muse_cell args)
Returns an object containing meta information about the given function.
Even closures have meta information.
muse_cell fn_trace (muse_env * env, void * context, muse_cell args)
(trace on) or (trace off)
References MUSE_ENABLE_TRACE, and MUSE_NIL.
muse_cell fn_with_recent (muse_env * env, void * context, muse_cell args)
(with-recent (fn (...) ... (the thing1) ... it ...))
Converts the function generated by the (fn ...) expression so that its body can close on recent values in the context in which the closure is being created.
Todo:
Infer the use of with-recent depending on the usage pattern of the and it within the body of the function itself. Its quite complicated to do.
References muse_do(), MUSE_LAMBDA_CELL, muse_mk_functional_object(), and MUSE_NIL.
muse_cell fn_symbol_whose_value_is (muse_env * env, void * context, muse_cell args)
(symbol-whose-value-is value)
Looks up the symbol table and gives the symbol which is currently (in dynamic scope) defined to the given value.
References muse_stack::bottom, module_find_symbol_with_value(), muse_functional_object_data(), MUSE_NIL, and muse_stack::size.