muSE: Raising and handling exceptions
Raising and handling exceptions
Modules
Internals
muSE implements an exception mechanism that allows you to normally resume computation from the point where an exception is raised.
Functions
muse_cell syntax_try (muse_env *env, void *context, muse_cell args)
Marks an expression that needs to be protected by exception handlers.
muse_cell fn_raise (muse_env *env, void *context, muse_cell args)
(raise [exception-details])
muse_cell fn_retry (muse_env *env, void *context, muse_cell args)
Similar to raise but does not prepend a resume continuation to the trial condition.
muse_cell syntax_finally (muse_env *env, void *context, muse_cell args)
Detailed Description
Function Documentation
muse_cell syntax_try (muse_env * env, void * context, muse_cell args)
Marks an expression that needs to be protected by exception handlers.
A try block has the following syntax -
(try
     expr
     handler1
     handler2
     ....
)
First it tries to evaluate the given expr. If the expression raised an exception using (raise...), then each of the handlers is tried in turn until one matches. The handlers are evaluated at the time the try block is entered, not when an exception is raised, so for efficiency reasons you should use in-place handlers (using the macro brace facility) which do not refer to the lexical context of the try block if possible and use closures for handlers only when you absolutely need them. If your handlers are predetermined before entering the try block and you only need to evaluate a symbol to get at the handlers, then entering a try block is efficient.
A handler can be a function expression - like (fn args expr) or (fn: args expr). If it is such an expression, each handler is tried in turn until the argument pattern of one of the handlers matches the raised exception. The body of the handler whose arguments matched the exception is evaluated and the result is returned as the result of the try block.
The first argument to the handler is an exception object whose sole purpose is to enable the handler to resume the computation with a given value as the result of the (raise...) expression that raised the exception. The rest of the arguments to a handler are the same arguments that were passed to raise.
Handlers may themselves raise exceptions. The raised exceptions start again from the inner most set of handlers and try to find another handler to match it. This gives you the facility to decide exception handling policies at a level higher than the level that implements the policy. Note that if you raise the same exception pattern captured by the handler, you'll not end up in the same handler again in an infinite loop and blow the stack. The handler invocation is protected from such re-entry. This lets you delegate the exception to an even higher level.
If a handler is not a function object, then its value is used as the value of the try block without further checks. Such a "handler" always succeeds.
If none of the handlers match, then the handlers of the previous enclosing try block are examined.
A handler may choose to resume the computation by invoking the exception object with the desired value that should be returned by the (raise ...) expression.
If continuations are captured in the middle of try blocks, they will automatically include the correct state of the try block nesting because they will capture the correct value of the "{{trap}}" symbol.
It is convenient to use read-time evaluated dynamically scoped function objects as handlers since they cause the least overhead and are usually sufficiently general. For example -
(try
  (do (write "Difference = "
        (if (< a b)
               (- b a)
            (raise 'NotInOrder a b)))
      (write "Product = " (* a b)))
  {fn: (ex 'NotInOrder x y)
          (ex (- x y))})
References muse_try().
muse_cell fn_raise (muse_env * env, void * context, muse_cell args)
(raise [exception-details])
Raises an exception described by the given arguments. Handlers are matched against the pattern of arguments to determine which handler to use to handle the exception. It is useful to use a quoted symbol as the first argument which describes the exception. A handler can then specify the same quoted symbol as its second argument in order to get to handle the exception.
(raise..) evaluates the matching handler without unwinding to the enclosing try block. This means any raised exception can be resumed by invoking the exception object (passed as the first argument to the handler) with the resume value as the argument.
See Also
syntax_try
References muse_eval_list().
muse_cell fn_retry (muse_env * env, void * context, muse_cell args)
Similar to raise but does not prepend a resume continuation to the trial condition.
This is useful to provide alternative inner code paths that can be invoked from an outer level. The argument pattern of an alternative should not expect a resume continuation as the first argument.
While a "raise" expression may evaluate to some value, a "retry" exception never completes evaluation, so it is not meaningful to use its result value for anything.
References muse_eval_list(), muse_message(), MUSE_NIL, MUSE_TRAP_POINT, and remove_process().
muse_cell syntax_finally (muse_env * env, void * context, muse_cell args)
(finally ...block...)
Installs a finalizer for the current trap state. A finally block's body will be captured in a closure and installed as a finalizer thunk. This thunk will be invoked at the point when the immediately enclosing try block completes - normally or abnormally. finally thus provides a cleanup mechanism for resources that might otherwise be left lingering around.
Note that finally is not a clause outside the expression protected by a try, but actually occurs and is evaluated within the protected code block. Therefore it can occur not merely within the syntactic scope of a try expression, but actually anywhere (and any number of times) within the execution scope of the try expression - including any functions called within the expression.
References fn_with_recent(), muse_message(), MUSE_NIL, MUSE_TRAP_POINT, and syntax_lambda().