muSE: Language constructs
Language constructs
Functions
muse_cell syntax_if (muse_env *env, void *context, muse_cell args)
muse_cell syntax_when (muse_env *env, void *context, muse_cell args)
muse_cell syntax_unless (muse_env *env, void *context, muse_cell args)
muse_cell syntax_cond (muse_env *env, void *context, muse_cell args)
cond is the generalization of if-then-else nested blocks.
muse_cell syntax_do (muse_env *env, void *context, muse_cell args)
muse_cell syntax_while (muse_env *env, void *context, muse_cell args)
muse_cell syntax_for (muse_env *env, void *context, muse_cell args)
muse_cell fn_the (muse_env *env, void *context, muse_cell args)
Detailed Description
Function Documentation
muse_cell syntax_if (muse_env * env, void * context, muse_cell args)
 (if cond-expr then-expr else-expr)
Evaluate the cond-expr first. If the cond-expr evaluates to something that's not (), the if expression evaluates to the result of the then-expr. If an else-expr is supplied and the cond-expr evaluated to (), the result will be the evaluation of the else-expr. If no else-expr is supplied and the condition failed to test, then () is the result.
For example -
 (if (= 1 2)
     (print "muSE doesn't know numbers!")
     (print "muSE knows numbers, alright"))
References muse_eval(), MUSE_IT, muse_message(), MUSE_NIL, muse_pop_recent_scope(), and syntax_if().
Referenced by syntax_if().
muse_cell syntax_when (muse_env * env, void * context, muse_cell args)
 (when cond ...body...)
Evaluates cond first. If condition evaluated to non-NIL value, then the body is evaluated just like do and the value of the last expression is the value of the when construct. Otherwise the value is ().
References MUSE_NIL.
muse_cell syntax_unless (muse_env * env, void * context, muse_cell args)
 (unless cond ...body...)
Evaluates cond first. If condition evaluated to (), then the body is evaluated just like do and the value of the last expression is the value of the unless construct. Otherwise the value is ().
References MUSE_NIL.
muse_cell syntax_cond (muse_env * env, void * context, muse_cell args)
cond is the generalization of if-then-else nested blocks.
 (cond
  (test1 result1)
  (test2 result2)
  ...
  (T else))
The above form will first check whether test1 is satisfied. If it is, then the result will be the evaluation of result1. If not, then test2 is checked, and so on. For example -
 (cond
     ((< a b) (print "a < b"))
     ((< a c) (print "a < c, but not b"))
     (T (print "a is >= b and c")))
References MUSE_IT, MUSE_NIL, muse_pop_recent_scope(), and syntax_cond().
Referenced by syntax_cond().
muse_cell syntax_do (muse_env * env, void * context, muse_cell args)
 (do ...expressions...)
Defines an expression block. The result of the do block is the result of the last expression in the block, after evaluating all the expressions in the block in sequence.
Referenced by module_find_symbol_with_value().
muse_cell syntax_while (muse_env * env, void * context, muse_cell args)
 (while bool-expr <body>)
Repeatedly evaluates the body statements as long as the bool-expr expression evaluates to something non-nil.
References muse_message(), and MUSE_NIL.
muse_cell syntax_for (muse_env * env, void * context, muse_cell args)
 (for init-expr cond-expr step-expr body [result-expr])
For-loop must be obvious to all ye C-fans. ex:
 (for (set! i (dup 0)) (< i 1000) (++ i)
  (do (set! j (+ j (* i i)))
      (print j))
  j)
References muse_message(), and MUSE_NIL.
muse_cell fn_the (muse_env * env, void * context, muse_cell args)
 (the recent-key)
Looks up the given recent-key to access the result of a recently done computation. Some builtin functions add their results to the recent list as do all user-defined functions. The recent list length is 8. This roughly matches the level at which readability begin to suffer instead of improving.
Here is a trivial example for illustration - a function that computes (a+b)/(a-b).
 > (define (add a b) (+ a b))
 > (define (sub a b) (- a b))
 > (define (h a b)
    (add a b)
    (sub a b)
    (/ (the add) (the sub)))
 > (h 5 2)
 2.333333
 > (the h)
 2.333333
Note
The add and sub recent results are not accessible to the caller of h. Evaluating
 (the add)
after evaluating
 (h 5 2)
will result in a "recent item not found" message box. This is a very important property of the - its ability to restrict the scope of the recent computations to the scope of user defined functions so that callers can access the results of their function evaluations rather than those made by the functions they evaluate.
Here is another contrived one -
 (if (find x some-list)
    (length (the find))
    (raise 'FindFailed x))
The above example is clearer using the and without it, you might have to write -
 (let ((result (find x some-list)))
    (if result
       (length result)
       (raise 'FindFailed x)))
which introduces a new name result into the code, besides adding a level of nesting for the purpose. The the primitive therefore reduces the need to introduce new temporary names into the code by allowing you to refer to recent computation results using the function that computed it as the key. As in the trivial
 (h a b)
example above, it allows you to reduce the level of nesting as well.
the and it
Within a given scope, the reserved symbol "it" can be used to refer to the most recently evaluated "the" expression. "it" will refer to the most recent "the" expression even if that result has been forgotten in the recent list and can no longer be obtained by re-evaluating the "the" expression. Here's an example -
 (if (find x some-list)
    (if (>= (length (the find)) 3)
       (print it)
       (print (the length) "is too short because" it "is less than 3."))
    (raise 'FindFailed x))
Builtins that support the -
length, map, join, collect, reduce,
find, andmap, ormap
transpose
vector, hashtable, list
read, read-bytes, read-xml
open-file
References muse_find_recent_item(), MUSE_IT, muse_message(), MUSE_NATIVEFN_CELL, and MUSE_NIL.