muSE: Cryptographic hashes
Cryptographic hashes
Functions
muse_cell fn_sha1_hash (muse_env *env, void *context, muse_cell args)
muse_cell fn_md5_hash (muse_env *env, void *context, muse_cell args)
Detailed Description
Function Documentation
muse_cell fn_sha1_hash (muse_env * env, void * context, muse_cell args)
 (sha1-hash [bytes|port|string])
Gives a 40-character hex string representation of the sha1 hash of the given bytes.
See http://en.wikipedia.org/wiki/SHA_hash_functions#SHA-1_pseudocode for the algorithm. The code below is basically a C implementation of whats given there.
References muse_add_recent_item(), muse_functional_object_data(), muse_mk_text(), MUSE_NIL, muse_port(), muse_raise_error(), MUSE_TEXT_CELL, muse_text_contents(), muse_unicode_to_utf8(), muse_utf8_size(), port_eof(), and port_read().
Referenced by fn_md5_hash().
muse_cell fn_md5_hash (muse_env * env, void * context, muse_cell args)
 (md5-hash [bytes|port|string])
Gives a 32-character hex string representation of the md5 hash of the given bytes.
See http://en.wikipedia.org/wiki/MD5#Pseudocode for the algorithm. The code below is basically a C implementation of whats given there.
References fn_sha1_hash(), muse_add_recent_item(), muse_functional_object_data(), MUSE_NIL, muse_port(), muse_raise_error(), MUSE_TEXT_CELL, muse_text_contents(), muse_unicode_to_utf8(), and muse_utf8_size().