muSE: Algorithms
Algorithms
Functions
muse_cell fn_sort_inplace (muse_env *env, void *context, muse_cell args)
muse_cell fn_sort (muse_env *env, void *context, muse_cell args)
Just like fn_sort_inplace(), except that the original list is not modified.
muse_cell fn_reverse (muse_env *env, void *context, muse_cell args)
muse_cell fn_reverse_inplace (muse_env *env, void *context, muse_cell args)
Detailed Description
Function Documentation
muse_cell fn_sort_inplace (muse_env * env, void * context, muse_cell args)
(sort! list [propertyFn])
Sorts a list in place according to an optional property function. The first argument is the list of objects to sort. The cells in the list are replaced with the same objects in sorted order. The usual object ordering is used, which will sort a numeric list in ascending order.
A propertyFn can be specified to control the sorting order. The ordering of two objects in the list is determined by the ordering of the objects resulting from the application of the property function to the list objects.
This method is not as flexible as giving a comparator function, but it is good enough for most purposes in a scripting language and is more efficient than giving a comparator function. For example, if you want to sort a numeric list in descending order instead of ascending order, you can write -
(sort! ls -)
instead of
(sort! ls)
If the list consists of lists, then you can use the propertyFn to select an element of the list entries to sort by.
References fn_sort_inplace(), muse_add_recent_item(), and MUSE_NIL.
Referenced by fn_sort_inplace().
muse_cell fn_sort (muse_env * env, void * context, muse_cell args)
Just like fn_sort_inplace(), except that the original list is not modified.
A new list of the same objects in sorted order is returned.
References fn_sort(), muse_add_recent_item(), and MUSE_NIL.
Referenced by fn_sort().
muse_cell fn_reverse (muse_env * env, void * context, muse_cell args)
(reverse list)
Evaluates to a list with items in the reverse order of the given list. The given list is not modified.
References fn_reverse(), muse_add_recent_item(), and MUSE_NIL.
Referenced by fn_reverse().
muse_cell fn_reverse_inplace (muse_env * env, void * context, muse_cell args)
(reverse! list)
Evaluates to a list with items in the reverse order of the given list. The given list is reversed in-place to conserve memory, therefore the cell given as input is left pointing to the last element of the list. Use
(set! x (reverse! x))
if you want to modify a variable containing a list to its reversed version.
References fn_reverse_inplace(), muse_add_recent_item(), MUSE_NIL, and muse_tail().
Referenced by fn_reverse_inplace().