muSE: Object system
Object system
Functions
muse_cell fn_new (muse_env *env, void *context, muse_cell args)
muse_cell fn_supers (muse_env *env, void *context, muse_cell args)
muse_cell fn_super_invoke (muse_env *env, void *context, muse_cell args)
muse_cell fn_super_invoke_explicit (muse_env *env, void *context, muse_cell args)
muse_cell fn_isa_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_object_p (muse_env *env, void *context, muse_cell args)
Detailed Description
Function Documentation
muse_cell fn_new (muse_env * env, void * context, muse_cell args)
(new supers-list prop1 value1 prop2 value2 ...)
(new supers-list)
(new)
Creates an "object" that you can use for OOP. get gets properties of the object (even if nested) and put sets properties of objects, even if nested. You can use "object" instead of "new" for clarity. They are synonyms.
get searches the object's hierarchy for the property if it is not found in the object itself. put always modifies only the object's own properties, even if nested.
The result of the most recent get or put operation can be obtained using the by giving the property key as the argument. For example -
> (new () 'message "hi there!")
> (get (the object) 'message)
hi there!
> (write (the 'message))
"hi there!"
Using the object in the function position with a method key as the first argument will invoke the corresponding method on the object. The result of the most recent method invocation can be accessed using the by supplying the method key. For example -
> (define o (object () 'task (fn (self) (print "did task") "result")))
> (o 'task)
did task
result
> (write (the 'task))
"result"
You can use super-invoke to call methods defined in the super objects.
You can edit an object's supers list using supers.
Note
Property and method access will be fastest if keyed by a symbol since symbol equality can be tested by an int comparison.
References fn_new(), and muse_add_recent_item().
Referenced by fn_new(), and fn_stats().
muse_cell fn_supers (muse_env * env, void * context, muse_cell args)
(supers object)
Gets the object's supers list.
(supers object supers-list)
Sets the object's supers list to the one given. If you modify the list returned by (supers object), do call (supers object supers-list) to tell the object that its supers list has changed.
Exceptions
error:object-expected Handler format:
(fn (resume 'error:object-expected obj) ...)
Raised if the given thing is not an object. The given "object" is passed to the handler in obj. You can resume by resolving the correct object in the handler.
References fn_supers(), muse_functional_object_data(), MUSE_NIL, and muse_raise_error().
Referenced by fn_supers().
muse_cell fn_super_invoke (muse_env * env, void * context, muse_cell args)
(super-invoke obj 'method-name . args)
Invokes a method definition searching the super list without searching the object's own property list.
Exceptions
error:method-not-found Handler format:
(fn (resume 'error:method-not-found obj methodkey) ...)
Raised when the given method is not found in the super tree. The sole argument is the original method key given. You can resume by passing the expected result of the invocation.
error:object-expected Handler format:
(fn (resume 'error:object-expected obj) ...)
Raised if the given thing is not an object. The given "object" is passed to the handler in obj. You can resume by resolving the correct object in the handler.
References fn_super_invoke(), muse_functional_object_data(), MUSE_NIL, and muse_raise_error().
Referenced by fn_super_invoke().
muse_cell fn_super_invoke_explicit (muse_env * env, void * context, muse_cell args)
(super-invoke* obj supers-list 'method-name . args)
Invokes a method definition searching the given super list without searching the object's own property list.
(super-invoke obj methodkey . args)
is equivalent to
(super-invoke* obj (supers obj) methodkey . args)
Exceptions
error:method-not-found Handler format:
(fn (resume 'error:method-not-found obj methodkey) ...)
Raised when the given method is not found in the super tree. The sole argument is the original method key given. You can resume by passing the expected result of the invocation.
error:object-expected Handler format:
(fn (resume 'error:object-expected obj) ...)
Raised if the given thing is not an object. The given "object" is passed to the handler in obj. You can resume by resolving the correct object in the handler.
References fn_super_invoke_explicit(), muse_functional_object_data(), MUSE_NIL, and muse_raise_error().
Referenced by fn_super_invoke_explicit().
muse_cell fn_isa_p (muse_env * env, void * context, muse_cell args)
(isa? type x)
Compares types. If type and x are of the same non object type, it returns x. If type and x are objects and they both have one common super class, it returns the x. If none of these conditions are satisfied, it returns ().
References muse_functional_object_data(), and MUSE_NIL.
muse_cell fn_object_p (muse_env * env, void * context, muse_cell args)
(object? obj)
Evalutes to obj if it is an object and to () if it isn't.
References MUSE_NIL, muse_functional_object_t::type_info, and muse_functional_object_type_t::type_word.