muSE: Vectors
Vectors
Functional objects
A functional vector is a fixed size array of cells.
Functions
muse_cell fn_vector (muse_env *env, vector_t *v, muse_cell args)
The function that implements vector slot access.
muse_cell fn_vector_to_list (muse_env *env, void *context, muse_cell args)
(vector->list fv [from count step]).
muse_cell fn_mk_vector (muse_env *env, void *context, muse_cell args)
(mk-vector N [datafn]).
muse_cell fn_vector_from_args (muse_env *env, void *context, muse_cell args)
(vector a1 a2 a3 — aN).
muse_cell fn_vector_p (muse_env *env, void *context, muse_cell args)
(vector? fv).
muse_cell fn_vector_length (muse_env *env, void *context, muse_cell args)
(vector-length v).
muse_cell fn_list_to_vector (muse_env *env, void *context, muse_cell args)
(list->vector ls).
MUSEAPI muse_cell muse_mk_vector (muse_env *env, int length)
Creates a new vector object that has enough slots allocated to hold the given number of objects.
MUSEAPI int muse_vector_length (muse_env *env, muse_cell vec)
Returns the number of slots the vector has.
MUSEAPI muse_cell muse_vector_get (muse_env *env, muse_cell vec, int index)
Returns the value occupying the slot at the given 0-based index.
MUSEAPI muse_cell muse_vector_put (muse_env *env, muse_cell vec, int index, muse_cell value)
Replaces the value in the slot at the given index with the new value.
Detailed Description
A functional vector is a fixed size array of cells.
A vector can be used like a function. When given one argument which should be an index, it'll return the vaue of the slot at that index. When given two arguments where the first argument is an index, it sets the slot at the given index to the value determined by the second argument.
Examples -
(define vec (mk-vector 5))
(print (vector-length vec))
     > 5
(vec 3 'three)
(vec 0 'zero)
(vec 1 'one)
(vec 2 'two)
(vec 4 'four)
(print (vec 2))
     > two
(print (vector->list vec))
     > (zero one two three four)
(print (vector->list vec 3 2))
     > (three four)
Function Documentation
muse_cell fn_vector_to_list (muse_env * env, void * context, muse_cell args)
(vector->list fv [from count step]).
Given a functional vector, it returns a list of elements of the vector. If no index range is given, the entire vector is converted into a list. If an index range or step is given, the elements in the range with the given step are converted. The conversion will start with index i and end with index j-1, in steps of step.
References muse_array_to_list().
muse_cell fn_mk_vector (muse_env * env, void * context, muse_cell args)
(mk-vector N [datafn]).
Creates a new vector of length N. All slots in the vector are initially NIL. The returned object is a nativefn (functional object). If vec is the returned object, then
(vec i)
yields the value at the slot i and
(vec i val)
sets the value at the slot i to val and returns val.
Referenced by fn_list_to_vector(), and muse_mk_vector().
muse_cell fn_vector_from_args (muse_env * env, void * context, muse_cell args)
(vector a1 a2 a3 — aN).
Makes an N-length vector from the arguments with the arguments as the initial values. Useful and compact for small vectors.
Supports the.
References fn_vector_from_args(), muse_add_recent_item(), and MUSE_NIL.
Referenced by fn_vector_from_args().
muse_cell fn_vector_p (muse_env * env, void * context, muse_cell args)
(vector? fv).
Returns fv if it is a functional vector. Returns () if it isn't.
References MUSE_NIL.
muse_cell fn_vector_length (muse_env * env, void * context, muse_cell args)
(vector-length v).
Evaluates to the length of the given functional vector.
References muse_vector_length().
muse_cell fn_list_to_vector (muse_env * env, void * context, muse_cell args)
(list->vector ls).
Converts the given list into a vector and returns the vector.
References fn_mk_vector(), muse_head(), MUSE_NIL, and muse_tail().
MUSEAPI muse_cell muse_mk_vector (muse_env * env, int length)
Creates a new vector object that has enough slots allocated to hold the given number of objects.
All slots are initialized to MUSE_NIL.
References fn_mk_vector(), and MUSE_NIL.