muSE: Ports
Ports
Functional objects
Data Structures
struct muse_port_type_t
Defines the Ports protocol.
struct muse_port_buffer_t
Every port is buffered for input as well as output.
struct _muse_port_base_t
The base port type.
Typedefs
typedef struct _muse_port_base_t muse_port_base_t
The base port type.
Functions
muse_cell fn_open_file (muse_env *env, void *context, muse_cell args)
void muse_define_builtin_fileport (muse_env *env)
Adds all file port definitions such as "open-file".
MUSEAPI muse_port_t muse_assign_port (muse_env *env, FILE *f, int mode)
Creates a port definition that you can use to read/write stuff from a given file pointer.
void muse_unassign_port (muse_port_t p)
Unassigns a file port which was earlier assigned using muse_assign_port.
muse_char port_getchar (muse_port_t p)
Reads a unicode character from the port.
muse_char port_putchar (muse_char c, muse_port_t p)
Writes the given unicode character to the port.
muse_char port_ungetchar (muse_char c, muse_port_t p)
Writes back a unicode character to the port buffer.
white_space_t ez_skip_whitespace (muse_port_t f, int line, int col)
Skips all white space and comments following the current stream position in the given stream Returns the column position at which the next non-white space character starts.
MUSEAPI muse_cell muse_pread (muse_port_t f)
Reads the next symbolic expression at the current stream position, ignoring white space and comment lines.
MUSEAPI void muse_pwrite (muse_port_t f, muse_cell sexpr)
Writes the given s-expression to the given stream.
MUSEAPI muse_port_t muse_port (muse_env *env, muse_cell p)
Takes a muSE port represented as a cell and returns the internal port object that it uses.
Pretty print support.
void pretty_printer_indent (muse_port_t p)
void pretty_printer_unindent (muse_port_t p)
void pretty_printer_line_break (muse_port_t f)
void pretty_printer_move (muse_port_t p, int numc)
ezscheme structures
int ez_update_col (muse_port_t f, int ch, int col)
ez_result_t ez_parse (muse_port_t p, int col, muse_boolean is_head)
A scheme to eliminate unnecessary parentheses in code.
muse_cell ez_parse_expr (muse_port_t p)
Ports implementation API
void port_init (muse_env *env, muse_port_base_t *p)
Intended to be called inside a particular port's init function at port creation time.
void port_destroy (muse_port_base_t *p)
Intended to be called inside a particular ports destroy function at port destruction time.
void port_free (muse_port_t p)
Frees the whole port.
int port_getc (muse_port_base_t *p)
Same protocol as the system getc function, but works with the given port.
int port_ungetc (int c, muse_port_base_t *p)
Same protocol as the system ungetc function.
int port_putc (int c, muse_port_base_t *p)
Same protocol as the system putc function.
int port_eof (muse_port_base_t *port)
Returns EOF if the port has reached end of stream.
void port_close (muse_port_base_t *p)
Flushes the port and call's the port's close function to release system resources.
size_t port_read (void *buffer, size_t nbytes, muse_port_base_t *port)
Wraps the port specific read function.
size_t port_write (void *buffer, size_t nbytes, muse_port_base_t *port)
Wraps the port specific write function.
int port_flush (muse_port_base_t *port)
Writes any data pending in the port's output buffer and then calls the port-specific flush function.
muse_char port_getchar (muse_port_base_t *p)
muse_char port_putchar (muse_char c, muse_port_base_t *p)
muse_char port_ungetchar (muse_char c, muse_port_base_t *p)
Detailed Description
Function Documentation
muse_cell fn_open_file (muse_env * env, void * context, muse_cell args)
(open-file "filename.txt" ['for-reading 'for-writing 'binary 'expand-braces 'detect-macros 'trust 'tab-syntax])
Returns a new file port for reading or writing to it. Use read and write with the returned port and when you're done with it, call close. If you use the 'binary flag, then any header that might be present at the start of the file won't be processed. Also, no such header will be written out if you're opening the file for writing.
You can allow brace expansion during reading by passing the
'expand-braces
and macro detection and expansion using the
'detect-macros
flag. The
'trust
flag is an abbreviation for setting both of them. If both are not set, the reader will not execute any code. These flags only affect the port when opened in read mode.
For example -
(let ((f (open-file "output.txt" 'for-writing)))
    (write f '(hello world))
    (close f))
If open-file fails, it raises the
('error:open-file <filename>)
exception. You can resume the exception by
continuing with a different filename,
continuing with () which will cause the port to be in eof state. You can also, of course, abort.
Supports the
Exceptions
error:open-file Handler format:
(fn (resume 'error:open-file path) ...)
Raised when, for some reason, the given path couldn't be opened as a file. The handler can resume by resolving the correct path to use.
References muse_add_recent_item().
Referenced by muse_define_builtin_fileport().
MUSEAPI muse_port_t muse_assign_port (muse_env * env, FILE * f, int mode)
Creates a port definition that you can use to read/write stuff from a given file pointer.
The returned port is only for use by the API when it has a file pointer and must use the port calls such as muse_pread() several times on the same port.
Ports assigned using muse_assign_port must be released using muse_unassign_port.
Parameters
f The file that the new port should read from.
mode A combination of muse_port_mode_bits_t indicating properties of the file port.
References MUSE_PORT_READ, MUSE_PORT_READ_DETECT_MACROS, MUSE_PORT_WRITE, and port_init().
Referenced by fn_generate_documentation(), and muse_load().
void muse_unassign_port (muse_port_t p)
Unassigns a file port which was earlier assigned using muse_assign_port.
Should not be used with other ports.
References MUSE_PORT_WRITE, port_destroy(), and port_flush().
Referenced by fn_generate_documentation(), and muse_load().
void port_init (muse_env * env, muse_port_base_t * p)
Intended to be called inside a particular port's init function at port creation time.
A common API provided to all ports.
Sets up the port's buffers.
A specific port implementation need not implement any buffering scheme because this base implementation automatically provides one.
References _muse_port_base_t::env, MUSE_PRETTY_PRINT, MUSE_TAB_SIZE, _muse_port_base_t::pp_max_indent_cols, and muse_functional_object_t::type_info.
Referenced by muse_assign_port(), and muse_define_builtin_fileport().
void port_destroy (muse_port_base_t * p)
Intended to be called inside a particular ports destroy function at port destruction time.
Destroys the port's buffers.
Referenced by muse_unassign_port(), port_close(), and port_free().
void port_free (muse_port_t p)
Frees the whole port.
Not for use within muSE function implementations. Only for use from C-API.
References port_close(), and port_destroy().
Referenced by fn_with_bytes_as_port().
int port_ungetc (int c, muse_port_base_t * p)
Same protocol as the system ungetc function.
The only difference from the system version is that infinite ungetting is not supported. Only a maximum of 16 characters may be "ungot".
References _muse_port_base_t::env, and MUSE_TAB_SIZE.
Referenced by ez_skip_whitespace(), muse_pread(), and port_ungetchar().
int port_putc (int c, muse_port_base_t * p)
Same protocol as the system putc function.
Flushes the port whenever a '
' character is put.
References _muse_port_base_t::env, and port_flush().
Referenced by fn_http_respond(), fn_reply(), muse_assert_failed(), and muse_mickey().
int port_eof (muse_port_base_t * port)
Returns EOF if the port has reached end of stream.
similar to feof.
Referenced by ez_parse(), ez_parse_group(), ez_parse_list(), fn_eof_p(), fn_read_bytes(), fn_read_line(), muse_mickey(), muse_pload(), and muse_pread().
size_t port_read (void * buffer, size_t nbytes, muse_port_base_t * port)
Wraps the port specific read function.
Any data pending in the input buffer is copied first before requesting the port for more data.
References _muse_port_base_t::env, and port_flush().
size_t port_write (void * buffer, size_t nbytes, muse_port_base_t * port)
Wraps the port specific write function.
Writes any data in the output buffer before calling the port-specific write function. If the buffer can hold all the given data as well, then the port's write function is not called and the given bytes are simply copied to the port buffer.
References _muse_port_base_t::env, and port_flush().
Referenced by fn_generate_documentation(), fn_http_respond(), fn_top_level_handler(), fn_with_bytes_as_port(), fn_write_xml(), muse_assert_failed(), port_putchar(), port_write_force(), and print_handler_choices().
MUSEAPI muse_cell muse_pread (muse_port_t f)
Reads the next symbolic expression at the current stream position, ignoring white space and comment lines.
Parameters
f The port from which the expression is to be read.
References _muse_port_base_t::env, ez_skip_whitespace(), MUSE_ENABLE_OBJC, muse_message(), MUSE_NIL, MUSE_PORT_EZSCHEME, MUSE_PORT_READ_EXPAND_BRACES, muse_pread(), muse_quote(), port_eof(), port_getc(), and port_ungetc().
Referenced by fn_read(), fn_top_level_handler(), muse_pload(), muse_pread(), and muse_repl().
MUSEAPI void muse_pwrite (muse_port_t f, muse_cell sexpr)
Writes the given s-expression to the given stream.
If the expression contains only basic objects such as numbers, lists and symbols, then output of write is suitable to read back by muse_pread(). Otherwise, the only difference between write and print is that write encloses strings in quotes and print doesn't.
Referenced by fn_reply(), fn_top_level_handler(), fn_write(), and print_handler_choices().
MUSEAPI muse_port_t muse_port (muse_env * env, muse_cell p)
Takes a muSE port represented as a cell and returns the internal port object that it uses.
If the given thing is not a port, then it returns NULL.
Referenced by fn_http_respond(), fn_load(), fn_md5_hash(), fn_read_json(), fn_sha1_hash(), and fn_write_json().