muSE: Internals
Internals
Processes
A muSE environment contains a circular list of processes called the "process ring" which it cycles through, spending a bit of attention on each process before switching to the next.
Functions
muse_process_frame_t * create_process (muse_env *env, int attention, muse_cell thunk, void *sp)
Creates a new process and returns a pointer to the frame of the newly created process.
muse_process_frame_t * init_process_mailbox (muse_process_frame_t *p)
A process's mailbox is a linked list whose head gives the pid of the process.
muse_cell process_id (muse_process_frame_t *p)
A function to wrap getting the process ID of a process from the process's frame structure.
muse_boolean prime_process (muse_process_frame_t *process)
Should be called after create_process to get it rolling.
muse_boolean run_process ()
Evaluates a process's thunk in a loop until the thunk evaluates to a non-nil value.
muse_boolean switch_to_process (muse_env *env, muse_process_frame_t *process)
Immediately switches attention to the given process.
muse_boolean procrastinate (muse_env *env)
Goes around the processes list and returns to the same point after one round-robin cycle.
void yield_process (muse_env *env, int spent_attention)
Used by muse_apply() to decrement the attention spent on the current process.
muse_boolean is_main_process (muse_env *env)
Returns MUSE_TRUE if the current process is the main process and MUSE_FALSE otherwise.
muse_boolean remove_process (muse_process_frame_t *process)
Removes the given process from the process ring and marks it as "dead".
muse_cell fn_pid (muse_env *env, muse_process_frame_t *p, muse_cell args)
Used to send asynchronous messages to a process and serves as a process's identifier.
void mark_process (muse_process_frame_t *p)
Marks all references held by the given process.
void free_process (muse_process_frame_t *p)
Frees process data structure memory.
void enter_atomic (muse_env *env)
Enters an atomic block that should be evaluated without switching to another process.
void leave_atomic (muse_env *env)
Leaves the current atomic block that should be evaluated without switching to another process.
void post_message (muse_process_frame_t *p, muse_cell msg)
Appends the given message (which, in general, should include the sending process's pid at the head) to the mailbox of the given process.
void push_timeout (muse_env *env, muse_cell id, muse_int timeout_us)
Adds another level of timeout nesting.
void check_timeout (muse_env *env)
Checks whether any timeout has expired and if so raises an exception to the effect.
void muse_init_recent (recent_t *r, int capacity, int depth)
Initializes the scoped recent calculations data structure.
void muse_clear_recent (recent_t *r)
Frees the scoped recent calculations data structure.
recent_t muse_copy_recent (recent_t *r)
Makes a copy of all the recent info upto the present execution point.
void muse_restore_recent (recent_t *r, recent_t *dest)
Takes a saved "recent" data structure and restores it into the given destination.
void muse_mark_recent_context (muse_env *env, recent_t *r, int ctxt)
Marks all objects remembered in the given recent-scope.
void muse_mark_recent (muse_env *env, recent_t *r)
Marks all objects in the recent data structure.
muse_boolean muse_find_recent_item (muse_env *env, muse_int key, muse_cell *value)
8 recent items are stored indexed by a 64-bit key.
recent_entry_t * muse_find_recent_lazy_item (muse_env *env)
Locates the most recent lazy item in the recents list.
muse_cell muse_add_recent_item (muse_env *env, muse_int key, muse_cell value)
You can add a new "recent" item using this function.
void muse_withdraw_recent_item (muse_env *env)
Moves the most recent item added to the recents list to the end of the list.
void muse_push_recent_scope (muse_env *env)
Enter a scope so that previous recent values are temporarily forgotten.
muse_cell muse_pop_recent_scope (muse_env *env, muse_int key, muse_cell value)
Exit from the scope with a result so that the innards of a computation are forgotten.
int muse_forget_it_temporarily (muse_env *env)
Saves the current value of it and reset it to "it".
Detailed Description
A muSE environment contains a circular list of processes called the "process ring" which it cycles through, spending a bit of attention on each process before switching to the next.
Therefore a process that is not in the ring never gets run and one in the ring will always get a chance to run at some point as long as no process executes infinitely blocking code.
A process's main task is to repeatedly evalaute a thunk until the thunk evaluates to a non-nil value, which is the thunk's way of saying "I'm done". This allows one to run server processes.
Each process gets its own set of stacks (including a C-stack) and its own namespace so symbol definitions made within a process do not affect symbol definitions in other processes.
Function Documentation
muse_process_frame_t* create_process (muse_env * env, int attention, muse_cell thunk, void * sp)
Creates a new process and returns a pointer to the frame of the newly created process.
The new process is initially in the "paused" state. It will not run initially because it is not yet part of the process ring - which is a circular list of processes that the evaluator cycles through in order. Call prime_process() to place a process in the ring.
Parameters
env The environment in which to create the new process.
attention The number of reductions that this process can perform before the evaluator switches to the next process.
thunk The created process is setup to evaluate this thunk in a loop until it evaluates to a non-nil value.
sp You can optionally supply a C stack pointer that points to the base of the stack of the newly created process. When creating the main process structure, this pointer must be NULL.
References _muse_process_frame_t::bindings_stack, muse_stack::bottom, _muse_process_frame_t::cstack, _muse_process_frame_t::current_port, _muse_process_frame_t::locals, muse_init_recent(), MUSE_MAX_SYMBOLS, MUSE_STACK_SIZE, _muse_process_frame_t::recent, muse_stack::size, muse_stack::top, and _muse_process_frame_t::traceinfo.
Referenced by fn_spawn(), and muse_init_env().
muse_process_frame_t* init_process_mailbox (muse_process_frame_t * p)
A process's mailbox is a linked list whose head gives the pid of the process.
Messages are added to the mailbox at the tail of this linked list and popped off for processing at the head.
References fn_pid(), and MUSE_NIL.
Referenced by fn_spawn(), and muse_init_env().
muse_cell process_id (muse_process_frame_t * p)
A function to wrap getting the process ID of a process from the process's frame structure.
The process id is to be found at the head of the given process's mailbox.
Referenced by fn_pid(), fn_spawn(), fn_this_process(), and post_message().
muse_boolean prime_process (muse_process_frame_t * process)
Should be called after create_process to get it rolling.
A newly created process (using create_process()) is not part of the process ring until it is "primed" using this function. A "primed" process is initially in the "virgin" state. When the process is first switched to in switch_to_process(), it comes alive.
Referenced by fn_spawn(), and muse_init_env().
muse_boolean run_process ()
Evaluates a process's thunk in a loop until the thunk evaluates to a non-nil value.
Once the thunk completes evaluation, the process dies and evaluation switches to the next process.
References _muse_process_frame_t::cstack, MUSE_NIL, remove_process(), and muse_stack::size.
Referenced by switch_to_process().
muse_boolean switch_to_process (muse_env * env, muse_process_frame_t * process)
Immediately switches attention to the given process.
If the given process is in the "virgin" state, run_process() is called on it. If the process is in the "paused" state, it checks whether the pause has timed out and if so switches to the process. If the process is still waiting, then it tries all processes in the process ring before giving the process another chance.
Note that switch_to_process() will always return MUSE_TRUE,
i.e. it will either block indefinitely or successfuly switch to the given process.
References _muse_process_frame_t::cstack, muse_elapsed_us(), muse_sleep(), run_process(), and muse_stack::top.
Referenced by fn_receive(), fn_run(), procrastinate(), remove_process(), and yield_process().
muse_boolean procrastinate (muse_env * env)
Goes around the processes list and returns to the same point after one round-robin cycle.
procrastinate() will not switch to the next process if an atomic operation is going on.
References switch_to_process().
muse_boolean remove_process (muse_process_frame_t * process)
Removes the given process from the process ring and marks it as "dead".
It then switches to the next process in the ring so that the ring can continue.
References switch_to_process().
Referenced by fn_retry(), and run_process().
muse_cell fn_pid (muse_env * env, muse_process_frame_t * p, muse_cell args)
Used to send asynchronous messages to a process and serves as a process's identifier.
Suppose the message sending expression has the form
(p x1 x2 x3 .. xN)
, where p is the id of the target process, the target process will receive the message in a similar form
(q x1 x2 x3 ... xN)
where q is the id of the sending process. This way the received message has information about the sending process and therefore the receiving process can reply to the sending process. Therefore, a process can receive and process message using pattern matching case expression.
(case (receive)
   ((pid . msg-pattern-1) expr-1)
   ((pid . msg-pattern-2) expr-2)
   ...
   )
It is a useful convention to use a symbolic constant at the head of a message so that it can be explicitly pattern matched against for dispatch. For example -
(case (receive)
  ((pid 'MsgType1 . args) expr-1)
  ((pid 'MsgType2 . args) expr-2)
  ...
  )
References free_process(), muse_doing_gc(), muse_eval_list(), MUSE_NIL, MUSE_T, post_message(), and process_id().
Referenced by init_process_mailbox().
void mark_process (muse_process_frame_t * p)
Marks all references held by the given process.
Called prior to garbage collection.
References _muse_process_frame_t::bindings_stack, _muse_process_frame_t::locals, muse_mark(), muse_mark_recent(), and _muse_process_frame_t::recent.
void enter_atomic (muse_env * env)
Enters an atomic block that should be evaluated without switching to another process.
See Also
leave_atomic()
Referenced by muse_gc(), and syntax_atomic().
void leave_atomic (muse_env * env)
Leaves the current atomic block that should be evaluated without switching to another process.
Atomic blocks can be nested, but must always be matched. Use the syntax_atomic muSE function to mark an atomic do block.
See Also
enter_atomic()
Referenced by muse_gc(), and syntax_atomic().
void post_message (muse_process_frame_t * p, muse_cell msg)
Appends the given message (which, in general, should include the sending process's pid at the head) to the mailbox of the given process.
See Also
fn_post
References MUSE_NIL, and process_id().
Referenced by fn_pid(), and fn_post().
void check_timeout (muse_env * env)
Checks whether any timeout has expired and if so raises an exception to the effect.
The structure of the exception is - ('timeout 'id given-us elapsed-us)
References muse_elapsed_us(), muse_list(), muse_nativefn_context(), muse_raise_error(), MUSE_TIMEOUT, and MUSE_TIMEOUTVAR.
Referenced by yield_process().
void muse_mark_recent_context (muse_env * env, recent_t * r, int ctxt)
Marks all objects remembered in the given recent-scope.
Marks all objects in the recent scope.
References recent_context_t::base, muse_mark(), and recent_context_t::top.
muse_boolean muse_find_recent_item (muse_env * env, muse_int key, muse_cell * value)
8 recent items are stored indexed by a 64-bit key.
You can look up a recent item by giving your key.
References recent_context_t::base, recent_context_t::depth, recent_context_t::prev, and _muse_process_frame_t::recent.
Referenced by fn_the().
muse_cell muse_add_recent_item (muse_env * env, muse_int key, muse_cell value)
You can add a new "recent" item using this function.
Only the 8 most recent items are kept. The return value is value itself.
References recent_context_t::base, recent_context_t::depth, _muse_process_frame_t::recent, and recent_context_t::top.
Referenced by fn_alist_to_hashtable(), fn_andmap(), fn_fetch_uri(), fn_format(), fn_hashtable_to_alist(), fn_http_parse(), fn_image_properties(), fn_join(), fn_length(), fn_list(), fn_list_files(), fn_list_folders(), fn_md5_hash(), fn_new(), fn_open_connection(), fn_open_file(), fn_ormap(), fn_read(), fn_read_bytes(), fn_read_line(), fn_read_xml(), fn_reverse(), fn_reverse_inplace(), fn_sha1_hash(), fn_sort(), fn_sort_inplace(), fn_split(), fn_substring(), fn_temp_file(), fn_temp_folder(), fn_transpose(), fn_vector_from_args(), fn_windows_registry_entry(), muse_force(), muse_pop_recent_scope(), and syntax_case().
void muse_withdraw_recent_item (muse_env * env)
Moves the most recent item added to the recents list to the end of the list.
Removes the most recent item added to the recents list.
References recent_context_t::base, recent_context_t::depth, _muse_process_frame_t::recent, and recent_context_t::top.
int muse_forget_it_temporarily (muse_env * env)
Saves the current value of it and reset it to "it".
Returns the bindings stack pos before saving it.
References MUSE_IT.