muSE: Boxes
Boxes
Functional objects
A box is a container for one object.
Functions
muse_cell fn_box (muse_env *env, box_t *b, muse_cell args)
The function that implements box access.
MUSEAPI muse_cell muse_mk_box (muse_env *env, muse_cell contents)
Creates a new box with the given contents.
MUSEAPI muse_cell muse_box_get (muse_env *env, muse_cell box)
Returns the contents of the given box.
MUSEAPI muse_cell muse_box_set (muse_env *env, muse_cell box, muse_cell contents)
Changes the contents of the given box to the new value.
muse_cell fn_mk_box (muse_env *env, void *context, muse_cell args)
Detailed Description
A box is a container for one object.
You can use the box like a function - sort of like R5RS "properties". If b is a box, the the expression (b) gets the contents of the box. The expression (b val) puts the value into the box and returns the new value.
Function Documentation
MUSEAPI muse_cell muse_mk_box (muse_env * env, muse_cell contents)
Creates a new box with the given contents.
If you pass MUSE_NIL for the contents, it is equivalent to creating an empty box.
References muse_box_set(), and MUSE_NIL.
MUSEAPI muse_cell muse_box_set (muse_env * env, muse_cell box, muse_cell contents)
Changes the contents of the given box to the new value.
Returns the new value.
References muse_message(), and MUSE_NIL.
Referenced by muse_mk_box().
muse_cell fn_mk_box (muse_env * env, void * context, muse_cell args)
(box [contents])
Creates a new box with the given contents. If contents is not given, a new box with () as the contents will be created. A box with () as its contents is considered to be empty.