muSE: Property lists
Property lists
Functions
muse_cell fn_get (muse_env *env, void *context, muse_cell args)
muse_cell fn_put (muse_env *env, void *context, muse_cell args)
muse_cell fn_put_many (muse_env *env, void *context, muse_cell args)
muse_cell fn_assoc (muse_env *env, void *context, muse_cell args)
muse_cell fn_plist (muse_env *env, void *context, muse_cell args)
muse_cell fn_symbol (muse_env *env, void *context, muse_cell args)
muse_cell fn_name (muse_env *env, void *context, muse_cell args)
muse_cell fn_gensym (muse_env *env, void *context, muse_cell args)
Generates an interned anonymous symbol that can be used as a variable in macro generated code.
Detailed Description
Function Documentation
muse_cell fn_get (muse_env * env, void * context, muse_cell args)
 (get thing key)
Looks up the value for the given key in the given thing. The thing can be any key-value association, including objects, hashtables, modules and vectors. Except for vectors which take integer keys, the others are expected to use symbols as keys.
get supports deep lookup.
 (get thing key1 key2 ... keyN).
is equivalent to -
 (get ... (get (get thing key1) key2) ... keyN)
If thing is a value that is being held in a variable, then the notation thing.key1.key2 is equivalent to
 (get thing 'key1 'key2)
.
See also
put
References muse_eval_list(), and muse_get().
muse_cell fn_put (muse_env * env, void * context, muse_cell args)
 (put thing key value)
Sets the value for the given key in the given thing to the given value. thing can be anything that get supports and key also has the same restrictions as for get.
put also supports deep nesting just like get.
 (put thing key1 key2 ... keyN value)
is equivalent to
 (put (get thing key1 key2 ... keyN-1) keyN value)
put supports the dot notation too. For example,
 (put thing.key value)
is equivalent to
 (put thing 'key value)
. (put is actually a macro that expands to this form at read time.)
See also
get
References muse_eval_list(), and muse_put().
muse_cell fn_put_many (muse_env * env, void * context, muse_cell args)
 (put* obj key1 value1 key2 value2 ... keyN valueN)
Sets many properties of the object in one go.
See also
put
get
References muse_equal(), muse_eval(), MUSE_GET, muse_head(), muse_list(), MUSE_NIL, muse_put(), muse_quote(), and muse_tail().
muse_cell fn_assoc (muse_env * env, void * context, muse_cell args)
 (assoc plist key)
See also
muse_assoc()
muse_cell fn_plist (muse_env * env, void * context, muse_cell args)
 (plist symbol)
See also
muse_symbol_plist()
References muse_symbol_plist().
muse_cell fn_symbol (muse_env * env, void * context, muse_cell args)
 (symbol "symbol-name")
Interns the symbol of the given textual name and returns a unique symbol cell.
References muse_symbol().
muse_cell fn_name (muse_env * env, void * context, muse_cell args)
 (name sym)
Returns the text name of the given symbol or () if the given thing is not a symbol or doesn't have a name.
References muse_intern_symbol(), MUSE_NIL, and MUSE_SYMBOL_CELL.
muse_cell fn_gensym (muse_env * env, void * context, muse_cell args)
Generates an interned anonymous symbol that can be used as a variable in macro generated code.
Previously, (before processes) it was possible to use (new) to do the same thing, but after processes were implemented, symbols need be interned before they can be used as variables since any function may be evaluated in multiple processes and it needs to maintain the state of its variables consistently in the process in which it is being evaluated.
References _newlocal, and muse_intern_symbol().