muSE: Byte array
Byte array
Functional objects
A byte array is finite sized sequence of raw byte data.
Functions
muse_cell fn_bytes_fn (muse_env *env, bytes_t *b, muse_cell args)
muse_cell fn_bytes_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_bytes_size (muse_env *env, void *context, muse_cell args)
size_t port_write_force (muse_env *env, unsigned char *buffer, size_t size, muse_port_t p)
Force the entire buffer down the throat of the port.
muse_cell fn_write_bytes (muse_env *env, void *context, muse_cell args)
muse_cell fn_read_bytes (muse_env *env, void *context, muse_cell args)
muse_cell fn_bytes (muse_env *env, void *context, muse_cell args)
muse_cell fn_copy_bytes (muse_env *env, void *context, muse_cell args)
muse_cell fn_string_to_bytes (muse_env *env, void *context, muse_cell args)
muse_cell fn_with_bytes_as_port (muse_env *env, void *context, muse_cell args)
Detailed Description
A byte array is finite sized sequence of raw byte data.
Raw data can be embedded into a muSE text stream using the construct
#11[blahblah...]
. You can also read and write raw byte data from any port using read-bytes and write-bytes. You can access portions of a byte array by using the array object itself as a function (fn_bytes_fn) and copy sections using copy-bytes.
Function Documentation
muse_cell fn_bytes_fn (muse_env * env, bytes_t * b, muse_cell args)
 (bytes-object byte-offset field-type [value])
Retrieves or modifies the data contents of the byte array according to a specified data type spec.
The offset and offset + sizeof(field-type) must be within range. The field-type is one of - 'byte, 'short, 'int, 'long, 'float, 'double. The type names and sizes match the Java specification. If a value is given the byte object is modified at the location. If given, the value must be of the appropriate type - integral for 'byte, 'short, 'int and 'long data types and floating point for 'float and 'double.
The types 'short, 'int and 'long stand for little endian byte order data. If you want to interpret the data as big-endian, use 'Short, 'Int and 'Long instead, respectively.
You can take a slice of a byte array by specifying an offset and a size as follows -
 (bytes-object offset size)
. If you omit the size, a slice is created up to the end of the array from the given offset. The expression evaluates to a new slice object that refers to the original bytes object. Modifying the slice data modifies the original object. You can therefore use slicing to read data to a portion of a byte array from a port using read-bytes.
References muse_cell_type(), MUSE_INT_CELL, muse_mk_text_utf8(), MUSE_NIL, MUSE_SYMBOL_CELL, and muse_symbol_name().
muse_cell fn_bytes_p (muse_env * env, void * context, muse_cell args)
 (bytes? bytes)
Evaluates to bytes if it is a valid byte data object and to () if it isn't one.
References MUSE_NIL.
Referenced by fn_with_bytes_as_port().
muse_cell fn_bytes_size (muse_env * env, void * context, muse_cell args)
 (bytes-size bytes) -> int
Referenced by fn_with_bytes_as_port().
muse_cell fn_write_bytes (muse_env * env, void * context, muse_cell args)
 (write-bytes [port] bytes [start-offset] [num-bytes])
Write the raw byte sequence to the port. If port is omitted, the data goes to stdout. Optional start offset and size can be specified to write a portion of the byte array without having to allocate a new slice object.
References MUSE_NIL, port_eof(), port_read(), and port_write_force().
Referenced by fn_with_bytes_as_port().
muse_cell fn_read_bytes (muse_env * env, void * context, muse_cell args)
 (read-bytes [port] [bytes]) -> bytes
Reads raw bytes from the given port or stdin. If a bytes object is given, it attempts to fill it. If no bytes object is given, it reads from the port until eof and returns a new bytes object containing the data.
Supports the
References muse_add_recent_item(), MUSE_NIL, and port_eof().
Referenced by fn_with_bytes_as_port().
muse_cell fn_bytes (muse_env * env, void * context, muse_cell args)
 (bytes size)
Creates a new uninitialized byte array of the given size.
Referenced by fn_string_to_bytes(), and fn_with_bytes_as_port().
muse_cell fn_copy_bytes (muse_env * env, void * context, muse_cell args)
 (copy-bytes size src src-offset dest dest-offset)
Copies size bytes from src starting at src-offset to the dest buffer starting at dest-offset.
References MUSE_NIL.
Referenced by fn_with_bytes_as_port().
muse_cell fn_string_to_bytes (muse_env * env, void * context, muse_cell args)
 (string->bytes string)
Renders the given unicode string into UTF-8 encoding and returns it as a bytes object.
References fn_bytes(), MUSE_NIL, muse_raise_error(), MUSE_TEXT_CELL, muse_text_contents(), muse_unicode_to_utf8(), and muse_utf8_size().
Referenced by fn_with_bytes_as_port().
muse_cell fn_with_bytes_as_port (muse_env * env, void * context, muse_cell args)
 (with-bytes-as-port bytes (fn (port) ...))
Applies the given function passing it a port object containing the data in the given bytes object. The port argument cannot be used outside the function call.
References muse_functional_object_type_t::fn, fn_bytes(), fn_bytes_p(), fn_bytes_size(), fn_copy_bytes(), fn_read_bytes(), fn_string_to_bytes(), fn_with_bytes_as_port(), fn_write_bytes(), muse_mk_nativefn(), MUSE_NIL, MUSE_PORT_TRUSTED_INPUT, port_free(), port_write(), and muse_functional_object_t::type_info.
Referenced by fn_flush(), fn_load(), and fn_with_bytes_as_port().