muSE: muse.c File Reference
muse.c File Reference
#include "muse_opcodes.h"
#include "muse_builtins.h"
#include "muse_port.h"
#include <stdio.h>
#include <stdlib.h>
#include <wchar.h>
#include <string.h>
#include <sys/time.h>
Functions
MUSEAPI muse_env * muse_init_env (const int *parameters)
Creates a new muse environment.
MUSEAPI void muse_destroy_env (muse_env *env)
Destroys the given environment.
MUSEAPI muse_int * muse_slot (muse_env *env, int slotid)
The environment maintains a fixed number of "slots" which are memory locations of size muse_int that are addressed using a four-character int id.
MUSEAPI void muse_set_slot_cleanup_proc (muse_env *env, int slotid, muse_slot_cleanup_proc_t proc)
Associates a callback function with a slot that will be called when the muSE environment is destroyed.
MUSEAPI muse_cell muse_cons (muse_env *env, muse_cell head, muse_cell tail)
Allocates a new cons cell with the given head and tail cells.
MUSEAPI muse_cell muse_mk_int (muse_env *env, muse_int i)
Allocates a new integer cell to hold the given integer.
MUSEAPI muse_cell muse_mk_float (muse_env *env, muse_float f)
Allocates a new float cell to hold the given integer.
MUSEAPI int muse_stack_pos (muse_env *env)
Returns the current stack position.
MUSEAPI void muse_stack_unwind (muse_env *env, int stack_pos)
Unwinds the stack to the given position.
MUSEAPI muse_cell muse_stack_push (muse_env *env, muse_cell obj)
Saves the given object on the stack so that it will not be garbage collected when gc is next invoked.
MUSEAPI int muse_bindings_stack_pos (muse_env *env)
Gets the current depth of the bindings stack.
MUSEAPI void muse_bindings_stack_unwind (muse_env *env, int pos)
MUSEAPI void muse_trace_push (muse_env *env, const muse_char *label, muse_cell fn, muse_cell arglist)
A mechanism for gathering call trace information.
MUSEAPI void muse_trace_pop (muse_env *env)
MUSEAPI size_t muse_trace_report (muse_env *env, size_t numchars, muse_char *buffer)
Generates a report of the stuff on the trace stack at the point of call.
MUSEAPI muse_cell muse_mk_text (muse_env *env, const muse_char *start, const muse_char *end)
Copies the given text and creates a new text cell to store it.
MUSEAPI muse_cell muse_mk_text_utf8 (muse_env *env, const char *start, const char *end)
Same as muse_mk_text() except that it takes a UTF8 string and converts it into a unicode string and stores it.
MUSEAPI muse_cell muse_mk_ctext (muse_env *env, const muse_char *start)
Same as muse_mk_text() except that it assumes a null terminated string.
MUSEAPI muse_cell muse_mk_ctext_utf8 (muse_env *env, const char *start)
Same as muse_mk_text_utf8() except that it assumes a null terminated string as input.
MUSEAPI muse_cell muse_mk_nativefn (muse_env *env, muse_nativefn_t fn, void *context)
Creates a new cell that stores a C function.
MUSEAPI muse_cell muse_mk_destructor (muse_env *env, muse_nativefn_t fn, void *context)
A destructor is a native function that also gets called with no arguments when the function is garbage collected.
MUSEAPI muse_cell muse_intern_symbol (muse_env *env, muse_cell sym, int local_ix, muse_int hash)
Includes the given symbol in the symbol table and makes its value process-local.
MUSEAPI muse_cell muse_symbol (muse_env *env, const muse_char *start, const muse_char *end)
Returns a reference to a named symbol with the given name.
MUSEAPI muse_cell muse_csymbol (muse_env *env, const muse_char *sym)
Same as muse_symbol(), but takes a c-style null terminated unicode character string.
MUSEAPI muse_cell muse_symbol_utf8 (muse_env *env, const char *start, const char *end)
Same as muse_symbol() except that it takes a UTF8 string.
MUSEAPI muse_cell muse_csymbol_utf8 (muse_env *env, const char *sym)
Same as muse_symbol_utf8() except that it takes a c-style null terminated utf8 string.
MUSEAPI muse_cell muse_builtin_symbol (muse_env *env, muse_builtin_symbol_t s)
Returns a symbol reference corresponding to the given symbol index.
MUSEAPI muse_cell muse_mk_anon_symbol (muse_env *env)
An anonymous symbol is similar to a named symbol, except that it is not stored permanently on the symbol stack.
MUSEAPI void muse_mark (muse_env *env, muse_cell c)
Prior to garbage collection, muse_mark is called on all cells which are referenced somewhere and should not be garbage collected.
MUSEAPI void muse_gc (muse_env *env, int free_cells_needed)
Collects all the garbage cells - i.e.
MUSEAPI muse_boolean muse_doing_gc (muse_env *env)
You can call this to know whether the garbage collection is in progress.
MUSEAPI muse_functional_object_t * muse_create_and_init_object (muse_env *env, muse_functional_object_type_t *type_info, muse_cell init_args)
Just creates an object without allocating a cell for it.
MUSEAPI void muse_destroy_object (muse_env *env, muse_functional_object_t *obj)
Counterpart of muse_create_and_init_object.
MUSEAPI muse_cell muse_mk_functional_object (muse_env *env, muse_functional_object_type_t *type_info, muse_cell init_args)
Creates a new functional object instance based on the given type information.
MUSEAPI muse_functional_object_t * muse_functional_object_data (muse_env *env, muse_cell fobj, int type_word)
Returns the data pointer of the functional object, or NULL if the object is not a functional object.
muse_process_frame_t * create_process (muse_env *env, int attention, muse_cell thunk, void *sp)
Creates a new process and returns a pointer to the frame of the newly created process.
muse_process_frame_t * init_process_mailbox (muse_process_frame_t *p)
A process's mailbox is a linked list whose head gives the pid of the process.
muse_cell process_id (muse_process_frame_t *p)
A function to wrap getting the process ID of a process from the process's frame structure.
muse_boolean prime_process (muse_process_frame_t *process)
Should be called after create_process to get it rolling.
muse_boolean run_process ()
Evaluates a process's thunk in a loop until the thunk evaluates to a non-nil value.
muse_boolean switch_to_process (muse_env *env, muse_process_frame_t *process)
Immediately switches attention to the given process.
muse_boolean procrastinate (muse_env *env)
Goes around the processes list and returns to the same point after one round-robin cycle.
void yield_process (muse_env *env, int spent_attention)
Used by muse_apply() to decrement the attention spent on the current process.
muse_boolean is_main_process (muse_env *env)
Returns MUSE_TRUE if the current process is the main process and MUSE_FALSE otherwise.
muse_boolean remove_process (muse_process_frame_t *process)
Removes the given process from the process ring and marks it as "dead".
muse_cell fn_pid (muse_env *env, muse_process_frame_t *p, muse_cell args)
Used to send asynchronous messages to a process and serves as a process's identifier.
void mark_process (muse_process_frame_t *p)
Marks all references held by the given process.
void free_process (muse_process_frame_t *p)
Frees process data structure memory.
void enter_atomic (muse_env *env)
Enters an atomic block that should be evaluated without switching to another process.
void leave_atomic (muse_env *env)
Leaves the current atomic block that should be evaluated without switching to another process.
void post_message (muse_process_frame_t *p, muse_cell msg)
Appends the given message (which, in general, should include the sending process's pid at the head) to the mailbox of the given process.
void push_timeout (muse_env *env, muse_cell id, muse_int timeout_us)
Adds another level of timeout nesting.
void check_timeout (muse_env *env)
Checks whether any timeout has expired and if so raises an exception to the effect.
void muse_init_recent (recent_t *r, int capacity, int depth)
Initializes the scoped recent calculations data structure.
void muse_clear_recent (recent_t *r)
Frees the scoped recent calculations data structure.
recent_t muse_copy_recent (recent_t *r)
Makes a copy of all the recent info upto the present execution point.
void muse_restore_recent (recent_t *r, recent_t *dest)
Takes a saved "recent" data structure and restores it into the given destination.
void muse_mark_recent_context (muse_env *env, recent_t *r, int ctxt)
Marks all objects remembered in the given recent-scope.
void muse_mark_recent (muse_env *env, recent_t *r)
Marks all objects in the recent data structure.
muse_boolean muse_find_recent_item (muse_env *env, muse_int key, muse_cell *value)
8 recent items are stored indexed by a 64-bit key.
recent_entry_t * muse_find_recent_lazy_item (muse_env *env)
Locates the most recent lazy item in the recents list.
muse_cell muse_add_recent_item (muse_env *env, muse_int key, muse_cell value)
You can add a new "recent" item using this function.
void muse_withdraw_recent_item (muse_env *env)
Moves the most recent item added to the recents list to the end of the list.
void muse_push_recent_scope (muse_env *env)
Enter a scope so that previous recent values are temporarily forgotten.
muse_cell muse_pop_recent_scope (muse_env *env, muse_int key, muse_cell value)
Exit from the scope with a result so that the innards of a computation are forgotten.
int muse_forget_it_temporarily (muse_env *env)
Saves the current value of it and reset it to "it".
Variables
const char * g_muse_typenames []
String names for the various cell types, intended for debugging and reporting use.
Detailed Description
Author
Srikumar K. S. (kumar.nosp@m.@muv.nosp@m.ee.co.nosp@m.m)
Copyright (c) 2006 Jointly owned by Srikumar K. S. and muvee Technologies Pte. Ltd.
All rights reserved. See LICENSE.txt distributed with this source code or http://muvee-symbolic-expressions.googlecode.com/svn/trunk/LICENSE.txt for terms and conditions under which this software is provided to you.
Function Documentation
MUSEAPI muse_cell muse_intern_symbol (muse_env * env, muse_cell sym, int local_ix, muse_int hash)
Includes the given symbol in the symbol table and makes its value process-local.
Note that no check is performed to see whether the symbol is already interned or not.
References muse_stack::bottom, _muse_process_frame_t::locals, MUSE_NIL, muse_raise_error(), MUSE_SYMBOL_CELL, muse_stack::size, and muse_stack::top.
Referenced by fn_gensym(), fn_name(), and muse_symbol().
Variable Documentation
const char* g_muse_typenames[]
Initial value:
=
{
    "MUSE_CONS_CELL",
    "MUSE_LAMBDA_CELL",
    "MUSE_SYMBOL_CELL",
    "MUSE_NATIVEFN_CELL",
    "MUSE_INT_CELL",
    "MUSE_FLOAT_CELL",
    "MUSE_TEXT_CELL",
    "MUSE_LAZY_CELL"
}
String names for the various cell types, intended for debugging and reporting use.
See also
_typename()