muSE: muse_image_info.cpp File Reference
muse_image_info.cpp File Reference
#include "muse_opcodes.h"
#include "muse_port.h"
Functions
muse_cell fn_image_properties (muse_env *env, void *context, muse_cell args)
Detailed Description
Author
Srikumar K. S. (kumar.nosp@m.@muv.nosp@m.ee.co.nosp@m.m)
Copyright (c) 2009 Jointly owned by Srikumar K. S. and muvee Technologies Pte. Ltd.
All rights reserved. See LICENSE.txt distributed with this source code or http://muvee-symbolic-expressions.googlecode.com/svn/trunk/LICENSE.txt for terms and conditions under which this software is provided to you.
Function Documentation
muse_cell fn_image_properties (muse_env * env, void * context, muse_cell args)
(image-properties path-to-image)
Creates an object using which you can access the metadata of the given image file. The returned object supports get.
The metadata can be accessed either by symbolic key or by numeric tag code, as specified in the Microsoft documentation.
Image property tag constants
Image property tag type constants
The symbolic names of the tags are derived from the constant declarations as follows -
A name of the form PropertyTagGpsDestDistRef becomes gps-dest-dist-ref i.e. the PropertyTag prefix is dropped and the camel case is converted into Scheme convention.
For names with abbreviations in them such as PropertyTagJPEGQuality, the lower case form preserves the abbreviation - so PropertyTagJPEGQuality becomes jpeg-quality
YCbCr is also converted into lower case as ycbcr - so PropertyTagThumbnailYCbCrCoefficients becomes thumbnail-ycbcr-coefficients
The following extra properties are also exposed -
'size
{vector width-pixels height-pixels}
'physical-size
{vector physical-width physical-height}
'resolution
{vector hres vres}
'path
"path/to/file.jpg"
Exceptions
image-properties:gdiplus-error
Handler
(fn (resume 'image-properties:gdiplus-error) ...)
When Initializing Gdiplus failed when image-properties function is called.
Consequence Cannot use image-properties feature.
Resume Useless
image-properties:invalid-tag
Handler
(fn (resume 'image-properties:invalid-tag props code/tag) ...)
When A property with an invalid tag is requested. The tag can be numeric or symbolic. If the tag is not a number or a symbol, then this exception means that you have to pass a number or a symbol. props is the properties objects which raised the exception. (i.e. this exception is not raised by image-properties itself, but by the object it returns.)
Consequence Cannot retrieve property.
Resume By passing the expected result.
error:string-expected
Handler
(fn (resume 'error:string-expected alt) ...)
When image-properties is called with a non-path value.
Consequence Cannot read image properties.
Resume By passing a valid string path to file.
image-properties:file-error
Handler
(fn (resume 'image-properties:file-error path) ...)
When There is a problem opening the image file.
Consequence Properties cannot be read.
Resume By passing a path to a valid image.
image-properties:not-supported
Handler
(fn (resume 'image-properties:not-supported) ...)
When The image-properties feature is not available on this platform. Currently (r619) this feature is available only on Win32.
Sample session
; Get properties of an image
> (define p (image-properties "somewhere/something.jpg"))
; Get size
> p.size
{vector 320 240}
; Get physical size
> p.physical-size
{vector 320.0 240.0}
; Get resolution
> p.resolution
{vector 96.0 96.0}
; Get file path
> p.path
somewhere/something.jpg
; Get thumbnail width (PropertyTagThumbnailWidth)
> (p 0x5013)
32
; Get thumbnail width symbolically (PropertyTagThumbnailWidth)
> p.thumbnail-width
32
> (p 'thumbnail-width)
32
> (get p 'thumbnail-width)
32
; If you want to get a full hashtable of the properties, you access the
; 'all field as shown below. (Note: You shouldn't modify the contents of the
; hashtable.)
> p.all
{hashtable '(.....)}
References muse_add_recent_item(), muse_mk_functional_object(), MUSE_NIL, and muse_raise_error().