muSE: muse_builtins.c File Reference
muse_builtins.c File Reference
#include "muse_builtins.h"
#include "muse_port.h"
#include <stdio.h>
#include <stdlib.h>
#include <memory.h>
Macros
#define _is_pid(pid) is_pid(env,pid)
Checks whether the given thing is a process id.
#define muse_shell_execute system
For unix-like systems, we just use system().
Functions
muse_cell fn_quote (muse_env *env, void *context, muse_cell args)
Quotes the given arguments without evaluating them.
muse_cell fn_cons (muse_env *env, void *context, muse_cell args)
(cons head tail).
muse_cell fn_eval (muse_env *env, void *context, muse_cell args)
muse_cell syntax_if (muse_env *env, void *context, muse_cell args)
muse_cell syntax_when (muse_env *env, void *context, muse_cell args)
muse_cell syntax_unless (muse_env *env, void *context, muse_cell args)
muse_cell syntax_cond (muse_env *env, void *context, muse_cell args)
cond is the generalization of if-then-else nested blocks.
muse_cell syntax_do (muse_env *env, void *context, muse_cell args)
muse_cell syntax_while (muse_env *env, void *context, muse_cell args)
muse_cell syntax_for (muse_env *env, void *context, muse_cell args)
muse_cell fn_stats (muse_env *env, void *context, muse_cell args)
muse_cell fn_int_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_float_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_number_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_cons_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_fn_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_lambda_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_symbol_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_string_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_int (muse_env *env, void *context, muse_cell args)
muse_cell fn_float (muse_env *env, void *context, muse_cell args)
muse_cell fn_number (muse_env *env, void *context, muse_cell args)
muse_cell fn_string (muse_env *env, void *context, muse_cell args)
muse_cell fn_char_code (muse_env *env, void *context, muse_cell args)
muse_cell fn_string_with_char_codes (muse_env *env, void *context, muse_cell args)
muse_cell fn_time_taken_us (muse_env *env, void *context, muse_cell args)
muse_cell fn_exit (muse_env *env, void *context, muse_cell args)
muse_cell fn_generate_documentation (muse_env *env, void *context, muse_cell args)
muse_cell fn_format (muse_env *env, void *context, muse_cell args)
muse_cell fn_string_length (muse_env *env, void *context, muse_cell args)
muse_cell fn_substring (muse_env *env, void *context, muse_cell args)
muse_cell fn_load_plugin (muse_env *env, void *context, muse_cell args)
muse_cell fn_this_process (muse_env *env, void *context, muse_cell args)
muse_cell fn_spawn (muse_env *env, void *context, muse_cell args)
muse_cell syntax_atomic (muse_env *env, void *context, muse_cell args)
muse_cell fn_receive (muse_env *env, void *context, muse_cell args)
muse_cell fn_run (muse_env *env, void *context, muse_cell args)
muse_cell fn_post (muse_env *env, void *context, muse_cell args)
muse_cell fn_process_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_with_timeout_us (muse_env *env, void *context, muse_cell args)
muse_cell fn_the (muse_env *env, void *context, muse_cell args)
muse_cell fn_trace (muse_env *env, void *context, muse_cell args)
muse_cell fn_system (muse_env *env, void *context, muse_cell args)
(system cmd arg1 arg2 ...) Executes the system command passing the given args.
muse_cell module_find_symbol_with_value (muse_env *env, void *obj, muse_cell value)
Searches this module's symbols for a symbol defined to the given value.
muse_cell fn_symbol_whose_value_is (muse_env *env, void *context, muse_cell args)
Detailed Description
Author
Srikumar K. S. (kumar.nosp@m.@muv.nosp@m.ee.co.nosp@m.m)
Copyright (c) 2006 Jointly owned by Srikumar K. S. and muvee Technologies Pte. Ltd.
All rights reserved. See LICENSE.txt distributed with this source code or http://muvee-symbolic-expressions.googlecode.com/svn/trunk/LICENSE.txt for terms and conditions under which this software is provided to you.
Function Documentation
muse_cell fn_stats (muse_env * env, void * context, muse_cell args)
(stats)
Evaluates to an object whose properties describe the current internal state of the muSE interpreter.
References fn_new(), muse_heap::free_cell_count, muse_list(), MUSE_NIL, and muse_put_many().
muse_cell fn_time_taken_us (muse_env * env, void * context, muse_cell args)
(time-taken-us ...block...)
Returns the time taken to execute the block, in microseconds.
References muse_tick(), and muse_tock().
muse_cell fn_generate_documentation (muse_env * env, void * context, muse_cell args)
(generate-documentation output-file-name)
References _t, muse_stack::bottom, muse_assign_port(), muse_fopen(), MUSE_NIL, MUSE_PORT_WRITE, muse_unassign_port(), port_close(), port_write(), and muse_stack::size.
muse_cell fn_string_length (muse_env * env, void * context, muse_cell args)
(string-length s)
Returns the number of characters in the string or () if s is not a string.
References MUSE_NIL, and MUSE_TEXT_CELL.
muse_cell fn_substring (muse_env * env, void * context, muse_cell args)
(substring str start-index [count])
Gives the substring of length count characters of the given string starting from start-index. If the start-index is considered to be modulo [0,length) ... which means you can get the last 3 characters of a string like this -
(substring str -3 3)
If you request more characters than is available in the string, you get as much of the string as is avaiable.
The count is optional. If omitted, the substring is considered up to the end of the string. You can use this to shorten the above example to -
(substring str -3)
Exceptions
error:integer-expected Handler format:
(fn (resume 'error:integer-expected value) ...)
Raised when an integer was expected and a different value was given. No point resuming since this is a grave programming error.
error:string-expected Handler format:
(fn (resume 'error:string-expected value) ...)
Raised when a string was expected and a different value was given. No point resuming since this is a grave programming error.
References fn_substring(), muse_add_recent_item(), MUSE_INT_CELL, muse_message(), muse_mk_text(), MUSE_NIL, muse_raise_error(), MUSE_TEXT_CELL, and muse_text_contents().
Referenced by fn_substring().
muse_cell fn_load_plugin (muse_env * env, void * context, muse_cell args)
(load-plugin dll-filename)
Loads and dynamically links the given plugin. Returns the result of invoking the plugin's entry point function.
References muse_link_plugin().