muSE: muse_port.c File Reference
muse_port.c File Reference
#include "muse_port.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
Functions
muse_char port_getchar (muse_port_t p)
Reads a unicode character from the port.
muse_char port_putchar (muse_char c, muse_port_t p)
Writes the given unicode character to the port.
muse_char port_ungetchar (muse_char c, muse_port_t p)
Writes back a unicode character to the port buffer.
white_space_t ez_skip_whitespace (muse_port_t f, int line, int col)
Skips all white space and comments following the current stream position in the given stream Returns the column position at which the next non-white space character starts.
MUSEAPI muse_cell muse_pread (muse_port_t f)
Reads the next symbolic expression at the current stream position, ignoring white space and comment lines.
MUSEAPI void muse_pwrite (muse_port_t f, muse_cell sexpr)
Writes the given s-expression to the given stream.
MUSEAPI muse_port_t muse_port (muse_env *env, muse_cell p)
Takes a muSE port represented as a cell and returns the internal port object that it uses.
ez_result_t ez_parse_atom (muse_port_t p, int col)
A ezscheme atom is a normal scheme atom - symbol, number, string.
ez_result_t ez_parse_group (muse_port_t p, int col)
An ezscheme group is an expression enclosed in parentheses.
ez_result_t ez_parse_list (muse_port_t p, int col)
An ezscheme list is a normal Scheme list, except that it allows for indent-defined expressions.
MUSEAPI muse_port_t muse_current_port (muse_env *env, muse_stdport_t which, muse_port_t port)
If port is NULL, retrieves the current input port for the current process.
Ports implementation API
void port_init (muse_env *env, muse_port_base_t *p)
Intended to be called inside a particular port's init function at port creation time.
void port_destroy (muse_port_base_t *p)
Intended to be called inside a particular ports destroy function at port destruction time.
void port_free (muse_port_t p)
Frees the whole port.
int port_getc (muse_port_base_t *p)
Same protocol as the system getc function, but works with the given port.
int port_ungetc (int c, muse_port_base_t *p)
Same protocol as the system ungetc function.
int port_putc (int c, muse_port_base_t *p)
Same protocol as the system putc function.
int port_eof (muse_port_base_t *port)
Returns EOF if the port has reached end of stream.
void port_close (muse_port_base_t *p)
Flushes the port and call's the port's close function to release system resources.
size_t port_read (void *buffer, size_t nbytes, muse_port_base_t *port)
Wraps the port specific read function.
size_t port_write (void *buffer, size_t nbytes, muse_port_base_t *port)
Wraps the port specific write function.
int port_flush (muse_port_base_t *port)
Writes any data pending in the port's output buffer and then calls the port-specific flush function.
Pretty print support.
void pretty_printer_indent (muse_port_t p)
void pretty_printer_unindent (muse_port_t p)
void pretty_printer_line_break (muse_port_t f)
void pretty_printer_move (muse_port_t p, int numc)
ezscheme structures
int ez_update_col (muse_port_t f, int ch, int col)
ez_result_t ez_parse (muse_port_t p, int col, muse_boolean is_head)
A scheme to eliminate unnecessary parentheses in code.
muse_cell ez_parse_expr (muse_port_t p)
Detailed Description
Author
Srikumar K. S. (kumar.nosp@m.@muv.nosp@m.ee.co.nosp@m.m)
Copyright (c) 2006 Jointly owned by Srikumar K. S. and muvee Technologies Pte. Ltd.
All rights reserved. See LICENSE.txt distributed with this source code or http://muvee-symbolic-expressions.googlecode.com/svn/trunk/LICENSE.txt for terms and conditions under which this software is provided to you.
Function Documentation
ez_result_t ez_parse_group (muse_port_t p, int col)
An ezscheme group is an expression enclosed in parentheses.
ezscheme uses parentheses to "group" as opposed to defining function heads. This means that enclosing an expression in multiple set of parentheses has no effect compared to just usig a single set - i.e. (hello) is exactly the same as (((hello))).
References _muse_port_base_t::env, ez_parse(), ez_skip_whitespace(), MUSE_NIL, port_eof(), and port_getc().
Referenced by ez_parse().