muSE: muse_builtins.h File Reference
muse_builtins.h File Reference
#include "muse_opcodes.h"
#include "muse_builtin_math.h"
Functions
muse_cell fn_quote (muse_env *env, void *context, muse_cell args)
Quotes the given arguments without evaluating them.
muse_cell fn_lazy (muse_env *env, void *context, muse_cell args)
muse_cell fn_cons (muse_env *env, void *context, muse_cell args)
(cons head tail).
muse_cell fn_lcons (muse_env *env, void *context, muse_cell args)
(lcons a b)
muse_cell syntax_lambda (muse_env *env, void *context, muse_cell args)
muse_cell syntax_block (muse_env *env, void *context, muse_cell args)
muse_cell syntax_generic_lambda (muse_env *env, void *context, muse_cell args)
(gfn formal-args body)
muse_cell syntax_generic_block (muse_env *env, void *context, muse_cell args)
(gfn: formal-args body)
muse_cell syntax_let (muse_env *env, void *context, muse_cell args)
(let <variable-bindings> <body>).
muse_cell syntax_case (muse_env *env, void *context, muse_cell args)
(case object <match-cases>).
muse_cell fn_apply (muse_env *env, void *context, muse_cell args)
(apply fn arglist).
muse_cell fn_apply_w_keywords (muse_env *env, void *context, muse_cell args)
The counterpart of call/keywords that applies a function to an a-list of key-value pairs.
muse_cell fn_eval (muse_env *env, void *context, muse_cell args)
muse_cell fn_call_w_keywords (muse_env *env, void *context, muse_cell args)
muse_cell fn_callcc (muse_env *env, void *context, muse_cell args)
muse_cell fn_the (muse_env *env, void *context, muse_cell args)
muse_cell fn_meta (muse_env *env, void *context, muse_cell args)
Returns an object containing meta information about the given function.
muse_cell fn_trace (muse_env *env, void *context, muse_cell args)
muse_cell fn_with_recent (muse_env *env, void *context, muse_cell args)
muse_cell fn_symbol_whose_value_is (muse_env *env, void *context, muse_cell args)
muse_cell syntax_try (muse_env *env, void *context, muse_cell args)
Marks an expression that needs to be protected by exception handlers.
muse_cell fn_raise (muse_env *env, void *context, muse_cell args)
(raise [exception-details])
muse_cell fn_retry (muse_env *env, void *context, muse_cell args)
Similar to raise but does not prepend a resume continuation to the trial condition.
muse_cell syntax_finally (muse_env *env, void *context, muse_cell args)
muse_cell fn_get (muse_env *env, void *context, muse_cell args)
muse_cell fn_put (muse_env *env, void *context, muse_cell args)
muse_cell fn_put_many (muse_env *env, void *context, muse_cell args)
muse_cell fn_assoc (muse_env *env, void *context, muse_cell args)
muse_cell fn_plist (muse_env *env, void *context, muse_cell args)
muse_cell fn_symbol (muse_env *env, void *context, muse_cell args)
muse_cell fn_name (muse_env *env, void *context, muse_cell args)
muse_cell fn_gensym (muse_env *env, void *context, muse_cell args)
Generates an interned anonymous symbol that can be used as a variable in macro generated code.
muse_cell fn_define (muse_env *env, void *context, muse_cell args)
muse_cell fn_define_extension (muse_env *env, void *context, muse_cell args)
muse_cell fn_define_override (muse_env *env, void *context, muse_cell args)
muse_cell fn_set_M (muse_env *env, void *context, muse_cell args)
muse_cell fn_setf_M (muse_env *env, void *context, muse_cell args)
muse_cell fn_setr_M (muse_env *env, void *context, muse_cell args)
muse_cell fn_first (muse_env *env, void *context, muse_cell args)
muse_cell fn_rest (muse_env *env, void *context, muse_cell args)
muse_cell fn_nth (muse_env *env, void *context, muse_cell args)
muse_cell fn_take (muse_env *env, void *context, muse_cell args)
muse_cell fn_drop (muse_env *env, void *context, muse_cell args)
muse_cell fn_dup (muse_env *env, void *context, muse_cell args)
muse_cell fn_list (muse_env *env, void *context, muse_cell args)
muse_cell fn_append_M (muse_env *env, void *context, muse_cell args)
muse_cell fn_length (muse_env *env, void *context, muse_cell args)
muse_cell fn_map (muse_env *env, void *context, muse_cell args)
muse_cell fn_join (muse_env *env, void *context, muse_cell args)
muse_cell fn_collect (muse_env *env, void *context, muse_cell args)
muse_cell fn_reduce (muse_env *env, void *context, muse_cell args)
muse_cell fn_slice (muse_env *env, void *context, muse_cell args)
muse_cell fn_find (muse_env *env, void *context, muse_cell args)
muse_cell fn_andmap (muse_env *env, void *context, muse_cell args)
muse_cell fn_ormap (muse_env *env, void *context, muse_cell args)
muse_cell fn_for_each (muse_env *env, void *context, muse_cell args)
muse_cell fn_transpose (muse_env *env, void *context, muse_cell args)
muse_cell fn_datafn (muse_env *env, void *context, muse_cell args)
muse_cell fn_eq (muse_env *env, void *context, muse_cell args)
muse_cell fn_equal (muse_env *env, void *context, muse_cell args)
muse_cell fn_lt (muse_env *env, void *context, muse_cell args)
muse_cell fn_gt (muse_env *env, void *context, muse_cell args)
muse_cell fn_le (muse_env *env, void *context, muse_cell args)
muse_cell fn_ge (muse_env *env, void *context, muse_cell args)
muse_cell fn_ne (muse_env *env, void *context, muse_cell args)
muse_cell fn_and (muse_env *env, void *context, muse_cell args)
muse_cell fn_or (muse_env *env, void *context, muse_cell args)
muse_cell fn_not (muse_env *env, void *context, muse_cell args)
muse_cell fn_min (muse_env *env, void *context, muse_cell args)
muse_cell fn_max (muse_env *env, void *context, muse_cell args)
muse_cell syntax_if (muse_env *env, void *context, muse_cell args)
muse_cell syntax_when (muse_env *env, void *context, muse_cell args)
muse_cell syntax_unless (muse_env *env, void *context, muse_cell args)
muse_cell syntax_cond (muse_env *env, void *context, muse_cell args)
cond is the generalization of if-then-else nested blocks.
muse_cell syntax_do (muse_env *env, void *context, muse_cell args)
muse_cell syntax_while (muse_env *env, void *context, muse_cell args)
muse_cell syntax_for (muse_env *env, void *context, muse_cell args)
muse_cell fn_int_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_float_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_number_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_cons_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_fn_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_lambda_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_symbol_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_string_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_whatis (muse_env *env, void *context, muse_cell args)
muse_cell fn_int (muse_env *env, void *context, muse_cell args)
muse_cell fn_float (muse_env *env, void *context, muse_cell args)
muse_cell fn_number (muse_env *env, void *context, muse_cell args)
muse_cell fn_string (muse_env *env, void *context, muse_cell args)
muse_cell fn_format (muse_env *env, void *context, muse_cell args)
muse_cell fn_char_code (muse_env *env, void *context, muse_cell args)
muse_cell fn_string_with_char_codes (muse_env *env, void *context, muse_cell args)
muse_cell fn_new (muse_env *env, void *context, muse_cell args)
muse_cell fn_supers (muse_env *env, void *context, muse_cell args)
muse_cell fn_super_invoke (muse_env *env, void *context, muse_cell args)
muse_cell fn_super_invoke_explicit (muse_env *env, void *context, muse_cell args)
muse_cell fn_isa_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_object_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_sort_inplace (muse_env *env, void *context, muse_cell args)
muse_cell fn_sort (muse_env *env, void *context, muse_cell args)
Just like fn_sort_inplace(), except that the original list is not modified.
muse_cell fn_reverse (muse_env *env, void *context, muse_cell args)
muse_cell fn_reverse_inplace (muse_env *env, void *context, muse_cell args)
muse_cell fn_port_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_close (muse_env *env, void *context, muse_cell args)
muse_cell fn_eof_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_print (muse_env *env, void *context, muse_cell args)
muse_cell fn_write (muse_env *env, void *context, muse_cell args)
muse_cell fn_read (muse_env *env, void *context, muse_cell args)
muse_cell fn_read_line (muse_env *env, void *context, muse_cell args)
muse_cell fn_flush (muse_env *env, void *context, muse_cell args)
muse_cell fn_mickey (muse_env *env, void *context, muse_cell args)
muse_cell fn_scribble (muse_env *env, void *context, muse_cell args)
{scribble} or (scribble inport)
muse_cell fn_load (muse_env *env, void *context, muse_cell args)
muse_cell fn_file_has_attached_code_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_write_xml (muse_env *env, void *context, muse_cell args)
muse_cell fn_read_xml (muse_env *env, void *context, muse_cell args)
muse_cell fn_xml (muse_env *env, void *context, muse_cell args)
{xml}
muse_cell fn_write_json (muse_env *env, void *context, muse_cell args)
muse_cell fn_read_json (muse_env *env, void *context, muse_cell args)
muse_cell fn_json (muse_env *env, void *context, muse_cell args)
{json}
muse_cell fn_exit (muse_env *env, void *context, muse_cell args)
muse_cell fn_tab_syntax (muse_env *env, void *context, muse_cell args)
{tab-syntax} Changes the syntax of the currently reading port to the EZSCHEME syntax.
muse_cell fn_scheme_syntax (muse_env *env, void *context, muse_cell args)
{scheme-syntax} Changes the syntax of the currently reading port to the normal syntax.
muse_cell fn_spawn (muse_env *env, void *context, muse_cell args)
muse_cell fn_this_process (muse_env *env, void *context, muse_cell args)
muse_cell syntax_atomic (muse_env *env, void *context, muse_cell args)
muse_cell fn_receive (muse_env *env, void *context, muse_cell args)
muse_cell fn_run (muse_env *env, void *context, muse_cell args)
muse_cell fn_post (muse_env *env, void *context, muse_cell args)
muse_cell fn_process_p (muse_env *env, void *context, muse_cell args)
muse_cell fn_with_timeout_us (muse_env *env, void *context, muse_cell args)
Misc
muse_cell fn_string_length (muse_env *env, void *context, muse_cell args)
muse_cell fn_substring (muse_env *env, void *context, muse_cell args)
muse_cell fn_time_taken_us (muse_env *env, void *context, muse_cell args)
muse_cell fn_generate_documentation (muse_env *env, void *context, muse_cell args)
muse_cell fn_load_plugin (muse_env *env, void *context, muse_cell args)
muse_cell fn_list_files (muse_env *env, void *context, muse_cell args)
muse_cell fn_list_folders (muse_env *env, void *context, muse_cell args)
(list-folders parent-folder).
muse_cell fn_split (muse_env *env, void *context, muse_cell args)
muse_cell fn_system (muse_env *env, void *context, muse_cell args)
(system cmd arg1 arg2 ...) Executes the system command passing the given args.
muse_cell fn_alert (muse_env *env, void *context, muse_cell args)
muse_cell fn_urlencode (muse_env *env, void *context, muse_cell args)
muse_cell fn_urldecode (muse_env *env, void *context, muse_cell args)
muse_cell fn_launch (muse_env *env, void *context, muse_cell args)
muse_cell fn_windows_registry_entry (muse_env *env, void *context, muse_cell args)
muse_cell fn_temp_folder (muse_env *env, void *context, muse_cell args)
muse_cell fn_temp_file (muse_env *env, void *context, muse_cell args)
muse_cell fn_to_lower (muse_env *env, void *context, muse_cell args)
muse_cell fn_to_upper (muse_env *env, void *context, muse_cell args)
muse_cell fn_stats (muse_env *env, void *context, muse_cell args)
Detailed Description
Author
Srikumar K. S. (kumar.nosp@m.@muv.nosp@m.ee.co.nosp@m.m)
Copyright (c) 2006 Jointly owned by Srikumar K. S. and muvee Technologies Pte. Ltd.
All rights reserved. See LICENSE.txt distributed with this source code or http://muvee-symbolic-expressions.googlecode.com/svn/trunk/LICENSE.txt for terms and conditions under which this software is provided to you.
Function Documentation
muse_cell fn_string_length (muse_env * env, void * context, muse_cell args)
 (string-length s)
Returns the number of characters in the string or () if s is not a string.
References MUSE_NIL, and MUSE_TEXT_CELL.
muse_cell fn_substring (muse_env * env, void * context, muse_cell args)
 (substring str start-index [count])
Gives the substring of length count characters of the given string starting from start-index. If the start-index is considered to be modulo [0,length) ... which means you can get the last 3 characters of a string like this -
 (substring str -3 3)
If you request more characters than is available in the string, you get as much of the string as is avaiable.
The count is optional. If omitted, the substring is considered up to the end of the string. You can use this to shorten the above example to -
 (substring str -3)
Exceptions
error:integer-expected Handler format:
 (fn (resume 'error:integer-expected value) ...)
Raised when an integer was expected and a different value was given. No point resuming since this is a grave programming error.
error:string-expected Handler format:
 (fn (resume 'error:string-expected value) ...)
Raised when a string was expected and a different value was given. No point resuming since this is a grave programming error.
References fn_substring(), muse_add_recent_item(), MUSE_INT_CELL, muse_message(), muse_mk_text(), MUSE_NIL, muse_raise_error(), MUSE_TEXT_CELL, and muse_text_contents().
Referenced by fn_substring().
muse_cell fn_time_taken_us (muse_env * env, void * context, muse_cell args)
 (time-taken-us ...block...)
Returns the time taken to execute the block, in microseconds.
References muse_tick(), and muse_tock().
muse_cell fn_generate_documentation (muse_env * env, void * context, muse_cell args)
 (generate-documentation output-file-name)
References _t, muse_stack::bottom, muse_format_view_t::format, muse_assign_port(), MUSE_FLOAT_CELL, muse_fopen(), MUSE_INT_CELL, muse_mk_ctext_utf8(), MUSE_NATIVEFN_CELL, MUSE_NIL, MUSE_PORT_WRITE, MUSE_SYMBOL_CELL, MUSE_TEXT_CELL, muse_unassign_port(), port_close(), port_write(), and muse_stack::size.
muse_cell fn_load_plugin (muse_env * env, void * context, muse_cell args)
 (load-plugin dll-filename)
Loads and dynamically links the given plugin. Returns the result of invoking the plugin's entry point function.
References muse_link_plugin().
muse_cell fn_list_files (muse_env * env, void * context, muse_cell args)
 (list-files [pattern])
Returns a list of files that patch the given pattern. For example:
 (list-files "*.jpg")
will list the JPG files in the current folder. Note that the returned list only has the file names and not the full paths to the files.
Another use for list-files is to check whether a particular file exists. If p is the full path to the file, say, then
 (list-files p)
will be () if the file doesn't exist and will be a single-entry list of the file's name (stripped of path) if the file exists.
References muse_add_recent_item(), muse_generate_list(), and MUSE_NIL.
muse_cell fn_list_folders (muse_env * env, void * context, muse_cell args)
(list-folders parent-folder).
Returns a list of folder names for all the folders that exist under the given parent folder. For example:
 (list-folders "../")
will list the folders above the current folder. Note that the returned list only has the folder names and not the full paths to the folders. Also, the folder names don't end with '/' or any such path separator character.
Another use for list-folders is to check whether a particular folder exists. If p is the full path to the folder without any trailing slashes/backslashes, then
 (list-folders p)
will be () if the folder doesn't exist and will be a single-entry list of the folder's name (stripped of path) if the folder exists.
References muse_add_recent_item(), muse_generate_list(), muse_mk_text(), and MUSE_NIL.
muse_cell fn_split (muse_env * env, void * context, muse_cell args)
 (split "one;two;;three;" ";") -> ("one" "two" "" "three" "")
 (split "one=1;two=2;three=3" "=;") -> ("one" "1" "two" "2" "three" "3")
The first argument is the string to split and the second argument is a character separator.
You can define a recursive splitter like this -
 (define (split-rec str (sep . seps))
     (if seps
         (map (fn (s) (split-rec s seps)) (split str sep))
         (split str sep)))
so that
 (split-rec "a=1&b=2&c=3" '("&" "="))
will give you
 (("a" "1") ("b" "2") ("c" "3"))
.
References fn_split(), muse_add_recent_item(), and muse_generate_list().
Referenced by fn_split().
muse_cell fn_alert (muse_env * env, void * context, muse_cell args)
 (alert arg1 arg2 ...)
Puts up an "abort-retry-ignore" message box with the given text. The arguments are "format"ed into a single string and presented in the dialog box.
References fn_format(), muse_message(), and MUSE_NIL.
muse_cell fn_urlencode (muse_env * env, void * context, muse_cell args)
 (urlencode "string")
Takes an arbitrary string and returns a version that can be used as a part of a URL. The string is not expected to contain unicode characters.
References muse_mk_text(), MUSE_NIL, muse_raise_error(), and muse_text_contents().
muse_cell fn_urldecode (muse_env * env, void * context, muse_cell args)
 (urldecode "encoded%20string")
Takes a url-encoded string and returns the regular string form.
References muse_mk_text(), MUSE_NIL, muse_raise_error(), and muse_text_contents().
muse_cell fn_launch (muse_env * env, void * context, muse_cell args)
 (launch "file.ext")
Opens the given filesystem object or URL in the default application.
References fn_new(), fn_system(), MUSE_CONS_CELL, MUSE_FLOAT_CELL, muse_functional_object_data(), MUSE_INT_CELL, MUSE_LAMBDA_CELL, muse_list(), muse_mk_text(), MUSE_NATIVEFN_CELL, MUSE_NIL, muse_put(), MUSE_SYMBOL_CELL, MUSE_TEXT_CELL, muse_text_contents(), muse_functional_object_t::type_info, and muse_functional_object_type_t::type_word.
muse_cell fn_windows_registry_entry (muse_env * env, void * context, muse_cell args)
 (windows-registry-entry section entry)
Looks up the given entry path in the given section. The entry's components are to be separated by backslashes. Integers become muSE integers, strings become muSE strings, a multi-string becomes a list of strings and a binary blob becomes a byte array.
Parameters
section Can be one of "HKEY_CLASSES_ROOT", "HKEY_CURRENT_CONFIG", "HKEY_CURRENT_USER", "HKEY_LOCAL_MACHINE", "HKEY_PERFORMANCE_DATA", "HKEY_PERFORMANCE_NLSTEXT", "HKEY_PERFORMANCE_TEXT" or "HKEY_USERS"
entry A backslash separated sequence of subkeys.
Example
To get the installed location of muvee Reveal's MVRT.dll, you can query the following registry entry -
 (windows-registry-entry
    "HKEY_LOCAL_MACHINE"
   "SOFTWARE\\Classes\\CLSID\\{30A8E5D8-A4BD-4038-981E-AD2B7AD781EA}\\InprocServer32\\")
References fn_windows_registry_entry(), muse_add_recent_item(), muse_generate_list(), muse_mk_ctext(), muse_mk_int(), MUSE_NIL, muse_raise_error(), and muse_text_contents().
Referenced by fn_windows_registry_entry().
muse_cell fn_temp_folder (muse_env * env, void * context, muse_cell args)
 (temp-folder)
Returns a path into which you can store temporary files. The path has a trailing path separator so you can append a file name to it directly. You're also assured that the folder exists and can be written to. If not, the return value is ().
References fn_temp_folder(), muse_add_recent_item(), muse_mk_ctext(), muse_mk_text(), and MUSE_NIL.
Referenced by fn_temp_folder().
muse_cell fn_temp_file (muse_env * env, void * context, muse_cell args)
 (temp-file folder [prefix])
Returns the full path to a unique temporary file in the given folder. If no folder is given, then temp-folder is used to get a folder for storing temporary files.
References fn_temp_file(), muse_add_recent_item(), muse_mk_ctext(), muse_mk_ctext_utf8(), MUSE_NIL, and muse_text_contents().
Referenced by fn_temp_file().
muse_cell fn_to_lower (muse_env * env, void * context, muse_cell args)
 (to-lower string)
Converts the given string to lower case.
References muse_mk_text(), and muse_text_contents().
muse_cell fn_to_upper (muse_env * env, void * context, muse_cell args)
 (to-upper string)
Converts the given string to upper case.
References muse_mk_text(), and muse_text_contents().
muse_cell fn_stats (muse_env * env, void * context, muse_cell args)
 (stats)
Evaluates to an object whose properties describe the current internal state of the muSE interpreter.
References fn_new(), muse_heap::free_cell_count, muse_list(), MUSE_NIL, and muse_put_many().