muSE: muse_utils.c File Reference
muse_utils.c File Reference
#include "muse_builtins.h"
#include <string.h>
#include <assert.h>
#include <stdlib.h>
#include "muse_port.h"
#include "muse_utils.h"
Functions
int uc16_to_utf8 (int c, unsigned char *utf8, int nbytes)
Converts the given 16-bit unicode character c to utf8 and stores the result in the given utf8 buffer.
int utf8_to_uc16 (const unsigned char *utf8, muse_char *uc16)
Sets uc16[0] to a unicode character if one utf8 character could be parsed.
buffer_t * buffer_alloc ()
Allocates a new buffer object.
void buffer_free (buffer_t *b)
Releases all memory allocated for the buffer object.
void buffer_putc (buffer_t *b, muse_char c)
Appends one character to the buffer.
void buffer_puts (buffer_t *b, const muse_char *s, int len)
Appends the given string s of length len.
muse_cell buffer_to_string (buffer_t *b, muse_env *env)
Use to convert the contents of the buffer to a muSE string.
muse_cell buffer_to_symbol (buffer_t *b, muse_env *env)
Similar to buffer_to_string(), but gives a muSE symbol instead.
int buffer_length (buffer_t *b)
The current length of the buffer in number of characters.
muse_char buffer_char (buffer_t *b, int i)
Gets the character at the i-th position in the buffer.
muse_cell buffer_substring (buffer_t *b, muse_env *env, int from, int len)
Returns a muSE string which is a substring of the contents of the buffer starting from from and containing a maximum of len characters.
Detailed Description
Author
Srikumar K. S. (kumar.nosp@m.@muv.nosp@m.ee.co.nosp@m.m)
Copyright (c) 2006 Jointly owned by Srikumar K. S. and muvee Technologies Pte. Ltd.
All rights reserved. See LICENSE.txt distributed with this source code or http://muvee-symbolic-expressions.googlecode.com/svn/trunk/LICENSE.txt for terms and conditions under which this software is provided to you.
Shared brick layer code.
Function Documentation
int uc16_to_utf8 (int c, unsigned char * utf8, int nbytes)
Converts the given 16-bit unicode character c to utf8 and stores the result in the given utf8 buffer.
If more than nbytes are needed, the character is not converted and 0 is returned. Otherwise the number of bytes used in the buffer is returned. If the unicode character is not 16-bit, an error value -1 is returned.
Referenced by muse_unicode_to_utf8(), port_putchar(), and port_ungetchar().
int utf8_to_uc16 (const unsigned char * utf8, muse_char * uc16)
Sets uc16[0] to a unicode character if one utf8 character could be parsed.
The return value is the number of bytes consumed.
Referenced by muse_utf8_to_unicode(), and port_getchar().
buffer_t* buffer_alloc ()
Allocates a new buffer object.
The buffer can serve as a variable length string, which it keeps as a list of fragments of 128 characters each.
Referenced by fn_read_line().
void buffer_putc (buffer_t * b, muse_char c)
Appends one character to the buffer.
It is added to the last fragment if there is space in it and if not a new fragment is created.
Referenced by fn_read_line().
void buffer_puts (buffer_t * b, const muse_char * s, int len)
Appends the given string s of length len.
Semantically equivalent to calling buffer_putc() on each of the characters of the string in sequence.
References buffer_puts().
Referenced by buffer_puts().
muse_char buffer_char (buffer_t * b, int i)
Gets the character at the i-th position in the buffer.
The value of i has to be less than the number returned by buffer_length().
muse_cell buffer_substring (buffer_t * b, muse_env * env, int from, int len)
Returns a muSE string which is a substring of the contents of the buffer starting from from and containing a maximum of len characters.
from + len cannot be greater than the buffer_length().
References buffer_length(), muse_mk_text(), MUSE_NIL, and muse_text_contents().