muSE: muse_builtin_plist.c File Reference
muse_builtin_plist.c File Reference
#include "muse_builtins.h"
Functions
MUSEAPI muse_cell muse_get (muse_env *env, muse_cell obj, muse_cell key, muse_cell argv)
Recursive property getter.
muse_cell fn_get (muse_env *env, void *context, muse_cell args)
MUSEAPI muse_cell muse_put (muse_env *env, muse_cell obj, muse_cell prop, muse_cell argv)
Deeply nested value setting support.
MUSEAPI muse_cell muse_put_many (muse_env *env, muse_cell obj, muse_cell argv)
muse_cell fn_put (muse_env *env, void *context, muse_cell args)
muse_cell fn_put_many (muse_env *env, void *context, muse_cell args)
muse_cell fn_assoc (muse_env *env, void *context, muse_cell args)
muse_cell fn_plist (muse_env *env, void *context, muse_cell args)
muse_cell fn_symbol (muse_env *env, void *context, muse_cell args)
muse_cell fn_name (muse_env *env, void *context, muse_cell args)
muse_cell muse_intern_symbol (muse_env *env, muse_cell sym, int local_ix, muse_int hash)
Includes the given symbol in the symbol table and makes its value process-local.
muse_cell fn_gensym (muse_env *env, void *context, muse_cell args)
Generates an interned anonymous symbol that can be used as a variable in macro generated code.
Detailed Description
Author
Srikumar K. S. (kumar.nosp@m.@muv.nosp@m.ee.co.nosp@m.m)
Copyright (c) 2006 Jointly owned by Srikumar K. S. and muvee Technologies Pte. Ltd.
All rights reserved. See LICENSE.txt distributed with this source code or http://muvee-symbolic-expressions.googlecode.com/svn/trunk/LICENSE.txt for terms and conditions under which this software is provided to you.
Function Documentation
muse_cell muse_intern_symbol (muse_env * env, muse_cell sym, int local_ix, muse_int hash)
Includes the given symbol in the symbol table and makes its value process-local.
Note that no check is performed to see whether the symbol is already interned or not.
References muse_stack::bottom, _muse_process_frame_t::locals, MUSE_NIL, muse_raise_error(), MUSE_SYMBOL_CELL, muse_stack::size, and muse_stack::top.
Referenced by fn_gensym(), fn_name(), and muse_symbol().