muSE: muse_opcodes.h File Reference
muse_opcodes.h File Reference
#include "muse.h"
Data Structures
struct muse_cons_cell
A cons cell consists of references to two muse cells called the head and the tail.
struct muse_nativefn_cell
muSE provides the facility to invoke C functions during the evaluation process.
struct muse_text_cell
A string is represented in a single cell by storing a pair of pointers to the start of the string and the end of the string.
union muse_cell_data
A muse cell is a union of all the possible cell types.
struct muse_stack
A stack is used to keep track of temporary references to objects so that a cons-ing operation does not result in an object being inadvertently garbage collected.
struct muse_heap
The muse heap is an array of cells where the cells available for allocation are collected into a free list.
struct muse_trace_t
A way to trace evaluations down the stack.
struct muse_traceinfo_t
struct recent_entry_t
struct recent_entries_t
struct recent_context_t
struct recent_contexts_t
struct recent_t
struct _muse_process_frame_t
A frame is the local environment of a process.
struct muse_slot_t
struct _muse_env
The muse environment contains all info relevant to evaluation of expressions in muSE.
Macros
#define _t() env->builtin_symbols[MUSE_T]
Returns the T symbol that is used to represent "TRUE" if no other object is available to represent it.
#define _newlocal() op_newlocal(env)
Returns a newly allocated process local cell.
Typedefs
typedef double muse_float_cell
A float in muSE is a 64-bit double.
typedef struct
_muse_process_frame_t muse_process_frame_t
A frame is the local environment of a process.
Functions
void muse_init_recent (recent_t *r, int capacity, int depth)
Initializes the scoped recent calculations data structure.
void muse_clear_recent (recent_t *r)
Frees the scoped recent calculations data structure.
recent_t muse_copy_recent (recent_t *r)
Makes a copy of all the recent info upto the present execution point.
void muse_restore_recent (recent_t *r, recent_t *dest)
Takes a saved "recent" data structure and restores it into the given destination.
void muse_mark_recent_context (muse_env *env, recent_t *r, int ctxt)
Marks all objects in the recent scope.
void muse_mark_recent (muse_env *env, recent_t *r)
Marks all objects in the recent data structure.
muse_boolean muse_find_recent_item (muse_env *env, muse_int key, muse_cell *value)
8 recent items are stored indexed by a 64-bit key.
recent_entry_t * muse_find_recent_lazy_item (muse_env *env)
Locates the most recent lazy item in the recents list.
muse_cell muse_add_recent_item (muse_env *env, muse_int key, muse_cell value)
You can add a new "recent" item using this function.
void muse_withdraw_recent_item (muse_env *env)
Removes the most recent item added to the recents list.
void muse_push_recent_scope (muse_env *env)
Enter a scope so that previous recent values are temporarily forgotten.
muse_cell muse_pop_recent_scope (muse_env *env, muse_int key, muse_cell value)
Exit from the scope with a result so that the innards of a computation are forgotten.
int muse_forget_it_temporarily (muse_env *env)
Saves the current value of it and reset it to "it".
muse_process_frame_t * create_process (muse_env *env, int attention, muse_cell thunk, void *sp)
Creates a new process and returns a pointer to the frame of the newly created process.
muse_process_frame_t * init_process_mailbox (muse_process_frame_t *p)
A process's mailbox is a linked list whose head gives the pid of the process.
muse_boolean prime_process (muse_process_frame_t *process)
Should be called after create_process to get it rolling.
muse_boolean switch_to_process (muse_env *env, muse_process_frame_t *process)
Immediately switches attention to the given process.
void yield_process (muse_env *env, int spent_attention)
Used by muse_apply() to decrement the attention spent on the current process.
muse_boolean procrastinate (muse_env *env)
Goes around the processes list and returns to the same point after one round-robin cycle.
muse_boolean remove_process (muse_process_frame_t *process)
Removes the given process from the process ring and marks it as "dead".
muse_cell process_id (muse_process_frame_t *process)
A function to wrap getting the process ID of a process from the process's frame structure.
muse_boolean is_main_process (muse_env *env)
Returns MUSE_TRUE if the current process is the main process and MUSE_FALSE otherwise.
void mark_process (muse_process_frame_t *p)
Marks all references held by the given process.
void free_process (muse_process_frame_t *p)
Frees process data structure memory.
muse_cell fn_pid (muse_env *env, muse_process_frame_t *process, muse_cell args)
Used to send asynchronous messages to a process and serves as a process's identifier.
void post_message (muse_process_frame_t *process, muse_cell msg)
Appends the given message (which, in general, should include the sending process's pid at the head) to the mailbox of the given process.
void enter_atomic (muse_env *env)
Enters an atomic block that should be evaluated without switching to another process.
void leave_atomic (muse_env *env)
Leaves the current atomic block that should be evaluated without switching to another process.
void push_timeout (muse_env *env, muse_cell id, muse_int timeout_us)
Adds another level of timeout nesting.
void check_timeout (muse_env *env)
Checks whether any timeout has expired and if so raises an exception to the effect.
int uc16_to_utf8 (int uc16, unsigned char *utf8, int nbytes)
Converts the given 16-bit unicode character c to utf8 and stores the result in the given utf8 buffer.
int utf8_to_uc16 (const unsigned char *utf8, muse_char *uc16)
Sets uc16[0] to a unicode character if one utf8 character could be parsed.
Variables
BEGIN_MUSE_C_FUNCTIONS typedef
longlong_t muse_int_cell
A single cell is used to represent an integer in muSE.
const char * g_muse_typenames []
String names for the various cell types, intended for debugging and reporting use.
Detailed Description
Author
Srikumar K. S. (kumar.nosp@m.@muv.nosp@m.ee.co.nosp@m.m)
Copyright (c) 2006 Jointly owned by Srikumar K. S. and muvee Technologies Pte. Ltd.
All rights reserved. See LICENSE.txt distributed with this source code or http://muvee-symbolic-expressions.googlecode.com/svn/trunk/LICENSE.txt for terms and conditions under which this software is provided to you.
Macro Definition Documentation
#define _newlocal () op_newlocal(env)
Returns a newly allocated process local cell.
The return value is an index into the locals stack.
Referenced by fn_gensym(), and muse_symbol().
Function Documentation
int uc16_to_utf8 (int c, unsigned char * utf8, int nbytes)
Converts the given 16-bit unicode character c to utf8 and stores the result in the given utf8 buffer.
If more than nbytes are needed, the character is not converted and 0 is returned. Otherwise the number of bytes used in the buffer is returned. If the unicode character is not 16-bit, an error value -1 is returned.
Referenced by muse_unicode_to_utf8(), port_putchar(), and port_ungetchar().
int utf8_to_uc16 (const unsigned char * utf8, muse_char * uc16)
Sets uc16[0] to a unicode character if one utf8 character could be parsed.
The return value is the number of bytes consumed.
Referenced by muse_utf8_to_unicode(), and port_getchar().
Variable Documentation
BEGIN_MUSE_C_FUNCTIONS typedef longlong_t muse_int_cell
A single cell is used to represent an integer in muSE.
Integers are all 64-bit to avoid any conversion and data loss issues.
const char* g_muse_typenames[]
String names for the various cell types, intended for debugging and reporting use.
See Also
_typename()