muSE: muse_builtin_math.c File Reference
muse_builtin_math.c File Reference
#include "muse_builtin_math.h"
#include <math.h>
#include <stdlib.h>
Typedefs
typedef double(* unary_math_op_t)(double)
The type unary math operators.
Functions
muse_cell fn_add (muse_env *env, void *context, muse_cell args)
muse_cell fn_sub (muse_env *env, void *context, muse_cell args)
muse_cell fn_mul (muse_env *env, void *context, muse_cell args)
muse_cell fn_div (muse_env *env, void *context, muse_cell args)
muse_cell fn_idiv (muse_env *env, void *context, muse_cell args)
muse_cell fn_mod (muse_env *env, void *context, muse_cell args)
muse_cell fn_inc (muse_env *env, void *context, muse_cell args)
muse_cell fn_dec (muse_env *env, void *context, muse_cell args)
muse_cell fn_trunc (muse_env *env, void *context, muse_cell args)
muse_cell fn_rand (muse_env *env, void *context, muse_cell args)
muse_cell fn_pow (muse_env *env, void *context, muse_cell args)
muse_cell fn_unary_math (muse_env *env, void *fn, muse_cell args)
The function that calls the supplied unary math operator in the "context" field on the given argument.
void muse_math_load_common_unary_functions (muse_env *env)
Defines log, log10, sqrt, sin, cos, tan, etc.
Detailed Description
Author
Srikumar K. S. (kumar.nosp@m.@muv.nosp@m.ee.co.nosp@m.m)
Copyright (c) 2006 Jointly owned by Srikumar K. S. and muvee Technologies Pte. Ltd.
All rights reserved. See LICENSE.txt distributed with this source code or http://muvee-symbolic-expressions.googlecode.com/svn/trunk/LICENSE.txt for terms and conditions under which this software is provided to you.
Function Documentation
muse_cell fn_add (muse_env * env, void * context, muse_cell args)
(+ ...numbers...)
add sums up all of its arguments and returns the result. The result will be an integer if all of its arguments are integers. Otherwise it'll be float.
References muse_expect(), MUSE_FLOAT_CELL, MUSE_INT_CELL, and muse_message().
muse_cell fn_sub (muse_env * env, void * context, muse_cell args)
(- ...numbers...)
Takes 1 or more arguments.
(- m) gives -m
(- m n) gives (m-n)
(- m n o p) gives (m - (n+o+p))
References muse_expect(), MUSE_FLOAT_CELL, MUSE_INT_CELL, muse_message(), and MUSE_NIL.
muse_cell fn_mul (muse_env * env, void * context, muse_cell args)
(* ...numbers...)
Multiplies all arguments. Result is float if at least one of the arguments is float. Otherwise it is an integer.
References muse_expect(), MUSE_FLOAT_CELL, MUSE_INT_CELL, and muse_message().
muse_cell fn_div (muse_env * env, void * context, muse_cell args)
(/ ...numbers...)
Takes 1 or more arguments.
(/ m) gives 1/m
(/ m n) gives (m/n)
(/ m n o p) gives (m / (n * o * p))
References muse_expect(), MUSE_FLOAT_CELL, MUSE_INT_CELL, muse_message(), and MUSE_NIL.
muse_cell fn_idiv (muse_env * env, void * context, muse_cell args)
(i/ numerator denominator)
Takes 2 arguments. Divides first by the second and returns the quotient. Arguments must be integers.
muse_cell fn_mod (muse_env * env, void * context, muse_cell args)
(% numerator denominator)
Takes 2 arguments and returns the floating point or integer remainder on dividing first by the second. It does a proper modulo operation unlike C/C++
the sign of the denominator is discarded and the result is always in the range [0,denom) irrespective of the sign of the numerator.
muse_cell fn_inc (muse_env * env, void * context, muse_cell args)
(++ c)
Increments the integer contents of the given cell.
muse_cell fn_dec (muse_env * env, void * context, muse_cell args)
(-- c)
Decrements the integer contents of the given cell.
muse_cell fn_trunc (muse_env * env, void * context, muse_cell args)
(trunc float-value)
Converts a float to int. If given an integer argument. returns it as is.
References MUSE_FLOAT_CELL.
muse_cell fn_rand (muse_env * env, void * context, muse_cell args)
(rand M [N])
Generates a random number.
(rand N) returns an integer random number in the range [0,N)
(rand M N) returns an integer random number in the range [M,N)
(rand F) returns a float random number in the range [0,F).
(rand G F) returns a float random number in the range [G,F).
References MUSE_FLOAT_CELL, MUSE_INT_CELL, and MUSE_NIL.
muse_cell fn_pow (muse_env * env, void * context, muse_cell args)
(pow base exponent)
Computes base ^ exponent. The result is always a float.
muse_cell fn_unary_math (muse_env * env, void * fn, muse_cell args)
The function that calls the supplied unary math operator in the "context" field on the given argument.
The supported unary math operations are -
sqrt
log
log10
exp
sin
cos
tan
asin
acos
atan
sinh
cosh
tanh
asinh
acosh
atanh
fabs
floor
ceil
Referenced by muse_math_load_common_unary_functions().